### ISSUE TITLE
File Rejection with odd error

### ISSUE THREAD

**Issue by eanders** [MollyMcEvilley/LSASampleCode#1001]
@JulesABrown I'm getting an odd error with a small data set of real data.  Any chance you can shed some light on what this is implying?
This is error 1301

> Since your LSACalculated file has a row ({population1_description}) with a value 1176 in the Population column, you must also have at least one row ({population2_description}) where the value of Population is 11.
[module.upload-errors.pdf](https://github.com/HMIS/LSASampleCode/files/9881353/module.upload-errors.pdf)

**Comment by eanders** [comment]
@JulesABrown I mis-spoke on the call, _this_ report does have clients.
LSACalculated.csv attached.
[LSACalculated.csv](https://github.com/HMIS/LSASampleCode/files/9881453/LSACalculated.csv)

**Comment by JulesABrown** [comment]
@eanders We have corrected this. Populations 1176 and 1177 are not subsets of Population 11. Please attempt this upload again to confirm that you are no longer receiving this flag.

**Comment by eanders** [comment]
Thanks @JulesABrown, the data set no longer triggers the issue.
