### ISSUE TITLE
HDX Upload error

### ISSUE THREAD

**Issue by eanders** [MollyMcEvilley/LSASampleCode#1002]
I'm receiving the following error with a data set.  It looks like translations are still broken, so I can't tell what populations might be triggering it.  Could you help?
```
Since your LSACalculated file has a row ({population1_description}) with a value 30 in the Population column, you must also have at least one row ({population2_description}) where the value of Population is 63.
```
This is on row 1318.  See attached.
[LSACalculated.csv](https://github.com/HMIS/LSASampleCode/files/9889767/LSACalculated.csv)
[module.upload-errors.pdf](https://github.com/HMIS/LSASampleCode/files/9889769/module.upload-errors.pdf)

**Comment by JulesABrown** [comment]
I see the issue and we will make a correction to this.

**Comment by JulesABrown** [comment]
This fix has been pushed.
