### ISSUE TITLE
HDX Server Processing Error

### ISSUE THREAD

**Issue by eanders** [MollyMcEvilley/LSASampleCode#1004]
I'm attempting to test another real file on the beta HDX 2.0 and getting the following errors.
```
Server Processing Error (2)
Upload ID: 574: App\Jobs\ProcessUpload has been attempted too many times or run too long. The job may have previously timed out.

Server Processing Error
Upload ID: 574: Failed to authenticate on SMTP server with username "5a2a58c889cc93" using 3 possible authenticators. Authenticator CRAM-MD5 returned Expected response code 235 but got code "535", with message "535 5.7.0 Monthly messages limit reached ". Authenticator LOGIN returned Expected response code 250 but got an empty response. Authenticator PLAIN returned Expected response code 250 but got an empty response.
```

[module.upload-errors.pdf](https://github.com/HMIS/LSASampleCode/files/9913854/module.upload-errors.pdf)

**Comment by MichelleNevius** [comment]
I had this experience yesterday or the day before, and when I tried again, my file went through. But I just hit this again just now-- mine was Upload ID 575.

**Comment by LaurenBianchi** [comment]
We are also receiving this server processing error.

**Comment by JulesABrown** [comment]
Yep, this appears to be a larger issue that's cutting across the sites right now. I will update this ticket when we get resolution.

**Comment by JulesABrown** [comment]
A few rounds of fixes have been pushed on this, so I'm closing.
