### ISSUE TITLE
beta HDX 2.0 Upload: "There is an issue with the data quality checks on your dataset. Please report this issue to your data liaison as soon as possible." message

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1005]
Hi @JulesABrown ,

After LSA file was accepted but instead of Flags list I get "There is an issue with the data quality checks on your dataset. Please report this issue to your data liaison as soon as possible." message. 

My submission: https://hdxdev.abtsites.com/dataset/590/warning

![image](https://user-images.githubusercontent.com/28144855/199748741-60b9f59f-4965-4e62-9f3f-44d3c7a1f535.png)

Please advise.

Best regards,
Natalie

**Comment by JulesABrown** [comment]
We're seeing that too as of this AM with a push we're working in dev. Hold pls. 

Note that as of this afternoon, we'll be ready to port y'all over to a more stable sandbox.

**Comment by JulesABrown** [comment]
I still have this flagged as an issue, but it has been deprioritized over red banner issues on datasets in prod. The red banner errors are file/CoC-specific issues, so I don't want to keep this particular file on our list if the file itself is not still needed. Is this specific dataset needed by the CoC or do they have a more recent upload that is working for them without red banner errors? @nataliesus

**Comment by JulesABrown** [comment]
@nataliesus this should be resolved now.
