### ISSUE TITLE
11/3 Test Kit issues

### ISSUE THREAD

**Issue by KAdlerCW** [MollyMcEvilley/LSASampleCode#1006]
There are a few issues in the 11/3 HMIS CSV. We were able to clean them up manually and successfully import the file, but I am posting them here in case they cause issues for others. 

- There are 233 duplicate client records in Client.csv. The duplicate rows have an ExportID of '2022LSATestNov0311am' and 'E79AAC483B90809B4FDFFB272AA252BD'. 

- There are 135 duplicate records in Exit.csv. Like Client.csv, the duplicate rows have an ExportID of '2022LSATestNov0311am' and 'E79AAC483B90809B4FDFFB272AA252BD'. 

- There are 272 HealthAndDV records with a 0 in WhenOccurred which is not an allowed value for this field in the Data Dictionary. 

- Our tool also flagged errors for Client, Enrollment, EnrollmentCoC and HealthAndDV having rows that were empty strings.

Thanks

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

Could you please also provide an updated LSA CSV Export.zip based on the new&fixed LSA test kit and the updated sample code?

Thank you!

**Comment by MollyMcEvilley** [comment]
Thank you both so much!  I have pushed out a new improved HMIS CSV Export and LSA CSV Export.  

Edit:  I have also updated the temp tables.
