### ISSUE TITLE
New LSA Sandbox site: Upload Error

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1007]
Hi @JulesABrown ,

https://hdxsandbox.abtsites.com/module/lsa/uploads/55

Here is the issue we have on the new LSA Sandbox site (previously, it was fixed on https://hdxdev.abtsites.com )

![image](https://user-images.githubusercontent.com/28144855/199862547-6c796469-fd50-4a53-9714-b6c7d3b5cf0a.png)

Could you please advise?

Thank you!
Natalie

**Comment by JulesABrown** [comment]
Yes, this issue was fixed on dev, but has not been pushed out to prod or sandbox yet. This will be fixed with a push we're hoping to do later today.

**Comment by JulesABrown** [comment]
This fix has been pushed.
