### ISSUE TITLE
LSACalculated - FlagID 1301

### ISSUE THREAD

**Issue by TanyaPieterse** [MollyMcEvilley/LSASampleCode#1009]
Hi Jules and Molly,

I updated our report to use Molly's latest Code up to yesterday November 3rd.  Then I tested the uploads with 3 sets of data.  One set was successful, but the others were both rejected again for ID 1301, LSACalculated has a row with Population=35 but there are no rows with Population=52.  

Both LSACalculated files are attached.  
[LSACalculated_1.csv](https://github.com/HMIS/LSASampleCode/files/9941548/LSACalculated_1.csv)
[LSACalculated_2.csv](https://github.com/HMIS/LSASampleCode/files/9941549/LSACalculated_2.csv)

Do you have any insight?
Thanks,

![image](https://user-images.githubusercontent.com/44713006/200061768-22dcc753-4d27-4c09-9b47-c9e34760c132.png)

**Comment by TanyaPieterse** [comment]
Hi,
With another dataset, we received 2 more combinations for Flag ID 1301 that is causing the upload to be rejected:
- Population=25 but no records with Population=58
- Population=31 but no records with Population=64

Here is the LSACalculated file:
[LSACalculated.csv](https://github.com/HMIS/LSASampleCode/files/9941839/LSACalculated.csv)


![image](https://user-images.githubusercontent.com/44713006/200071159-168f00e7-6e71-4e39-bef5-c77960fa14f2.png)

Thanks,

**Comment by MollyMcEvilley** [comment]
The records for Population 35 are for ReportRows 4,5,6,7, & 9 -- LSAHousehold averages -- which are not reported for population 52.  There are no records for Population 35 in the counts, so this is an HDX issue.

The records for Population 25 are for ReportRow 23 (LSAExit averages -- which are not reported for Population 58.  There are no records for Population 25 in the counts, so this is an HDX issue.

The records for Population 31 are also for ReportRow 23.  Again, LSAExit averages are not reported for Population 64 and there are no reccords for Population 31 in the counts, so this is an HDX issue.

**Comment by JulesABrown** [comment]
This is a known and standing issue, per the weebly (https://www.weebly.com/editor/main.php#/). Our intent is to push fixes to this flag EOD today.

**Comment by TanyaPieterse** [comment]
Hi Jules,
Thank you so much!  I will have a look at the weebly link - thank you for all the guidance through this!

**Comment by JulesABrown** [comment]
This fix has been pushed.
