### ISSUE TITLE
LSA CSV Export.zip: LSAHousehold.csv and LSACalculated.csv - issue with more than 1 Header row

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1010]
Hi @MollyMcEvilley ,

It looks like you have header row in LSAHousehold.csv not only on the first row, but also on 427 and 863. perhaps, data were inserted 3 times.
![image](https://user-images.githubusercontent.com/28144855/200135554-74d74f5c-d3e5-41d3-8656-e42a61f4c589.png)

Also. LSACalculated.csv has a similar problem:
![image](https://user-images.githubusercontent.com/28144855/200135989-591b00b9-5f8a-4326-b237-2d998a86d177.png)

These issues cause validation errors on our side. Could you please take a look?

Thank you!
Natalie

**Comment by JulesABrown** [comment]
LSACalculated also has an extra column. This version uploads.
[LSA CSV Export_2022.11.07.zip](https://github.com/HMIS/LSASampleCode/files/9954021/LSA.CSV.Export_2022.11.07.zip)


EDITED: this version is getting a ton of flags - I suspect another file had multiple pastings of data causing the calculated values to look different from LSACalculated. @MollyMcEvilley, if you want to assign that investigation to me, just put the ticket over to me.
