### ISSUE TITLE
Follow up for #994: LSA CSV Export Temp Tables.zip: sys_Time.csv dates in 2012 year

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1011]
Hi @MollyMcEvilley ,

#994 was resolved, but the most recent sys_Time.csv has dates in 2012 year again.
![image](https://user-images.githubusercontent.com/28144855/200136851-00e6ac84-7b34-4cb5-a843-5791e9caa70d.png)

Could you please take a look?

Thank you!
Natalie

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

Did you have a chance to take a look at dates in 2012 year? These records cause the discrepancy in the system that was developed to compare 2 LSA reports.

Also, there is a difference in HousedDays calculated in our System comparing with LSA Sample Output because of the dates in sys_Time table within [2012-10-01; 2014-09-30].
![image](https://user-images.githubusercontent.com/28144855/205205898-23f1fbdd-e38c-4aea-a721-8fb6fdb0c154.png)

I.e. in tlsa_Household.csv for [HoHID = 90679 & HHType = 1] in our system we have PSHHousedDays = 2922, but in LSA Sample Output PSHHousedDays is 3652. There are several records in tlsa_Household.csv with a similar issue. And it also causes discrepancies in lsa_Household.csv files.

I just want to confirm that 01 Temp Reporting and Reference Tables.sql has a correct calendar start date and this is the only place where 10/1/2012 should not be updated with [report start date] - 7 years (which is a bit tricky because 10/1/2012 was removed from LSA spec):

![image](https://user-images.githubusercontent.com/28144855/205207525-9e7387a8-1a90-4db4-8ca0-9ac88d9e4320.png)


Could you please take a look?

Thank you!
Natalie

**Comment by nataliesus** [comment]
just in case, under #970 @TanyaPieterse asked: `Should we change the @start date to also indicate ReportStart - 7 years?` but perhaps it was overlooked...

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

Just in case there are any updates for calendar start date....

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

Just in case you had a chance to look at [calendar start date] = 10/1/2012 and not [report start date] - 7 years. It causes the discrepancy not only with sys_Time.csv but also with [PSHHousedDays] column for tlsa_Household.csv and lsa_Household.csv...

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley , @kiadso ,

Just in case you had time to take a look at this ticket...

**Comment by MollyMcEvilley** [comment]
Closed by the commit referenced above
