### ISSUE TITLE
Flag Issue: Flag ID #1195-1.0

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1012]
Hi @JulesABrown ,

Could you please investigate Flag ID #1195-1.0? It looks like there is an issue in flag calculation because we have [CHBedInventory] = 36 ProjectType = 3 and HouseholdType = 3 in Inventory.csv file.

https://hdxsandbox.abtsites.com/dataset/70/warning

![image](https://user-images.githubusercontent.com/28144855/200395387-4d597e0a-7f2d-41ef-bbe9-3f982469c165.png)
![image](https://user-images.githubusercontent.com/28144855/200395863-8bb48f6e-7add-4821-9ad5-36262573d686.png)

Please also check other != HIC count flags as it looks like they have issue too.

Thank you!
Natalie

**Comment by JulesABrown** [comment]
Yep, the HIC issues are identified and it looks like that flag is on the list as a problem: https://hudhdx2infoissues.weebly.com/

**Comment by LaurenBianchi** [comment]
Another customer reported a similar issue/flag being thrown for 905-1.

**Comment by JulesABrown** [comment]
Sent that one over to the flag team - thanks

**Comment by nataliesus** [comment]
Hi @JulesABrown ,

Can Flag 1166-1 also be investigated? Thank you very much!

**Comment by JulesABrown** [comment]
Just updating that these are still under investigation. We have tested a fix to no avail, so we are still working through the issue.

**Comment by JulesABrown** [comment]
These fixes got pushed out to the HDX 2.0 last week, so I'm closing out this ticket.
