### ISSUE TITLE
Flags 1245 and 1246: suggestion to fix them in Sample Code

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1015]
Hi @MollyMcEvilley ,

Last year there were 2 tickets about flags 1246 and 1245:

- #883
- #903

@bayboos described the scenario and a solution to fix it:

> 
> We have a client who have one enrollment in the TH project. This client is a child, but also HoH since it’s a single person household. Obviously, such household/enrollment have HHType = 3 - children only. The flag is being triggered because, for a Population = 76, he is being matched with referrence population 76/0 (people who are 18 to 21 years old in all household types) but not with 76/3 (people who are 18 to 21 years old in children only household) - simply because such ref population does not exist. And this does make sense, having an adult person in children only household is not possible.
> 
> Thus, we can assume that the 76/0 match is incorrect; however the query that does the matching (9.4.1) doesn’t seem to be able to exclude this match. The only condition using any age-related values is this: hhid.ActiveHHType = ph.HHType or ph.HHType = 0 which is correctly excluding the client from household type specific counts (within the relevant population) but does nothing to exclude him from the “all types” count.
> 
> **The first possible solution that comes to my mind would be to add additional sub-query to check if the hhid.ActiveHHType is within Population-allowed values when ph.HHType = 0 is being used**; but such solution 1) should be approved before implementation, 2) with similar approval, may need to be added to other similar queries (especially the ones dealing with age-related populations), and 3) may have a negative impact on the querry’s performance.

@kiadso confirmed:
>those two flags definitely fall under the same "clients aging across Household Types" umbrella. Classifying these as Warnings means we recognize the data may be valid.

----

This year Flags 1245 and 1246 were enabled (please see https://hudhdx2infoissues.weebly.com/  ; Resolved Error/Warning Issues section):
![image](https://user-images.githubusercontent.com/28144855/204175031-3e35170a-66ac-4892-9ca9-af8d84b82343.png)

And we receive a lot of these flags and Customers are expecting us to fix them.
Here is one of our flags (with flag description):
![image](https://user-images.githubusercontent.com/28144855/204176094-0abc4452-303c-4767-bdbf-2d7d06624bf9.png)

According to LSA Spec ( instructions for row 55 and Population 76) HHType = 3 is not allowed:
![image](https://user-images.githubusercontent.com/28144855/204176264-9a01f794-798d-4b58-8c7e-4ecc33d4a1e2.png)
So I believe HHType = 0 should be aggregate for HHTypes = 1,2,99 excluding HHType = 3, correct? 

But in Sample Code there is no logic to exclude HHType = 3 from HHType = 0 row 55 and Population 76. That is the question.
 
To resolve Flags 1245 and 1246 in our LSA implemention I used the idea @bayboos suggested:
1) added [HHTypeAllowed] varchar(10) column to ref_PopHHTypes table;
2) run SQL query to set HHTypeAllowed as a list of allowed HHTypes for the particular PopID

```
UPDATE ref_PopHHTypes AS ph
   SET ph.HHTypeAllowed = ph.HHType;

UPDATE ref_PopHHTypes AS ph
  JOIN (
       SELECT ph2.PopID, GROUP_CONCAT( ph2.HHType SEPARATOR ',' ) AS HHTypeAllowed
         FROM ref_PopHHTypes AS ph2
        WHERE ph2.HHType != 0
        GROUP BY ph2.PopID
        ORDER BY NULL
     ) AS tmp ON ( ph.PopID = tmp.PopID )
   SET ph.HHTypeAllowed = tmp.HHTypeAllowed
 WHERE ph.HHType = 0;
```
3) for queries like
![image](https://user-images.githubusercontent.com/28144855/204176776-4e9edc84-3400-45a7-9c5c-8af4aa55435e.png)
I replaced ```or ph.HHType = 0``` with ```OR ( ph.HHType = 0 AND FIND_IN_SET( hhid.ActiveHHType, ph.HHTypeAllowed ))```
4) Flags 1245 and 1246 are no longer reported.

Could you please take a look if Sample Code should also be updated similar way? Or how else we can resolve flags 1245 and 1246?

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
HHType = 0 should be a count regardless of household type.  Under the current circumstances, these flags will come up for people who age into adulthood during the report period.  Jules is putting in a request for a threshold for the flags -- so that they will only trigger when the discrepancy falls outside of the norms.

**Comment by JulesABrown** [comment]
I did get approval to add a threshold for these flags. That fix will be forthcoming, but at the cadence we seem to be working, we're probably looking at next week to implement the threshold. Closing this out.

**Comment by JulesABrown** [comment]
One additional comment for posterity: even if the flag trips, if the *reason* is because all those clients are in CO HHtype on that PIT date, then the resolution for the warning is to enter a note stating that. The research team needs to document that that is the case; they are not asking you to eliminate the warning if the data are accurate.
