### ISSUE TITLE
tlsa_CountPops: HouseholdID for Population IDs 51, 52, 56, 57, 58, 59, 60, 61, 62, 63, 1176, 1177, 1276, 1277

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1017]
Hi @MollyMcEvilley ,

Not an issue, just found a discrepancy in tlsa_CountPops.csv in our report implementation comparing with the sample output so want to confirm with you just in case sample code will be updated for the current or for the next fiscal year.

According to the Spec (Section 9.4), next Population IDs are used for report row 55:
 50, **51, 52**, 55, **56, 57, 58, 59, 60, 61, 62, 63, 1176, 1177, 1276, 1277** and some others. Listed Population IDs are only used for report row 55 only, not for any other report row id.

**My question is about Population IDs in bold: 51, 52,56, 57, 58, 59, 60, 61, 62, 63, 1176, 1177, 1276, 1277.**

I.e. for Population IDs 50 and 55 only [PersonalID] is inserted into tlsa_CountPops table. But both [PersonalID] and [HouseholdID] are inserted into tlsa_CountPops table for the Population IDs in bold:
![image](https://user-images.githubusercontent.com/28144855/205467825-a4e7b7cc-501f-49fb-af9d-26a48496785b.png)

On Step 9.4.1 (when data are inserted into lsa_Calculated table for report row 55) only [pop.PersonalID] is used, [pop.HouseholdID] is not used:
![image](https://user-images.githubusercontent.com/28144855/205467101-ab14a2bb-22d3-4bf8-aafa-3e427fdfc8c0.png)

So I wonder why we insert [HouseholdID] into tlsa_CountPops table for Population IDs 51, 52,56, 57, 58, 59, 60, 61, 62, 63, 1176, 1177, 1276, 1277 and not use it in step 9.4.1? Was it just copy/paste and can be removed? Or [HouseholdID] should be added to calculations in step 9.4.1? Could you please advise?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
HouseholdID was being inserted to tlsa_CountPops for populations 56-71 -- Race, Ethnicity, Gender.  This was totally superfluous -- none of those characteristics change from enrollment to enrollment, nor are they dependent on any household characteristics.  I removed HouseholdID from the insert statements for those populations in steps 9.1.17-9.1.19,  There should be no change to output related to these populations.

HouseholdID IS relevant to 51 (Parenting Youth 18-24) and 52 (Parenting Child), but, as you pointed out, it wasn't used in step 9.4.1.  I have added HouseholdID to the join between tlsa_Enrollment and tlsa_CountPops, WHICH MAY RESULT IN A CHANGE TO POINT-IN-TIME COUNTS FOR THESE 2 POPULATIONS.

![image](https://user-images.githubusercontent.com/6156815/207428073-f1fd4b8e-6abd-490b-87b4-3a72d64d70a1.png)

**Comment by JulesABrown** [comment]
Edited!

There is a flag that may be resolved by this issue, flag 693. CoCs with this flag associated with either Parenting Youth 18-24 or Parenting Children may see the flag resolved by this fix.

These flags look like this, but there are many variations
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/BrownJ/AppData/Local/Temp/1/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/BrownJ/AppData/Local/Temp/1/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link=blue vlink=purple>



Count of people with   characteristic (ReportRow=55) where Cohort=1 (Active in the current report   period) & Universe=13 (TH Project Type) & HHType=2 (AC (adult &   child)) & Population=5167 (Parenting Youth (18-24) who are Female) | 1 | Count all people in household (ReportRow=53)   where Cohort=1 (Active in the current report period) & Universe=13 (TH   Project Type) & HHType=2 (AC (adult & child)) & Population=12   (Parenting Youth households (where the oldest adult is 18-24)) | 0
-- | -- | -- | --
Count of people with characteristic   (ReportRow=55) where Cohort=1 (Active in the current report period) &   Universe=13 (TH Project Type) & HHType=2 (AC (adult & child)) &   Population=5165 (Parenting Youth (18-24) who are Non-Hispanic/Latin(a)(o)(x)) | 1 | Count all people in household (ReportRow=53) where Cohort=1 (Active in   the current report period) & Universe=13 (TH Project Type) & HHType=2   (AC (adult & child)) & Population=12 (Parenting Youth households   (where the oldest adult is 18-24)) | 0
Count of people with characteristic   (ReportRow=55) where Cohort=1 (Active in the current report period) &   Universe=13 (TH Project Type) & HHType=2 (AC (adult & child)) &   Population=1276 (Youth (18-21) in an AC Parenting Youth Household) | 1 | Count all people in household (ReportRow=53) where Cohort=1 (Active in   the current report period) & Universe=13 (TH Project Type) & HHType=2   (AC (adult & child)) & Population=12 (Parenting Youth households   (where the oldest adult is 18-24)) | 0



</body>

</html>

**Comment by JulesABrown** [comment]
Note that we have posted an announcement to the weebly for CoCs. They are aware that this issue exists, that we have requested that affected vendors implement a code fix, and that they are expected to reupload after their vendor notifies them the fix has been implemented.
