### ISSUE TITLE
Spec issue: tlsa_Enrollment.ActiveAge = 18 for PopID 1176, 1276

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1018]
Hi @MollyMcEvilley ,

Sample Code step 9.1.21 uses tlsa_Enrollment.ActiveAge = **21** for PopID 1176, 1276:
![image](https://user-images.githubusercontent.com/28144855/205468013-1bda74f0-4829-489e-a57a-31217766bd59.png)

According to spec, only tlsa_Enrollment.ActiveAge = **18** should be used for PopID 1176, 1276:
![image](https://user-images.githubusercontent.com/28144855/205468368-ee9eb007-0377-4311-aa7e-96d9e71ed743.png)

tlsa_Enrollment.ActiveAge = 18 is not in the allowed list, so it looks like Spec should be corrected replacing tlsa_Enrollment.ActiveAge = 21 with tlsa_Enrollment.ActiveAge = 18.

Could you please take a look?

Thank you!
Natalie

**Comment by JulesABrown** [comment]
This commit reflects the start of changes to the Specs from the 508'd v1.0 posted to the HUD Exchange https://www.hudexchange.info/resource/5726/lsa-report-specifications-and-tools/
