### ISSUE TITLE
LSA CSV Export.zip: LSAReport.csv possible issue with [NoCoC]

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1020]
Hi @MollyMcEvilley ,

There is [NoCoC] = 3 in LSAReport.csv in Sample Output. But in our implementation [NoCoC] = 0. I think there is an issue with Sample Code. Could you please take a look who and why is counted for [NoCoC] = 3?

I think of scenario when:
- Program A has 2 Program CoCs: XX-500 and XX-501.
- Client has an enrollment into Program A with [client_location] = XX-501
- LSA report is run for CoC = XX-500

So in fact [client_location] exists, is in one of the allowed Program CoCs, but the household is reported for [NoCoC].

![image](https://user-images.githubusercontent.com/28144855/205470175-868e1f60-6b9d-42e8-892b-71c134d8e129.png)

Could you please take a look? Maybe I am doing something wrong...

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Thank you!
