### ISSUE TITLE
LSAReport.csv: MoveInDate = 23 question

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1021]
Hi @MollyMcEvilley ,

Could you please provide a few clients who are counted for LSAReport.csv: MoveInDate = 23? I have MoveInDate = 0 and cannot catch the issue who is not counted. Having a client example will help a lot.

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
These may have been MoveInDates that were dated after ReportEnd... The current code produces 0 for MoveInDate -- I will upload an updated test kit.
