### ISSUE TITLE
LSACalculated.csv: question about AVG() usage for [Value] column

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1022]
Hi @MollyMcEvilley ,

Comparing LSACalculated.csv I have many rows with a discrepancy in [Value] column. Our [Value] is Sample Output [Value] + 1.
![image](https://user-images.githubusercontent.com/28144855/205530470-563e9650-f249-4a63-9ce1-ab191f53167e.png)

In the Spec it is said that Value = the average of ... **rounded to the nearest whole number**:
![image](https://user-images.githubusercontent.com/28144855/205530323-739e7e0d-1363-4247-a8b4-c4b7f9b78ca5.png)

I.e. we have 2 records with RRHPSHPreMoveInDays = [3, 36] and their average is ( 3 + 36 ) / 2 = 39 / 2 = 19.5, and in MariaDB it is **20** stored in INT column when 19.5 is inserted into DB table. But in Sample Output it is **19**. Which one is correct? I want to make our results identical, so should it be 19 instead of 20?

Please see row in LSACalculated.csv for:
- RowID = 4
- HHType = 0
- PopID = 13
- SystemPath = 6

Please advise.

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
The result of the built-in average function for SQL Server is 19.  If the result of your built-in average function is 20, that is fine -- it may not be possible to make the results identical.

**Comment by nataliesus** [comment]
Thank you for looking into this! So if the average is i.e. 19.5, then [Value] = 19 (I want to make our system matches values from Sample Output). One last question, if the average is i.e. 19.6 then [Value] should be 20 (rounded to the nearest whole number), correct? Or it should be 19 anyway?

**Comment by MollyMcEvilley** [comment]
SQL Server ignores everything that would fall to the right of the decimal when averaging or dividing integers -- the result of "SELECT 191/10" is 19.  The result of "SELECT 199/10" is 19.  The result of "SELECT cast(19.9 as int)" is 19.

The critical part of the specs for this is "or the result of a built-in AVERAGE or AVG function... when the datatype of the parameter is _integer_."
