### ISSUE TITLE
LSACalculated.csv: unexpected Population IDs are reported for Universe 10 report row 55 

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1023]
Hi @MollyMcEvilley ,

According to Spec, ProjectID (**Universe 10**) **report row 55** is required for Population IDs [50, 53, 1176, 1177, 1276, 1277] **only**.
![image](https://user-images.githubusercontent.com/28144855/205652407-e523c9f9-be78-4d3e-8e4a-1332133b264a.png)

LSACalculated.csv from Sample Output has a lot more Population IDs reported (i.e. 55, 56 etc) that shouldn't be there:
![image](https://user-images.githubusercontent.com/28144855/205652329-ae4e58f1-0687-404e-a781-1a58c6d80716.png)

It looks like there is an issue in Sample Code step 9.4.1 so `((rv.Universe = 10 and rp.ByProject = 1) or rp.ByProject is NULL)` should be replaced with `if(rv.Universe = 10, rp.ByProject = 1, rp.ByProject is NULL)` :
![image](https://user-images.githubusercontent.com/28144855/205650714-e25ba452-620b-48b9-8b9b-e62d80b1b0c2.png)

Could you please take a look?

Thank you!
Natalie

**Comment by nataliesus** [comment]
Hi @JulesABrown , 

I just wonder if there are any flags that report impossible combinations such as those described above.

**Comment by JulesABrown** [comment]
@nataliesus We do not have any flags about LSACalculated having "too many" rows at this time and don't have a plan to add them at this time. Unless the file gets so big that it can't be managed, there's no real harm in having more info about those pop groups.
