### ISSUE TITLE
New Sample Output

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1025]
Hi @MollyMcEvilley ,

You have updated several places in Sample Code recently. Could you please provide the updated Sample Output as well? It will help a lot to minimize discrepancies between Sample Output and our report results so we can continue investigating the discrepancies.

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
I updated the sample output again just a minute ago -- I made an unanticipated change to the code in file 09 -- see issue #1017.
