### ISSUE TITLE
Flag 967-130.187

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1027]
Hi @kiadso ,

Submission: https://hdxsandbox.abtsites.com/dataset/212/warning

Flag 967-130.187 has a description:
All households: You reported that zero people were served (active in residence) during the entire report period in this HMIS-participating project, _our_project_name_here_. Please confirm if this is correct and explain any reasons why no people were served.

The reason why ho household is reported is Organization.VictimServiceProvider = 0 so no Household is inserted into tlsa_HHID table.
At the same time. both project and its organization are reported in Organization.csv and Project.csv files.

It is not an issue, correct? We have several flags reported for the same reason. Could you please advise what explanation the Customer should provide to their liaison?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Closing out issues from previous years because these flags have been reworked for FY2023 reporting.
