### ISSUE TITLE
Flag 1300 LSACalculated ReportRow 23 and ReportRow 63

### ISSUE THREAD

**Issue by kcourtneywellsky** [MollyMcEvilley/LSASampleCode#1029]
One of our communities is receiving Flag 1300 when uploading their LSA. This is preventing their LSA results from being accepted. The issue pertains to a person with two RRH enrollments, and in one of the enrollments, no Housing Move-In Date exists.

Flag 1300 states "Since your LSACalculated file has a row with the value 23 in the ReportRow column, you must also have at least one row where the value of ReportRow is at least one of 18-22." ReportRow 23 is "Average days to return after exit (all)", and the 18-22 values are Exits by Project Type, so 21 is "Average days to return after exit from RRH". Then there are two other ReportRows in the same category, 63 "Average days to return after exit from RRH with no move-in date" and 64 "Average days to return after exit from PSH with no move-in date". It seems the flag is trying to alert that there is a summary row (23) with no accompanying detail rows (18-22). I believe that the flag should also look for ReportRows 63 and 64 as well, since those are possible values for "LsaExit by Project Type". 

In this situation, LSACalculated contains a ReportRow 23 and a ReportRow 63 for the person's household. Given that during one of the RRH enrollments, the person did not move in to housing and so there was not a Housing Move-In Date, Flag 1300 should allow for ReportRows 63 and 64 if ReportRow 23 exists.

**Comment by MollyMcEvilley** [comment]
Closing out FY2023 issues
