### ISSUE TITLE
5.1.1 Latest Enrollment CoC

### ISSUE THREAD

**Issue by jbloescw** [MollyMcEvilley/LSASampleCode#1030]
Can anyone clarify for me in section 5.1.1; when we return the latest enrollment CoC, that it does or does not matter the project types of said later enrollment CoC?  The code/specs don't look at project types but want to confirm.  
Should those later enrollment cocs be only of lsa project types or no?

**Comment by MollyMcEvilley** [comment]
In step 5.1.1, we are specifying, for each HoH enrollment that overlaps the report period, whether or not the most recent (relative to ReportEnd) EnrollmentCoC record **FOR THAT EnrollmentID** matches ReportCoC.  Other enrollments and/or project types are not relevant to the logic here.

![image](https://user-images.githubusercontent.com/6156815/224116230-96b31169-9aed-42cf-89d8-53c112412cd7.png)

**Comment by MollyMcEvilley** [comment]
Hey Jeff, I am going to close this as an answered question.  If you have follow-up questions or want to set-up a session to talk this through, send Jules an email and he will schedule.
