### ISSUE TITLE
Spec Section 5.11: copy-paste issue with PSHAgeMinRRHSOAgeMin and PSHAgeMaxRRHSOAgeMax

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1034]
Hi @MollyMcEvilley ,

Could you please take a look and fix if needed the highlighted text:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/d04a1d2e-e6b0-41c0-9461-fc68a90358d0)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
PSHAgeMin and Max are deleted in the version of the specs in [this commit](https://github.com/HMIS/LSASampleCode/commit/c32e1440ffd16615171bc45c966c4712fc8b9ca4).
