### ISSUE TITLE
LSA Data Dictionary FY2023: DataType = varchar and some depricated columns

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1035]
Hi @MollyMcEvilley ,

**1.** In sample code DataType = varchar was replaced with DataType = nvarchar. Just in case LSA Data Dictionary FY2023 should also be updated. i.e.
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/eb2a8d97-a4b5-4f49-824c-2f45c78b5a3b)

**2.** We need to remove HoHRace and HoHEthnicity, and add HoHRaceEthnicity for lsa_Household and LSAExit (it affects also Column Number value)

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/e430070b-5e7e-4424-ab2c-cff8cd5e4fde)
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/6acbf50e-01ba-4f42-8a52-4f26458691db)

**3.** "Files" tab needs update because of changes in LSAExit
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/5f83b604-549f-4436-b094-62370a9b9fdd)

Thank you!
Natalie

**Comment by nataliesus** [comment]
In addition,

**4.** Not an issue, but maybe we can replace 10/1/2012 with [report start date - 7 years]?
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/5e6b663c-196b-4ffc-a850-524c6fe127a1)

**5.** I have some conserns about "all Project IDs in Project.csv" text because there is no Inventory record for `ProjectType = 13 and RRHSubType = 1`:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/1416520e-fbba-4908-bca0-e6a693a841ae)

**Comment by JulesABrown** [comment]
- @MollyMcEvilley, I defer to you on item 1
- Removed HoHEthnicity rows in LSAHousehold and LSAExit. Edited HoHRace to HoHRaceEthnicity and revised descriptions. Renumbered columns.
- Edited Files tab to address the edits above and to indicate the similar deletion/revision in LSAPerson.
- Replaced date with [report start date] - 7 years
- Edited Inventory to say "all project IDs with inventory..."
