### ISSUE TITLE
02 LSA Output Tables.sql: lsa_Affiliation table structure needs corrections

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1037]
Hi @MollyMcEvilley ,

It looks like a copy-paste issue in the lsa_Affiliation table structure. Could you please take a look?

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/a8a61596-a8e8-4f29-a033-b9b0bcc7b3a9)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
I looked for a very long time trying to figure out what was wrong with those columns without noticing that they were in the wrong table -- but did figure it out eventually.  :)  Commit forthcoming.
