### ISSUE TITLE
Spec: Section 3.1 - Project Type = 0 is missing

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1041]
Hi @MollyMcEvilley ,

Could you please take a look if Project Type = 0 should be added?

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/4cbffe02-3554-45f4-be79-5bb367752e4e)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Yes, it absolutely should. Commit forthcoming.
