### ISSUE TITLE
Step 3.4.1 - question about [DisabilityStatus]

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1044]
Hi @MollyMcEvilley ,

In the Spec DisabilityStatus logic was removed but:
- DisabilityStatus is bold in the [Target] section
- DisabilityStatus logic is programmed in the Sample Code

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/bbdac780-ca71-4d2b-955a-23952e75bc1c)

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
That was definitely not intentional -- thank you! Undeleting that section as it's fairly critical to subsequent logic...
