### ISSUE TITLE
Sample Code lsa_Inventory: RRHSubType condition needs correction

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1046]
Hi @MollyMcEvilley ,

Could you please update RRHSubType condition, because RRHSubType  is null for ProjectType <> 13
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/9ce3e8bc-1bae-4c12-bf56-7a8d1241e261)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
![image](https://github.com/HMIS/LSASampleCode/assets/6156815/e71245a4-f24d-414c-803a-2e2dafcbd672)
