### ISSUE TITLE
Sample Code Section 4.7: ProjectType condition for ResProjectID is missing

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1051]
Hi @MollyMcEvilley ,

**1.** Spec has condition by ProjectType condition for ResProjectID. But there is no such condition in Sample Code.
BTW, was ProjectType = 9 intentionally excluded from ResProjectID?
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/a08b6d54-9386-4ec0-a127-57c6d557b537)

**2.** There is no "ResProjectID Must match a ProjectID in Project.csv" in Sample Code, so potentially lsa_Affiliation table can have ProjectIDs not included in Project.csv.

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/f5ebbb11-f684-453a-96f0-674ae62453f3)

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Not to sidestep the issue, but there is no difference in the criteria for _ResProjectID_ between the LSA and the HMIS CSV, so I am going to resolve this by deferring to the CSV.

![image](https://github.com/HMIS/LSASampleCode/assets/6156815/e3018a56-5421-41d9-a675-4e944452d728) 

(Edited to update the screenshot after deleting a stray comma.)
