### ISSUE TITLE
Spec Section 5.5 - [LastActive] logic needs correction

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1052]
Hi @MollyMcEvilley ,

It looks like there were no changes for [LastActive] logic in the Spec.
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/d5fd706f-5a5c-42a7-8eb3-3bb4f132ce0a)

But Sample Code was updated:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/c550cde1-86f1-4ecc-8762-0c2a812a9f55)

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
This one is really baffling.  I clearly put some thought into the updates, but I don't remember doing it.  My best guess is that I updated it at the end of last year with the intention to bring it up as a proposed change for this year -- but I really don't remember it.  One way or the other, it's not on the list of approved changes for this year, so I am rolling back the changes.  Thanks for pointing this out.

![image](https://github.com/HMIS/LSASampleCode/assets/6156815/4e0a448b-2c8d-485d-bd2c-4864d1c5fa6f)
