### ISSUE TITLE
07 LSAExit.sql: Step 7.9.1 - issue with HHChronic

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1058]
Hi @MollyMcEvilley ,

Here is the updated spec:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/db1496f3-837d-4226-a7bc-e48861c34de4)

Could you please take a look if `or ch.ch = 4` should be removed from the Sample Code?
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/dd05edc2-17d9-401b-8129-9d6b1bedfe21)

Thank you!

**Comment by MollyMcEvilley** [comment]
Yes it should -- thank you.
