### ISSUE TITLE
07 LSAExit.sql: Step 7.9.1 - HHFleeingDV question

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1060]
Hi @MollyMcEvilley ,

I.e. for [HHVet] age parameter for `between 18 and 65` condition depends on ExitCohort:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/df39519f-091a-4e14-a107-07d83363b4e5)

I wonder if for [HHFleeingDV] calculation we also should use either [ActiveAge] or [Exit1Age] or [Exit2Age] ( depending on [ExitCohort]) instead of [dv.ActiveAge]

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/318170a9-e55a-4f47-90bc-ee4137fdfae3)

Could you please advise?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
You are absolutely right!

![image](https://github.com/HMIS/LSASampleCode/assets/6156815/24b81483-804f-4e4f-a239-f942b0efedb5)
