### ISSUE TITLE
11 LSAReport DQ and ReportDate.sql: [NoCoC] needs correction

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1061]
Hi @MollyMcEvilley ,

**1.** ProjectType = 0 is missing:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/59d0ae07-99e6-417d-b4d4-b05829cf1e31)

**2.**
Spec:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/c5f1242b-eb08-454d-ac22-6b34a676b75d)

Sample Code:
`n.EnrollmentCoC is null` is not the same as `EnrollmentCoC <> any ProjectCoC.CoCCode for the ProjectID` because it does not count the scenario when EnrollmentCoC exists but is not equal to any ProjectCoC.CoCCode.
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/6bfc9c6e-93d6-44f7-86b2-7ac41e8eae52)

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
I've included null values for EnrollmentCoC in the specs criteria for this count:
![image](https://github.com/HMIS/LSASampleCode/assets/6156815/47470bd6-1030-484d-9073-0575b74d4b2b)
And added the condition where EnrollmentCoC isn't in ProjectCoC to the code:
![image](https://github.com/HMIS/LSASampleCode/assets/6156815/352e2dec-b488-46df-b0b5-6be318efc9b1)
