### ISSUE TITLE
11 LSAReport DQ and ReportDate.sql: [NotOneHoH] needs correction

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1062]
Hi @MollyMcEvilley ,

**1.** Could you please add ProjectType = 0 (it already exists in the Spec)
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/0db7e124-3d76-4601-b2da-1198eb5299e7)

**2.**
Spec:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/51823643-3e2d-46de-ae11-e9aeffdbaf6d)

Sample Code:
There is no `EnrollmentCoC = ReportCoC` condition, so two scenarios that should be excluded will be reported:
- a Household with 2+ HoHs where no HoH has EnrollmentCoC 
- a Household with 2+ HoHs where all HoH has EnrollmentCoC **<>** ReportCoC (actual for cases, when Project has more than 1 ProjectCoC)

Could you please take a look?
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/6da56ed5-72e6-478d-aae7-a626e55c9eac)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
1.  Yes, added ProjectType 0 to NotOneHoH (11.2) and also to NoCoC (11.1).
2.  Added EnrollmentCoC = ReportCoC to the WHERE clause in 11.2.
