### ISSUE TITLE
11 LSAReport DQ and ReportDate.sql: LivingSituation condition for consistency with other files

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1063]
Hi @MollyMcEvilley ,

Not an issue, but is it possible to replace `LivingSituation in (101,116,118)` with `LivingSituation between 100 and 199` as it was done in other places in the LSA Sample Code?

**Comment by MollyMcEvilley** [comment]
Yes, it is!  Commit forthcoming.
