### ISSUE TITLE
Spec Section 8.11 - Target -> ReportRow

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1072]
Hi @MollyMcEvilley ,

Could you please replace ReportRow = 37-52 with ReportRow = 101-136 in Target table for section 8.11?

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/f6e466f4-67fd-4da8-b717-0397d67627e7)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Completed with [this commit](https://github.com/HMIS/LSASampleCode/commit/c32e1440ffd16615171bc45c966c4712fc8b9ca4).
