### ISSUE TITLE
Spec Section 10.4 -> Population ID = 97

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1073]
Hi @MollyMcEvilley ,

Sample Code has a record in ref_PopHHTypes table for Population ID = 97 and HHType = 3
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/43fdacf3-8d93-4ec1-bdc4-5ed6312676ec)

But there is no such combination in the Spec:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/801e1f5d-a9a2-4b34-a7c3-a457095c449a)

Could you please take a look at which one should be updated?

---

Also, could you please update "19 subpopulations" text as subpopulation list was changed?

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/54790154-ce9c-4746-bc2c-ec6fe9d32567)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Updated the specs to include HHType 3 for Population 97 and to specify that there are now 34 and not 19 subpopulations...
