### ISSUE TITLE
LSA Data Dictionary FY2023 -> Lists: Population 48, 1348, 1448, 1546, 1548, 97 are missing

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1076]
Hi @MollyMcEvilley,

Spec 8.3 has new "48 - Domestic Violence Survivors Not Identified as Currently Fleeing"
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/dd325ad5-dd34-46d2-97c8-279f4d312c7e)

that is not listed in LSA Data Dictionary FY2023 -> Lists: Population
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/f1db0083-2b0a-47f7-8130-fe073e333a97)

The same situation is with Population = 1348, 1448, 1546, 1548, 97.

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/8291d39f-037d-47fb-b798-5eed816d213e)

Could you please take a look?

Thank you!
Natalie

**Comment by nataliesus** [comment]
Also, Population = 1447 should be removed
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/faa3a682-2f3b-48e8-852b-0d9cd2e61b67)

because there is no Population = 1447 in the Spec:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/00a19d6a-7d74-4dff-a6ee-399c54cd03df)

**Comment by JulesABrown** [comment]
- Added 48, 1348, 1448, and 1548. 
- Added 1546, but @MollyMcEvilley, can you confirm that 1346 was replaced by 1546?
- Removed 1447

**Comment by nataliesus** [comment]
Hi @JulesABrown ,

Could you please also take a look at the missing Population = 97?

Thank you!
Natalie

**Comment by JulesABrown** [comment]
@nataliesus Added - thanks!

@MollyMcEvilley, please check the other outstanding issue on this ticket. Thanks!
