### ISSUE TITLE
LSA Data Dictionary FY2023 -> Lists: duplicate Population rows

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1077]
Hi @MollyMcEvilley ,

Population 5253 - 5271 are listed twice:

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/301a3c95-f81e-492d-9b94-d13a5cc111c2)

Could you please take a look?

Thank you!
Natalie

**Comment by JulesABrown** [comment]
Deleted out second set of duplicates
