### ISSUE TITLE
Spec Section 8.2: several ReportRow IDs are missing

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1078]
Hi @MollyMcEvilley ,

LSA Data Dictionary FY2023 -> Lists tab has ReportRow = 53, 54, 55, 56, 57 and ReportRow between 901 and 920 that are missing n the Spec Section 8.2

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/567b0e4e-89c3-410b-a251-bac5728d12c9)

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/6eea8064-237f-4f62-8c45-2bbcaaa1531d)

Could you please add them?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Rows 901-920 are in section 10 because they are DQ counts.  The logic for the AHAR Counts (rows 53-57) is separate.
