### ISSUE TITLE
Spec: Multi-Racial (not Hispanic/Latina/e/o) issue

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1083]
Hi @MollyMcEvilley ,

(HoH)RaceEthnicity has values 98 and 99:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/290826cd-61c6-4cbc-ae38-d83f3ffd889d)

I want to confirm with you that "Multi-Racial (not Hispanic/Latina/e/o)" should not include (HoH)RaceEthnicity 98 and 99 because now Spec has ` (HoH)RaceEthnicity >=12, does not include a 6` condition that allows 98 and 99 be counted as "Multi-Racial (not Hispanic/Latina/e/o)".

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/8599a202-0671-4043-9abf-2b2f4f79290a)

Steps list to fix:
- 8.3.15
- 8.3.39
- 9.1.18

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Yes, you are absolutely right -- updated specs sections 8.3 and 9.4 as well as sample code in _08 LSACalculated Averages...sql_ and _09 LSACalculated AHAR Counts.sql_. Commit forthcoming.

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

Just in case, Sample Code already has `(HoH)RaceEthnicity not in (98,99)` condition: 
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/2fd30c21-10e7-43c2-8b3c-bfda84618307)
