### ISSUE TITLE
Spec Section 8.2: Report Rows 901-920 are missing

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1087]
Hi @MollyMcEvilley ,

Could you please add Report Rows 901-920 to the table? Now table ends on Row 136.

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/1e55be20-2279-467d-8994-5acafe11d599)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
ReportRows 901-920 are in Section 10 -- they aren't listed in section 8.2 because they are DQ counts and not averages.
