### ISSUE TITLE
Sample Code Step 10.6: ProjectType = 15 is missing

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1094]
Hi @MollyMcEvilley ,

Spec has RRHSSO project type that is missing in the Sample Code:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/c17aa6a6-a900-45eb-8395-fdec20240be1)
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/cf57b5ef-30b6-459b-823e-46f25501e6f0)

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
15 is only an LSAProjectType and doesn't apply here -- the RRH-SO ProjectType = 13 (with an RRHSubType of 1, but it's not necessary to specify that in this query).
