### ISSUE TITLE
Report Row = 907: Sample Code has conditions not listed in Spec

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1095]
Hi @MollyMcEvilley ,

Sample Code has next conditions not used in Spec:
- inner join hmis_Enrollment coc on coc.HouseholdID = hn.HouseholdID and coc.EnrollmentCoC = rpt.ReportCoC
- and hx.ExitDate > hn.EntryDate
- and p.ProjectType in (0,1,2,3,8,13) 
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/6ebc8307-b779-4e9a-a0ab-2b9c0e230303)

Could you please take a look what should be updated?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Closed by [this commit](https://github.com/HMIS/LSASampleCode/commit/c32e1440ffd16615171bc45c966c4712fc8b9ca4).
