### ISSUE TITLE
Report Row = 908: difference between Sample Code and Spec

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1096]
Hi @MollyMcEvilley ,

Sample Code has next conditions not used in Spec:
- inner join hmis_Enrollment coc on coc.HouseholdID = hn.HouseholdID and coc.EnrollmentCoC = rpt.ReportCoC
- hn.RelationshipToHoH is null
- and hx.ExitDate > hn.EntryDate
- and p.ProjectType in (0,1,2,3,8,13) (what is about ProjectType =15?)
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/5eb17f02-5366-493f-bafd-192d74f59753)

Could you please take a look at what should be updated?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Commit forthcoming with all addressed EXCEPT that ProjectType 15 doesn't apply in lsa_Project -- the ProjectType there is 13 with an RRHSubType of 1.
