### ISSUE TITLE
Sample Code Step 10.8: wrong table usage

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1097]
Hi @MollyMcEvilley ,

In Spec it is said to use tlsa_HHID table. Sample Code uses tlsa_Enrollment table. Could you please take a look?

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/2be4e212-f0cb-404e-be05-b2d54393ee6a)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Corrected - commit forthcoming.
