### ISSUE TITLE
Sample Code Step 10.18: x.DateDeleted is null condition is missing

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1098]
Hi @MollyMcEvilley ,

Could you please add `x.DateDeleted is null` condition for 10.18 Sample Code Step as it is done in other steps?
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/6916b3dd-7acd-4c4f-b507-f8153f682b5d)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Corrected - commit forthcoming.
