### ISSUE TITLE
Spec Section 10.12: wrong [DisabilityStat] field is used

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1099]
Hi @MollyMcEvilley ,

Could you please replace [DisabilityStat] with [DisabilityStatus] in the Spec to match Sample Code? 

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/975e8cbf-19b1-4c22-a893-aaf0eb85e51d)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Corrected - commit forthcoming.
