### ISSUE TITLE
Spec Section 8.10: SystemPath value for ReportRow = 36 

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1100]
Hi @MollyMcEvilley ,

Could you please replace `=<>` with `<>`?
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/4919d65d-5972-4297-9cf7-2eed404fce72)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Corrected -- commit forthcoming.
