### ISSUE TITLE
LSA Data Dictionary FY2023 ->LSACalc Values by Row: need corrections

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1101]
Hi @JulesABrown ,

**1.** Just in case. do you think we need a yellow background for new rows to be consistent with other tabs? Now no row is highlighted.

**2.** ReportRow = 23.

In the Spec it is said that ReportRow = 23 is not generated for subpopulations 21 or 22:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/7c43f8b0-22e6-47ce-9bc7-1d25d2adf597)

Could you please add a similar note to LSA Data Dictionary (now it looks like subpopulations 21 and 22 are included)? 
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/5d5055b8-4ec7-464a-a26d-636605a3f06e)

**3.** ReportRow = 36

In the Spec it is said that ReportRow = 36 SystemPath <> -1:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/475ccae0-6f16-4a5e-8fb1-134451e14cc8)

But SystemPath = -1 for ReportRow = 36 in LSA Data Dictionary:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/7972b0db-f2f2-4d06-8fdf-cb7d42401b65)

**4.** ReportRow = 101-116

LSA Data Dictionary has [Universe] = 2 for these rows, but, according to the Spec, it should be [Universe] = 3:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/55d5f504-3d48-4c8f-915e-adf615dcd2dd)

**5.** ReportRow = 134-136

LSA Data Dictionary has [Universe] = 2 for these rows, but, according to the Spec, it should be [Universe] = 4:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/21c82c7e-e28a-4ba1-86f6-a2251b3ab576)

**6.** ReportRow = 53-54

According to Spec, these rows should be available for Population = 48: 
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/176fed33-8ebf-4b20-b3fe-94528ee9f860)

Could you please add Population = 48 to LSA Data Dictionary?
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/0197fe5b-d42b-451f-979f-9f24abf3ccc5)

**7.** ReportRow = 55 and Universe 11-16

According to Spec, ReportRow = 55 should be available for Population = 97:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/77ae287e-f4bc-45e5-bbe5-998f32d8f7f9)

Could you please add Population = 97 to LSA Data Dictionary?
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/4e1ea181-5d9c-4710-a7c7-593320e532d0)

**8.** ReportRow = 901-920

According to Spec, these rows should have [Cohort] = 1: 

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/4abd9637-6ec4-49be-94d2-f7bac350e306)

But it is [Cohort] = 10 in LSA Data Dictionary:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/2313f656-bb20-43de-a60e-dfcdd3789e54)

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
1.  Dictionary - LSACalcValues by Row tab - Added yellow highlighting to changes from FY22
2.  Dictionary - LSACalcValues by Row tab - Updated Population column for ReportRow 23 to remove pop IDs 21 and 22
3. Specs* - Corrected '**SystemPath** = <> -1' to '**SystemPath** <> -1' in the tlsa_Exit Values column for ReportRow 36
4. Dictionary - LSACalcValues by Row tab - Corrected Universe to 3 for temporary destinations (ReportRows 101-116)
5. Dictionary - LSACalcValues by Row tab - Corrected Universe to 4 for unknown/other destinations (ReportRows 134-136)
6. Dictionary - LSACalcValues by Row tab - Added PopID 48 to Population column for ReportRows 53 and 54
7. Dictionary - LSACalcValues by Row tab - Added PopID 97 to Population column for ReportRow 55
8. Dictionary - LSACalcValues by Row tab - Corrected Cohort for ReportRows 901-920 to 1

COMMITS FORTHCOMING.

*Regarding issue 3:  The criteria for including households in the average for ReportRow 36 (Days to Exit After Any System Path) is a tlsa_Exit.**SystemPath** value that DOES NOT EQUAL -1.   The lsa_Calculated.**SystemPath** value for ReportRow 36, however, is -1.
