### ISSUE TITLE
ref_PopHHTypes: missing HHType records for PopID = [1334, 1336, 1534, 1535, 1536]

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1105]
Hi @MollyMcEvilley ,

Spec has next values for HHType column for PopID = 13, 15, 34, 35, 36:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/6b5971e3-c255-44b7-b69f-ae220cdd4bac)

There are missing records in ref_PopHHTypes table for:
- PopID = 1334 and HHType = [0, 2, 99]
- PopID = 1336 and HHType = [0, 1, 99]
- PopID = 1534 and HHType = [0, 2, 3, 99]
- PopID = 1535 and HHType = [0, 1, 2, 99]
- PopID = 1536 and HHType = [0, 1, 3, 99]

Could you please take a look and add them?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Issue in 01 Temp Reporting and Reference Tables.sql -- commit forthcoming.
