### ISSUE TITLE
LSAPerson Column Names "RRHSONoMoveIn" and "RRHSOWithMoveIn" need to be updated for consistency 

### ISSUE THREAD

**Issue by JulesABrown** [MollyMcEvilley/LSASampleCode#1106]
Other columns using list 6 are labeled "HHType..." followed by the project type. Update these column labels to be consistent with that convention for import purposes: "HHTypeRRHSONoMI" and "HHTypeRRHSOMI"

**Comment by MollyMcEvilley** [comment]
Updated with commit forthcoming:
- Specs
- Dictionary
- 01 Temp Reporting and Reference Tables.sql
- 02 LSA Output Tables.sql
- 05_12 to 05_15 LSAPerson Project Group and Population Household Types.sql
