### ISSUE TITLE
ref_RowPopulations: PopID = [1015, 1115, 1215, 1315, 1415] are missing for ReportRow = 23

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1107]
Hi @MollyMcEvilley,

According to the Spec, PopID = [1015, 1115, 1215, 1315, 1415] should be available for ReportRow = 23:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/f9988bcb-1695-4779-8ca1-6d5cc5f4f929)

But there are no correspondent records in ref_RowPopulations. Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Closed by [this commit](https://github.com/HMIS/LSASampleCode/commit/7c5557414f68e4eb3ddcd3c6362c6eba56d6303d).
