### ISSUE TITLE
ref_RowValues: RowID = 101-116 has issue with [Universe]

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1108]
Hi @MollyMcEvilley ,

According to the Spec, for [RowID] = 101-116 we should use [Universe] = 3: 
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/316ca5e9-b765-4d8f-aae5-a521bf12fa9b)

Now it in [Universe] = 2 for [RowID] = 101-116 in ref_RowValues table:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/d8dcc7c0-7f5c-43f6-b443-15445ad29f4c)

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Closed by [this commit](https://github.com/HMIS/LSASampleCode/commit/7c5557414f68e4eb3ddcd3c6362c6eba56d6303d) with updates to the insert to ref_RowValues.
