### ISSUE TITLE
ref_RowPopulations: extra PopID = [5097, 5197, 5297] for ReportRow = 55

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1111]
Hi @MollyMcEvilley ,

Spec (section 8.4) does not have a subpopulation = 97. Could you please remove PopID = [5097, 5197, 5297] for ReportRow = 55?

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/eafb514b-8f0b-416f-aeb2-5392911a1719)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
The discrepancy is a specs issue and not a code issue -- thank you for pointing it out!  Commit forthcoming.

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

Could you please update LSA Data Dictionary FY2023 Population list as well because PopID = [5097, 5197, 5297] are missing now?

Thank you!
