### ISSUE TITLE
lsa_HMISParticipation - question about date restriction

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1112]
Hi @MollyMcEvilley ,

Now all non-deleted records from hmis_HMISParticipation table are selected, without any availability dates restriction. But i.e. for hmis_Funder we have date restrictions:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/0427898a-99c9-40f7-8144-4d1aff31c1d4)

Just wonder if we need any for hmis_HMISParticipation.

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
No need for date restrictions!
