### ISSUE TITLE
Follow-up for #1043: Step 3.3.2: exit destination codes discrepancy between Sample Code, Spec, Data Dictionary

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1114]
Hi @MollyMcEvilley ,

It looks like both Spec and Data Dictionary do not have fixes for point 5 from #1043:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/d8a00ae7-ed42-4461-9f0c-87de3638d673)
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/7c00e144-4557-4ad0-ad08-48980e896b75)

Could you please double-check?

Thank you!
Natalie

**Comment by nataliesus** [comment]
Also, could you please check `hx.ExitDate in (17,30,99)` condition in the Sample Code? Shouldn't it be `( hx.Destination is null or hx.Destination in (17,30,99))`?

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/7c4f3bbf-8d8c-447a-9396-1885fd7f1dcc)

**Comment by MollyMcEvilley** [comment]
The first issue is a feature, not a bug.  The data standards update added a general _Rental by client with some kind of subsidy_ category (435) to the _Destination_ field and moved the specific subsidy types to a separate dependent field.  We don't need to see the 435 in the LSA to know that's what was selected if the value in the **xDestination** column is one of the subsidy types.  

Fixing the second issue now -- thanks!!

![image](https://github.com/HMIS/LSASampleCode/assets/6156815/1e480ae0-06fc-4706-862b-a78f157c9f70)
