### ISSUE TITLE
Records in ref_RowValues and ref_RowPopulations tables for RowID = 901-920

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1116]
Hi @MollyMcEvilley ,

I know I previously asked you to add rows for RowID = 901-920 in ref_RowValues and ref_RowPopulations tables under #1088 and you did.

But after you replied under #1087 that `ReportRows 901-920 are in Section 10 -- they aren't listed in section 8.2 because they are DQ counts and not averages` I now wonder if we do need these rows in ref_RowValues and ref_RowPopulations tables or they can be removed? Because they are not used in the code (section 10 has hardcoded values not taken from either ref_RowValues or ref_RowPopulations tables).

What do you think?

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
I think they're fine to stay there!  They're not hurting anything or taking up very much space.  :)
