### ISSUE TITLE
Follow-up for #1062: NotOneHoH question

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1121]
Hi @MollyMcEvilley ,

This is a follow-up ticket for #1062.

In the Spec it is said, that NotOneHoH should count Households if `There are no EnrollmentIDs for the HouseholdID where RelationshipToHoH = 1`:

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/2d958a15-3a94-4b40-9640-2cca213a761d)

Sample Code has `n.EnrollmentCoC = rpt.ReportCoC` condition, and, assuming that EnrollmentCoC should be entered for HoH, it is not possible to select Households without HoH.

I believe `n.EnrollmentCoC = rpt.ReportCoC` condition should be applied if there are more than 1 HoHs in the Household and at least one of them has `n.EnrollmentCoC = rpt.ReportCoC`.

Could you please take a look? 

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
This is a very good point.  I am going to update both the specs and the sample code to count HouseholdIDs where any associated enrollment has _EnrollmentCoC_ = **ReportCoC**.

![image](https://github.com/HMIS/LSASampleCode/assets/6156815/43fdc4dc-4d7c-44cf-9a4c-98c50ed98fc1)

![image](https://github.com/HMIS/LSASampleCode/assets/6156815/317550da-c4f4-4386-bcbc-2a70a16d1333)
