### ISSUE TITLE
Follow-up for #1095: Report Row = 907 and 908: new discrepancy between Sample Code and Spec

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1123]
Hi @MollyMcEvilley,

Now Spec has `ExitDate >= EntryDate` condition, but Sample Code uses `ExitDate > EntryDate` condition:

- Spec:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/8589bc42-c87a-4df8-a490-70e6b77e488e)

- Sample Code:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/dce94574-bb32-4704-a907-9cdbd0a73607)

Could you please update the formula in the Spec?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
The sample code is correct in this case -- updating the specs.
