### ISSUE TITLE
Sample Code: ReportRow in (901,902) - issue with Project Type

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1124]
Hi @MollyMcEvilley ,

**1.** Could you please take a look if ProjectType = 0 should be added?
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/05467dce-fe6a-4016-a60f-37d309963f88)

**2.** I wonder if RRHSO was not added in the Spec intentionally. Because for ReportRow = 905 it was added. If we do need to exclude RRHSO, then we should add a correspondent condition in the Sample Code.
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/98d7e286-b45f-48ba-9a0f-373a483b510d)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
I am deleting the ProjectType criteria altogether as we are counting enrollments in tlsa_Enrollment, which is already limited by project type.
