### ISSUE TITLE
Affiliation.csv: ProjectType = 6 is missing (both Sample Code and Spec)

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1127]
Hi @MollyMcEvilley ,

HMIS CSV Export spec limit Affiliation.csv to  ProjectType = 6 and (ProjectType = 13 subtype 1):
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/3f5779d8-d9d7-4323-bacf-0cd680613b8e)

LSA Affiliation.csv uses only ProjectType = 13 subtype 1. What is about ProjectType = 6? Was it excluded intentionally?

Sample Code:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/8119c4b8-e552-4908-9ecb-d914cf134391)

Spec:
- Section 2.7
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/052482b5-7cff-4409-bb90-a9d5dfd5a7c7)

- Section 4.7
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/10a98fb1-4e9b-423d-aae1-7601c5752538)
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/3c21cb06-7062-4f23-b21a-453997ebd91f)

Could you please take a look?

Thank you!
Natalie

**Comment by nataliesus** [comment]
In addition. Spec Section 4.7 has restrictions by ProjectType for ResProjectID:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/4e909223-7939-44e2-931d-49d501d4bae3)

1. There are no such restrictions in Sample Code. Do we need them?
2. ProjectType = 9 is missing (it was in the CSV Export for prev FY, now we have
https://www.hudexchange.info/program-support/my-question/?askaquestionaction=public%3Amain.answer&key=D4811CDC-B0EF-4502-BE967BC5E01AD5A8 ticket open)

Could you please take a look? Thank you!

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

Now we have `Project.OperatingEndDate is null or OperatingEndDate >= ReportStart` restriction for [ProjectID]. I wonder if we need such a restriction for Projects selected for [ResProjectID]?

Also, according to LSA Spec, `ResProjectID Must match a ProjectID in Project.csv where: ProjectType <> 13; or RRHSubType = 2`. What if there are records with ResProjectID not in Project.csv? Maybe we need an additional `inner join lsa_Project lp1 on lp1.ProjectID = a.ResProjectID`, what do you think?

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
I would rather see that there are issues -- e.g. a missing residential project in Project.csv -- and I think the join would obscure that.  Does that make sense?

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley,

> I would rather see that there are issues -- e.g. a missing residential project in Project.csv -- and I think the join would obscure that. Does that make sense?

Hmm, it makes sense for Systemwide LSA.

I just thinking that the report can be used as Project-Focused LSA, and it can be a "false" issue if ResProjectID is not in the Projects list. Maybe in this case validation that ResProjectID is in Project.csv should be applied only for Project-Focused LSA? What do you think?

Thank you!
Natalie
