### ISSUE TITLE
SSNValid possible issue (both Spec and Sample Code)

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1128]
Hi @MollyMcEvilley ,

Here are LSA SSNValid programming instructions:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/29d95c20-5859-4c01-a4f8-e0fb7724474b)

I've just started working on HMIS DQ report, and I think we overlooked for LSA ( both Spec and Sample Code ) one important update made in Glossary for FY 2024 that if SSN Quality is "partial", then SSN can contain only 4 last digits and it is a valid scenario:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/d7f5716b-88a5-44c8-9728-f129f54d1b42)

What do you think? Should SSNValid in LSA be updated?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
The LSA is doing this differently because the counts here are principally related to the possibility of duplicate clients.  (Four digits is consistent with the data standards but isn't a valid SSN.)
