### ISSUE TITLE
DisablityStatus Description in Dictionary is incomplete

### ISSUE THREAD

**Issue by JulesABrown** [MollyMcEvilley/LSASampleCode#1129]
Cell H104 - Description of DisabilityStatus Column - is incomplete. It ends with "(Note that"

List 19 - Gender should be highlighted in yellow, too.

**Comment by MollyMcEvilley** [comment]
I have no idea what I thought people should take special note of re: DisabilityStatus, so I just deleted "(Note that".

Highlighted Gender list items.
