### ISSUE TITLE
Follow-up for #1059: Spec: DisabilityStatus recent changes

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1135]
Hi @MollyMcEvilley ,

**1.** Could you please confirm there is no typo in this text in Spec Section 7.4 (both docx documents)? Also, I cannot see logic to set DisabilityStatus = 99:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/4261a53d-a88c-4bb3-a17b-acedaba2026d)

Because the Sample Code was updated using DisabilityStatus = 99 if DisabilityStatus is not either 0 or 1. 

**2.** Just in case, I am not sure the Sample Code use the right logic here:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/2e033972-95d5-4d3a-a164-9cc040950bfe)

Maybe it should be something like `IFNULL( MAX( IF( n.DisabilityStatus IN (0,1), n.DisabilityStatus, NULL )), 99 )`

**3.** Just in case, maybe for #1059 "Spec" tag is also needed?

**4.** Is it OK that DisabilityStatus was added to the group condition in Sample Code Step 7.4.1?

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/d90d2e65-2891-4cce-abcc-7c81ecced2aa)

Because I cannot find in Spec Section 7.4 that DisabilityStatus impacts on selection into tlsa_ExitHoHAdult table:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/1ae5e279-e63b-43aa-a1d8-7a29716e9bb0)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
See notes in #1153 re: corrections. Thank you!
