### ISSUE TITLE
[SSNValid] - both Sample Code and Spec needs an update

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1137]
Hi @MollyMcEvilley ,

Previously under #1065 I overlooked to add SSN conditions as reverse sequential numbers for all 9 digits (In Glossary we see “987654321” as an example). 

- 098765432
- 109876543
- 210987654
- 321098765
- 432109876
- 543210987
- 654321098
- 765432109
- 876543210
- plus 012345678 which is a sequential list and which was missing in #1065

Could you please take a look and update both Spec and Sample Code?

Thank you!
Natalie

**Comment by nataliesus** [comment]
or maybe we should not use 0 and the list should be:

- 876543219
- 765432198
- 654321987
- 543219876
- 432198765
- 321987654
- 219876543
- 198765432

What do you think?

**Comment by MollyMcEvilley** [comment]
This is a fine suggestion, but it's a change that we are not going to make at this time.
