### ISSUE TITLE
Spec Section 3.4: minor update for column header for DomesticViolenceSurvivor

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1141]
Hi @MollyMcEvilley ,

Just in case, "Survivor" is italicised in "DomesticViolenceSurvivor" column name:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/df3e7426-7948-4b4c-827b-2520d5ee3088)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Thank you!  I corrected it and it will go out the next time I do a commit for the specs, but I accepted the change and did not note it in the RevisionHistory because I don't think anyone but you and I care about it :).
