### ISSUE TITLE
Spec Section 3.4: no logic for new [HIV], [SMI], and [SUD] columns

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1142]
Hi @MollyMcEvilley ,

New [HIV], [SMI], and [SUD] columns have been added to tlsa_Enrollment table structure and steps 3.4.5, 3.4.6, and 3.4.7 in Sample Code recently.

But the is no logic for them in Spec (section 3.4). Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
I added this to the sample code:

![image](https://github.com/HMIS/LSASampleCode/assets/6156815/55c9cdda-0d5d-4aaa-921f-0f9057d0aee2)
