### ISSUE TITLE
Sample Code Step 4.5: issue with [Availability] and [ESBedType]

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1146]
Hi @MollyMcEvilley ,

I the spec (both LSA and CSV Export) [Availability] and [ESBedType] columns are mandatory for ProjectType = (0, 1):
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/6e628847-1632-4236-97b0-44a2a225163d)

In the Sample Code [Availability] and [ESBedType] columns are selected for ProjectType = 1 only:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/7cd62e27-d276-41c3-b9f9-9d13b088034f)

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Can I just take this opportunity to say that you're amazing?  Thank you.
