### ISSUE TITLE
Sample Code: SUD issue

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1151]
Hi @MollyMcEvilley ,

Could you please take a look if DisabilityResponse = 1 should be replaced with DisabilityResponse in (1,2,3) for SUD?

The most recent code uses DisabilityResponse = 1:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/4c497199-2737-453e-b29f-f05d3a3f87e4)

Previously DisabilityResponse in (1,2,3) condition was used:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/3aa3fa75-8046-4818-bc5e-1ae28152cfe2)

Thank you!
Natalie

P.S. Perhaps, sample report output needs to be regenerated.

**Comment by MollyMcEvilley** [comment]
I will update the sample output later this afternoon....
