### ISSUE TITLE
Spec and Sample Code: Section 7.4 DisabilityStatus logic for LSAExit

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1153]
Hi @MollyMcEvilley ,

I have a few questions about recent updated related to 7.4 section.

Spec:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/976a202c-c8b1-4bab-ac8b-a44bca9f8364)

Sample Code:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/0e7c3e92-ae35-46c8-8ae5-a1f6db8a5ddf)

My concerns:
1. Spec: "Set to 99 if..." does not take into account that DisabilityStatus could be set to 1 because of prev condition;
2. Sample Code:
- we use GROUP BY, so we need to rewrite the CASE condition to work for "if the value is X for **any** EnrollmentID";
- maybe the CASE should be rewritten to follow the Spec so if there are 2 enrollments with 0, and NULL values correspondently, then, according to Spec, DisabilityStatus should be 99. But in Sample Code DisabilityStatus result is 0.

Could you please take a look?

Thank you!
Natalie

P.S. Just in case status for https://github.com/HMIS/LSASampleCode/issues/1135 should be changed.

**Comment by MollyMcEvilley** [comment]
I re-ordered the criteria in the specs and re-worked the sample code accordingly.  I don't think I accounted for the possibility that there might be more than one EnrollmentID per PersonalID for a given HouseholdID.

![image](https://github.com/HMIS/LSASampleCode/assets/6156815/e626542b-26c1-49c7-a300-ca3fab7b6be5)
