### ISSUE TITLE
Sample Code: question about ESTLivingSit

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1160]
Hi @MollyMcEvilley ,

Could you please help me to find where the selected instructions from the Spec are programmed in the Sample Code?
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/8d66e206-0e83-4c8a-9517-b2ae43f153d0)

ESTLivingSit is defined in step 6.6.1 in Sample Code:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/50605a1f-c5b8-4510-81b5-624401190c97)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
It is in the code above:  "when hn.EntryDate <> n.EntryDate...  then 99."

The EntryDate in tlsa_HHID will not match the EntryDate in hmis_Enrollment when there is no bednight on the HMIS EntryDate -- that is set in step 3.3.1:

![image](https://github.com/HMIS/LSASampleCode/assets/6156815/3fee4464-0d58-422a-a59a-4f7ef4cb390f)
