### ISSUE TITLE
Upload was rejected because of ID 1300

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1165]
Hi @MollyMcEvilley ,

Test upload was rejected with next errors:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/6edefbbf-45f5-4948-8ed2-6a52ace63248)

Test data:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/0e365105-afb4-4ae7-b496-2d6efdf3c4b3)

Please notice both tlsa_HHID (hhid) and tlsa_Enrollment (n) have:
- Active = 1
- AHAR = 0 (because there is no hhid.MoveInDate for LSAProjectType = 13)

Programmed logic:
1. household is included in lsa_Calculated as ReportRow = 4 because RRHPSHPreMoveInDays > 0
2. to be included in lsa_Calculated for ReportRow = [53, 54, 55],  n.AHAR = 1 condition must be true. But our single enrollment in the household has n.AHAR = 0, and, as a result, cannot be reported for ReportRow = [53, 54, 55].

Could you please take a look? Is it an issue in the upload validation rules? Please notice this issue is not reported in flags, instead, it stoppes the upload process with "failed" resolution.

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Notes:

4 --> 53
4 --> 54
4 --> 55
4 is avg days homeless before move-in to RRH/PSH regardless of whether or not they moved in
53, 54, and 55 are counts of people in residence.

It is possible to have row 4 without 53, 54, and 55.

**Comment by MollyMcEvilley** [comment]
Ref #1171

**Comment by JulesABrown** [comment]
We agree and have put in a ticket to fix the issue. We will notify you when the fix is made.

**Comment by JulesABrown** [comment]
Updated on sandbox - please check.
