### ISSUE TITLE
Flag 684 has hhchar = 0

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1167]
Hi @JulesABrown ,

Could you please advise how "hhchar = 0" condition is applied for Flag 684 and if it is anything that should be used for validation rules?

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/4592b460-e54b-4968-aedb-b86184b46c4d)

Thank you!
Natalie

**Comment by JulesABrown** [comment]
I reviewed with the flag team and this value doesn't play a role in this flag. It will be removed from display in this flag in our next update.
