### ISSUE TITLE
Flag 684-2xx with "multiple genders selected" description

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1168]
Hi @JulesABrown ,

### Upload URL
https://hdxsandbox.abtsites.com/dataset/296/warning

### Flag 684
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/f5f07777-352d-4efc-ae8b-f877398c7137)

### Issue

According to the Spec (section 10.4) `Population=85 and ReportRow=55` is for multigender (`Gender >= 10 and not in (98,99)`):
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/21433649-060f-491d-a52c-fb414243db76)

Using the formula from [Python logic for the LSAPerson version], the record in lsa_Person table has Gender = 99 (Data Not Collected).

There is an issue in Python logic for the LSAPerson version - `Gender > 9` should be replaced with `Gender >= 10 and not in (98,99)'.

Could you please take a look?

Thank you!
Natalie

**Comment by JulesABrown** [comment]
We agree and have put in a ticket to fix the issue. We will notify you when the fix is made.

**Comment by JulesABrown** [comment]
Fix has been pushed to Sandbox - please check.

**Comment by nataliesus** [comment]
Hi @JulesABrown ,

New upload: https://hdxsandbox.abtsites.com/dataset/331/flag-report

The flag is still reported: 
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/edd99a64-eead-4a12-81c7-1c659e55f248)

Best regards,
Natalie

**Comment by JulesABrown** [comment]
Confirmed resolved
