### ISSUE TITLE
LSA upload rejected (8.8/10 & 8.11)

### ISSUE THREAD

**Issue by jbloescw** [MollyMcEvilley/LSASampleCode#1171]
I'm getting a rejected error and I feel that it boils down to how 8.8/10 and 8.11 are set.
![image](https://github.com/HMIS/LSASampleCode/assets/44415627/91bb51f2-5b88-4439-8224-9894a2fc4a31)

There is one client who in section 8.8/10 ends up getting dropped by the final where statement:  AND (rv.RowID <> 36 OR ex.SystemPath <> -1)

The record has report row 36 and a system path of -1 which is what excludes them from populating a Report Row 36.

Now, in section 8.11, the client meets all of the join and where clause criteria.  This is where they get picked up and set a ReportRow of 102.  Here's how the data looks:
![image](https://github.com/HMIS/LSASampleCode/assets/44415627/5f8712df-3a98-4406-9c7e-9c9db1fc1b62)

So there are a couple of questions here.
1. Should this client have other report row 36s showing that I'm not noticing?
2. If not the above, why is 8.11 letting someone in when the previous step excluded them?

I think I have exhausted my knowledge here of looking for a data anomaly and need your input to see what might be going on.
I'm not sure if the other errors with RowID 23 are related to this one or not, but this ticket is focused on the first error in the screenshot.

**Comment by MollyMcEvilley** [comment]
Notes:

102 Avg days to return after exit to street (this is all households who return after exit, regardless of system path)
23 Avg days to return after exit (all households regardless of system path)
36 Avg days to return after any system path (this excludes households with a system path of -1 – it is row 23 without those households)
24-35 Avg days to return after specific system paths (that are not -1)

It is possible to have row 102 without row 36; 
It is possible to have row 23 without row 36; and
It is possible to have row 23 without rows 24-35.

**Comment by MollyMcEvilley** [comment]
Ref #1165

**Comment by JulesABrown** [comment]
We agree and have put in a ticket to fix the issue. We will notify you when the fix is made.

**Comment by JulesABrown** [comment]
Updated on sandbox - please check.

**Comment by JulesABrown** [comment]
confirmed resolved
