### ISSUE TITLE
LSA Step 4.4 - issue inserting Null Geocode

### ISSUE THREAD

**Issue by TanyaPieterse** [MollyMcEvilley/LSASampleCode#1172]
Hi,
Just a quick bug, in Steps 4.4 the insert into lsa_ProjectCoC fails and does not allow Null for a Geocode, how should we handle projects where the CoC neglected to enter the CoC Information with the Geocode, should these Projects be excluded from the LSA?
Thanks,
Tanya

**Comment by MollyMcEvilley** [comment]
I think that the report should fail to run under these circumstances rather than gracefully excluding the project(s) or allowing NULLs (it wouldn't be uploadable anyway).
