### ISSUE TITLE
HDX Upload: "There is an issue with the data quality checks on your dataset" message

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1173]
Hi @JulesABrown ,

Upload: https://hdxsandbox.abtsites.com/dataset/300/warning

Upload was successful, but when I opened the Flags Report tab I got next message: "There is an issue with the data quality checks on your dataset. Please report this issue to your data liaison as soon as possible." although 13 flags were generated.

Could you please take a look?

Thank you!
Natalie

**Comment by JulesABrown** [comment]
This has been resolved
