### ISSUE TITLE
Flag 1338-1.xx - Broken symbol

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1174]
Hi @JulesABrown ,

Upload: https://hdxsandbox.abtsites.com/dataset/300/warning

Nothing critical, but just in case it is something that will be fixed:

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/7403b437-0ada-4bb1-b70a-a9af948026ea)

Thank you!
Natalie

**Comment by JulesABrown** [comment]
We have put in a ticket and this will be resolved in a future update. No impact on workflow; closing without further notification.
