### ISSUE TITLE
Flag popup content width

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1175]
Hi @JulesABrown ,

The half (50%) of the popup is empty. I just wonder if the popup content can use 80% or even 100% of the popup width to display the flag description. Now there is a scroll if the description or formulas are quite long:

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/e735ba75-b94a-4458-b662-f4df9f181e2e)

Best regards,
Natalie

**Comment by JulesABrown** [comment]
The "warnings" flags use the other half of the window for the comments thread. Maybe we could make that edit at some point for the errors.
