### ISSUE TITLE
Errors in test kit results

### ISSUE THREAD

**Issue by evaripatis** [MollyMcEvilley/LSASampleCode#1176]
Looking at the results for lsaFunder and lsaHMISParticipation, there seem to be a few issues.  Both of these files contain records associated with inactive projects.  Specifically, FunderID 1028 and HMISParticipationIDs 95, 100, 111, and 117.  All of these are associated with projects whose OperatingEndDate occurs prior to the Report Start Date and, therefore, should not be included in the results.  This incorrect record in lsaFunder shouldn't have any negative downstream impacts, but the ones in lsaHMISParticipation could, as that file is used in Step 10.5.  As I have only started to dig into the results and any discrepancies between our files and the sample ones, I cannot yet say whether or not these are other issues like this.

**Comment by MollyMcEvilley** [comment]
Thank you!

The only date filter on the lsa_Funder results is the _EndDate_ in the Funder record itself.  If there is an _OperatingEndDate_ for the project, there should be a corresponding _EndDate_ entered into HMIS for the funding source(s) -- but if there isn't, the Funder records will be included for any project in lsa_Project.  The note in the specs re: the _OperatingEndDate_ for Funder records is related to validation at the time of upload (i.e., the minimum requirements) and not to programming.

![image](https://github.com/HMIS/LSASampleCode/assets/6156815/3ce328d2-6904-4d2e-a034-1a03560d2f16)

On the other hand, the specs DO limit the HMISParticipation records to projects active in the report period, and I am making that correction in section 4.6 of the sample code.
