### ISSUE TITLE
LSA-Common-Flags-Library: missing flags

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1177]
Hi @MollyMcEvilley , @JulesABrown ,

Recently LSA-Common-Flags-Library.xlsx has been shared. 

It looks like it doesn’t include all flags, because i.e. for flag 684 there are 2 tickets:
- #1168
- #1170

but Flag 684 is missing in the LSA-Common-Flags-Library.xlsx file:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/fb95a669-1363-43d9-bbc1-c9019a08ed11)

Could you please take a look?

Thank you!
Natalie

**Comment by JulesABrown** [comment]
The intent of the common flags library is to post information about the common flags, not all the flags. It is not intended to be comprehensive. We will post the full list of flag text to the github shortly.
