### ISSUE TITLE
Follow-up for #1153: how PersonalID impacts on DisabilityStatus ( Step = 7.4.2, 7.4.3)

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1179]
Hi @MollyMcEvilley ,

Here is the most recent Sample Code and Spec:

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/ca4a478a-9d1c-4329-89f0-b5b38d5c6bbe)

I have a few questions:
- Spec: how to interpret "the selection criteria"? What exactly criteria should be used?
- Sample Code: there is `n.PersonalID = hoha.PersonalID` condition, but it is not listed in the Spec. Spec uses "any EnrollmentID associated with the QualifyingExitHHID" so it doesn't look like a restriction by PersonalID.

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
The "n.HouseholdID = hoha.QualifyingExitID" ensures that the enrollment is associated with the qualifying exit.  Using the PersonalID ensures that the enrollment is associated with the person in tlsa_ExitHoHAdult.  (this is essentially what the "selection criteria" bit refers to).
