### ISSUE TITLE
Intermediates for Sample Output

### ISSUE THREAD

**Issue by evaripatis** [MollyMcEvilley/LSASampleCode#1181]
Is there anyway we can get the intermediate files (tlsaPerson, tlsaEnrollment, etc.) that go along with the Sample LSA Output?  We currently use the sample SQL files to do this, but I'm not entirely confident in the accuracy of the sample SQL.  It would be helpful to have those intermediate files included for troubleshooting discrepancies.  For example, in the tlsaPerson file, I've got two individuals with differing CHTimeStatus values, when compared to what the sample SQL puts out.  The individuals are IDs 649822 and 688125.  The sample SQL generates a value of 99 for their CHTimeStatus, while our code is generating a -1.  The only way CHTimeStatus gets a value of 99 is if it gets updated by step 5.10.5, but as far as I have been able to discern, these individuals shouldn't be getting updated by that step.

**Comment by MollyMcEvilley** [comment]
I have added a zip file called Sample LSA Temp Tables -- thanks for the reminder!
