### ISSUE TITLE
Possible Upload Issue for file being rejected (ID 1301)

### ISSUE THREAD

**Issue by TanyaPieterse** [MollyMcEvilley/LSASampleCode#1182]
Hi there,

When I upload one of our LSA Files it is being rejected stating ID 1301: 
![image](https://github.com/HMIS/LSASampleCode/assets/44713006/ee42585b-f43e-4f85-bea1-86d5dedda639)

I believe this is caused by a client that was 20 years old when they entered and exited the Project in an AO Youth Household.  According to the LSA Dictionary:
Population	1190	Age 18-21 in AO Youth Household
Population	11		Youth Household 22-24

Should the HDX not instead be looking to see if there are Population 10 Youth Household 18-21 records in the LSA Calculated file instead of the  Population 11 Youth Household 22-24?

Thanks,
Tanya

**Comment by JulesABrown** [comment]
Yep - I'll put a fix through and notify you when it's pushed.

**Comment by JulesABrown** [comment]
The fix has been pushed to remove 1190 and 1191 from the comparison to Population 11. Please recheck at your convenience.
