### ISSUE TITLE
"Red banner" issue with LSA upload

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1183]
Hi @JulesABrown,

LSA Upload: https://hdxsandbox.abtsites.com/dataset/344/flag-report

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/e8a2169d-0f88-4423-9720-e905f75251da)

Just in case it can be helpful.

Thank you!
Natalie

**Comment by JulesABrown** [comment]
This dataset actually just got hung up in processing and doesn't have any issues. If you reupload, you shouldn't get a red banner anymore.
