### ISSUE TITLE
Sample Data: Missing Values For Some Fields

### ISSUE THREAD

**Issue by evaripatis** [MollyMcEvilley/LSASampleCode#1186]
For the following Sample Data files, there are fields that are missing values when compared to the sample SQL (run against the "DataLab - 2024 Zips 2023-11-09" data set).  In each case, the Sample Data field is empty, while the same field for sample SQL result is populated.

**tlsaHousehold**
- RRHSOStatus
- RRHSOMoveIn

**tlsaPerson**
- RRHSOAgeMin
- RRHSOAgeMax
- HHTypeRRHSONoMI
- HHTypeRRHSOMI
- HHTypeES
- HHTypeSH
- HHTypeTH
- HIV
- SMI
- SUD

**tlsaEnrollment** (the following was only present for one record, EnrollmentID 836523)
- PITJanuary
- PITApril
- PITJuly

**Comment by MollyMcEvilley** [comment]
This was closed with[ this commit](https://github.com/HMIS/LSASampleCode/commit/b372a7136a61eb83eb4ddf5f47a535a159df5557):
