### ISSUE TITLE
Step 10.5: both Sample Code and Spec: there is an issue for n.ExitDate is null (found by Flag 1338)

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1190]
Hi @MollyMcEvilley ,

It looks like we need to update 10.5 for cases when n.ExitDate is null: 
- Sample Code:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/c284826d-c826-48c7-8a37-e54594ed6fbd)
- Spec:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/04ced980-7894-4c55-bd6b-f1ee7c05bc65)

Because of Flag 1338 when lsa_HMISParticipation record is valid, n.ExitDate is null, but program is inserted into lsa_Calculated table for ReportRow = 906 as having "XXX client enrollments that are active during the report period and also overlap with a period of time in which the project was not identified as participating in HMIS" because of `part.HMISParticipationStatusEndDate >= n.ExitDate` condition.

Could you please take a look?

Thank you!
Natalie

**Comment by LaurenBianchi** [comment]
Hello, 
Can we advocate for this to be added to the weebly site? 
Could be related to the current work on this ticket but we are getting reports of customers generating no data errors but having this flag thrown.
Thank you for your time and insight!

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

Could you please update Spec in the current project and also on https://files.hudexchange.info/resources/documents/LSA-Programming-Specifications-2023.pdf to reflect the fix?

Thank you!
Natalie
