### ISSUE TITLE
Flags 701 and 1217: no issue, just numeration question

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1194]
Hi!

Just in case, for this flag variable numeration doesn't look like a sequence. It is 1,2,3,4 and then 14

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/84594a5e-1c37-4d62-bd9f-d2cc09944ced)

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/4191ffc7-b5b7-4ccb-b90d-ded134f43700)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
You are absolutely correct that this is weird.  I reviewed 701 and 1217 with the HDX flag team a few days ago and they confirmed that it is peculiar but there are no missing rows of information in the flag...  They will possibly update the flag code to fix the numeration, but they did not make any commitments.   

Thank you!
