### ISSUE TITLE
Flag 416: question about rrhsostatus variable

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1195]
Hi @JulesABrown ,

Upload: https://hdxsandbox.abtsites.com/dataset/443/flag-report

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/58842499-aad8-43f8-899b-6b72629c7d62)

Could you please advise why rrhsostatus is included in the variables list? It looks like it shouldn't be used for validation?

Thank you!
Natalie

**Comment by JulesABrown** [comment]
Basically because if RRHSOStatus includes a period of activity in the report period, it may be the reason HHFleeingDV appears inconsistent with the other columns.
