### ISSUE TITLE
Invalid Affiliation File Errors?

### ISSUE THREAD

**Issue by evaripatis** [MollyMcEvilley/LSASampleCode#1196]
We've been notified by one of our clients that they received errors for their Affiliation.csv file when submitting their LSA.  Upon reviewing their report files, their Affiliation.csv file **_is empty_**, however, their Project.csv file contains no records where ProjectType is 13, RRHSubType is 1, and ResidentialAffiliation is 1.  Based on the current specifications, I can't see why an empty Affiliation.csv file would generate any errors here.  Is there is an error in the validation process?  Do the specifications need updating?  If neither of those, could you provide clarification on why this error is occurring?
![image](https://github.com/HMIS/LSASampleCode/assets/71396927/89489a09-8705-45b6-976b-aa04b2bd82a9)
![image](https://github.com/HMIS/LSASampleCode/assets/71396927/00645195-e823-4262-9be2-5bc5fda3650d)

**Comment by JulesABrown** [comment]
We've definitely had a bunch of uploads with blank affiliation files accepted already, so there might be something going on in the file itself. We'll look into it. Thanks!

**Comment by JulesABrown** [comment]
@evaripatis it looks like the export is populating that row with something (see the image on the right). The file should be completely empty (like the one on the left) to pass the upload process.
![MicrosoftTeams-image (2)](https://github.com/HMIS/LSASampleCode/assets/44678553/73954228-8404-4a18-8d96-12a2f9e20d31)

**Comment by evaripatis** [comment]
Ok, thank you!  We'll have them manually delete that row until we can push out an update to have it removed.
