### ISSUE TITLE
Flag 1301

### ISSUE THREAD

**Issue by jbloescw** [MollyMcEvilley/LSASampleCode#1200]
Since your LSACalculated file has a row with a value 52 in the Population column, you must also have at least one row where the value of Population is 46.

Customer is getting this error kicked back to them when they upload (MO-604).
When I look at the export for LSA Calculated, I do see both populations here.  Why is this getting rejected?  Is there more information on these types of flags or am I missing something here?

Thanks!

**Comment by JulesABrown** [comment]
The value was supposed to be checking for the relationship between 52 and 35, not 52 and 46. We have corrected the flag and pushed out a fix. If MO-604 reuploads, they should not hit this issue anymore.
