### ISSUE TITLE
Data missing in latest Sample LSA Output

### ISSUE THREAD

**Issue by evaripatis** [MollyMcEvilley/LSASampleCode#1201]
For the updated sample data, posted about a week ago, the Organization file has absolutely nothing in it, while the Funder, ProjectCoC, HMISParticipation, and Inventory files have only headers in them.

**Comment by MollyMcEvilley** [comment]
Something is failing here... this isn't fixed.

**Comment by MollyMcEvilley** [comment]
Okay, it is really and truly fixed by [this commit](https://github.com/HMIS/LSASampleCode/commit/72ae68852c63f20f3ad65360ad0c48a0deb428e6).
