### ISSUE TITLE
Sample data issue: EST/RRH/PSH Geography

### ISSUE THREAD

**Issue by evaripatis** [MollyMcEvilley/LSASampleCode#1203]
In the tlsa_Household file, all of the records have Geography values (EST, RRH, and PSH) of -1 or 99.  This is despite the fact that the ProjectCoC file has GeographyType values of 1, 2, or 3 for every record.  I'm not seeing a reason why the tlsa_Household file should have values of 99, at least not that many.

**Comment by evaripatis** [comment]
@MollyMcEvilley, that last change did improve things for the LSAHousehold file, but the issue persists for the tlsa_Household file.  It looks like the intermediate files were not updated.

**Comment by evaripatis** [comment]
@MollyMcEvilley, can you please re-open this ticket?

**Comment by MollyMcEvilley** [comment]
Reclosing -- this has been addressed in the most recent commit.
