### ISSUE TITLE
Sample HMIS Data.zip: question about CoC

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1215]
Hi @MollyMcEvilley ,

Sample LSA Output.zip is generated for "XX-501" only.

HMIS Data.zip contains data for both "XX-501" and "XX-500".

Just want to confirm that "XX-500" data were intentionally added to HMIS Data.zip and they should not be replaced with "XX-501".

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Hi Natalie,

Yes, I added the data to make sure that the sample code properly excludes data from CoCs other than ReportCoC.
