### ISSUE TITLE
LSA Specifications: RaceEthnicity Table Discrepancy 

### ISSUE THREAD

**Issue by LaurenBianchi** [MollyMcEvilley/LSASampleCode#1217]
Hello,
I reviewed the LSA specifications yesterday and noticed a discrepancy in the LSA Specs vs. the sample code and LSA Data Dictionary. I was hoping to get this table discrepancy resolved in the LSA Specifications.

[On page 55](https://files.hudexchange.info/resources/documents/LSA-Programming-Specifications-2023.pdf#page=61), the RaceEthnicity LSA Values appear to differ from the guidance in the bullet points above the table, LSA Data Dictionary, and the Sample Code.
![Screenshot 2024-04-09 at 10 52 27 AM](https://github.com/HMIS/LSASampleCode/assets/92442726/69353ddc-7e14-4c84-aad5-a5e412cde08c)
It looks like the updates were applied [here](https://github.com/HMIS/LSASampleCode/blob/master/LSA%20Programming%20Specifications%20FY2023%20v1_0.docx), just not in the HUD Exchange version. 
Thank you for your assistance!
LB

**Comment by MollyMcEvilley** [comment]
I am going to close this out because it's not an issue in the documentation posted here... but also going to check on the progress of getting the final version of the FY2023 specs posted to the HUD Exchange.  Thank you!
