### ISSUE TITLE
CSV Export v1.4 - some changes are missing in LSA

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1219]
Hi @MollyMcEvilley , @JulesABrown ,

There are a few changes in https://files.hudexchange.info/resources/documents/HMIS-CSV-Format-Specifications-2024.pdf that are not reflected in LSA. I would like to confirm with you if we should keep these differences.

**1. ProjectCoC.csv -> Geocode column.**
It is now nullable in CSV Export spec, but mandatory for LSA:

CSV Export spec:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/bba8ef0f-d84a-43b1-a355-a83ff7c7f730)

LSA:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/c24d6f27-c08f-4017-b882-d8d2382570ff)
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/158657b9-9654-4ca7-bc80-0460026f73bc)

**2. Inventory.csv -> CoCCode column.**
It is now nullable in CSV Export spec, but mandatory for LSA:

CSV Export spec:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/f4eda194-3c1d-4c98-8e27-460361ab964c)

LSA:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/ed014d5b-abf6-401f-96e6-1e14a6099ca8)
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/8c9549c1-86d5-4189-a285-2077a9d8cf4a)

I believe for LSA Inventory.csv -> CoCCode should be mandatory. Should LSA Spec be updated to not refer to HMIS CSV documentation?

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
These fields may be nullable in the general sense, but the upload will be rejected if they are null because the data are required / mandatory for the LSA and projects included therein.
