### ISSUE TITLE
Please check if X placeholder in SSN described in the Glossary affects SSNValid rule in LSA

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1220]
Hi @MollyMcEvilley , @JulesABrown ,

I have a question about SSN validation rule that checks that SSN contains only digits:

![image](https://github.com/user-attachments/assets/3e2c65d6-b639-4ab2-aef7-ac591d633314)

According to the Glossary, SSN may contain vendor-designated placeholder character(s) (i.e. we will use "x" in our system) that are allowed and their existence does not make SSN invalid:

![image](https://github.com/user-attachments/assets/2d47381d-17fd-4cea-955e-4532a8b01678)

Maybe `c.SSN like '%[^0-9]%'` should be rewritten as `replace( c.SSN, 'x', '' ) like '%[^0-9]%'`.

What do you think?

Best regards,
Natalie

**Comment by nataliesus** [comment]
just in case, the Spec also needs correction:
![image](https://github.com/user-attachments/assets/c8aaa7ae-1e76-408f-9ad9-a703561f0c8a)

**Comment by nataliesus** [comment]
also, "SSN begins with '000', '666', or '9'" instructions should be updated to "the First three digits cannot be “000,” “666,” or in the 900 series” to mimic Glossary, Or maybe it is a Glossary that should be fixed...
![image](https://github.com/user-attachments/assets/525acf33-98f9-4bf1-8228-c00bf830554c)

**Comment by MollyMcEvilley** [comment]
The LSA specs aren't impacted by Glossary changes.  We are going to leave the SSN validation as is for this year.
