### ISSUE TITLE
[SSNValid] - an addition for sequential numbers list

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1222]
Hi @MollyMcEvilley , @JulesABrown ,

The GLossary (https://files.hudexchange.info/resources/documents/HMIS-Standard-Reporting-Terminology-Glossary-2024.pdf) doesn't provide the exact list of SSN sequential numbers.

As the new LSA season is coming, I would like you to revisit https://github.com/HMIS/LSASampleCode/issues/1137 and possibly add all or some sequential numbers from the list including reverse sequential numbers as well:

098765432
109876543
210987654
321098765
432109876
543210987
654321098
765432109
876543210

plus 012345678 which is a sequential list and which is missing now

876543219
765432198
654321987
543219876
432198765
321987654
219876543
198765432

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Hi @nataliesus -- thank you!  We are going to leave the SSN validation as is for this year.
