### ISSUE TITLE
new FY: Sample Code: suggestion for ch_Exclude, ch_Include, ch_Episodes, and sys_TimePadded tables

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1223]
Hi @MollyMcEvilley ,

Now  ch_Exclude, ch_Include, ch_Episodes, and sys_TimePadded tables are filled for Sections 5 and 6, and then in Section 7 these tables are truncated and filled with a new data related to Section 7.

I wonder if Sample Code can be updated for the next FY so these tables are duplicated i.e. with '_s7' suffix so it is possible to use these new tables in Section 7, and the old tables in Sections 5 and 6. Also, it will be reflected in Sample LSA Temp Tables.zip.

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
I used _exit suffixes instead of _s7 because I suppose there's a chance in the future that the section numbering could change, but otherwise, I think this was a really good idea.  Thank you.

**Comment by nataliesus** [comment]
Perfect! Thank you very much!
