### ISSUE TITLE
03_01b LSA Parameters and Metadata for HIC.sql - LookbackDate question

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1226]
Hi @MollyMcEvilley ,

I wonder if the report is run for HIC submission (LSAScope = 3), should we still look backward up to 7 years from the [report start date]? 
![image](https://github.com/user-attachments/assets/69d32d09-08b6-49ba-bdae-f0861e3c2a91)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
There is an open question about the feasibility of using the upload for the Sheltered PIT for CoCs with 100% participation.  It's not going to happen this year, but it's not off the table for the future and the CH counts require the lookback, so we're leaving it there for now.
