### ISSUE TITLE
LSA Data Dictionary FY2024.xlsx -> Lists: yellow empty cells on rows 480 and 481

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1228]
Hi @MollyMcEvilley ,

Could you please take a look if cells A,B,C, and D on rows 480 and 481 should have a yellow background as empty cells in columns E,F, and next.

![image](https://github.com/user-attachments/assets/72d7e40f-a756-4bf2-8259-eb261dce25e7)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
No, that was left over from last year and will be fixed with the next commit... Thank you!
