### ISSUE TITLE
Spec: Section 2.2: reference to CSV Spec

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1230]
Hi @MollyMcEvilley ,

LSA Programming Specifications FY2024 - Annotated.docx refers to the CSV Spec v1**.4**. Following the link we get to the CSV Spec v1**.5**:
![image](https://github.com/user-attachments/assets/b07abc53-a076-4ae0-886a-585d254c584a)

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
I am going to remove the version number altogether since they are using a stable URL with no version number.... Will be updated in the next commit.
