### ISSUE TITLE
Spec: Section 2.3: Project Group

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1233]
Hi @MollyMcEvilley ,

Just wonder if Project Group definition should be updated to include Project Types allowed for the HIC submission that are normally excluded from the LSA submission.

![image](https://github.com/user-attachments/assets/9eb1b087-6bf2-439e-b82e-ae6c52a2e140)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Since this is related to demographics reporting for the active cohort, I don't think it applies to RRH-SO or OPH...  I'm going to go ahead and leave this alone.
