### ISSUE TITLE
Spec: Section 3.2: Cohort logic for HIC

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1234]
Hi @MollyMcEvilley ,

In the Spec it is said: "**Point-in-time cohorts are only included if the relevant date falls between ReportStart and ReportEnd**". Thus, if for the HIC report [ReportStart] is equal to one of the [CohortStart] dates, then the cohort should be reported, correct?

I am asking because in the Sample Code there is no chance that any of Point-in-time cohorts is ever included for HIC (the insert statement works only if LSAScore != 3).

![image](https://github.com/user-attachments/assets/9ba13633-4822-40c3-aa4f-e28fa466b9e7)

What do you think: is it better to update the Spec or the Sample Code so they both match?

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
> Thus, if for the HIC report [ReportStart] is equal to one of the [CohortStart] dates, then the cohort should be reported, correct?

This isn't necessary -- we don't need separate counts for Cohort 11 and Cohort 1 if the HIC date happens to be 1/31.  Clarifying this in Section 3.2
