### ISSUE TITLE
A question about comparing HMISParticipationStatusStartDate/EndDate with other dates

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1236]
Hi @MollyMcEvilley ,

Could you please advise if a date should be counted as "valid" if it is on HMISParticipationStatusStartDate or HMISParticipationStatusEndDate?

I.e. Spec Section 3.3:
![image](https://github.com/user-attachments/assets/376b8146-5edf-4c77-8ebe-4e27c53c9297)

The Sample Code (step 3.3.1):
![image](https://github.com/user-attachments/assets/7f27c5a4-976e-4ddc-989d-163e0d155655)

Why
-  ">=" is used for `svc.DateProvided >= part.HMISParticipationStatusStartDate` but  ">" is used for `hx.ExitDate > hp1.HMISParticipationStatusStartDate`
- "<" is used for `svc.DateProvided < part.HMISParticipationStatusEndDate` but  "<=" is used for `hoh.EntryDate <= hp1.HMISParticipationStatusEndDate`

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
See issue #1272 for details.
