### ISSUE TITLE
LSA Spec Clarification request pg 86-87

### ISSUE THREAD

**Issue by kepaton** [MollyMcEvilley/LSASampleCode#1237]
Page 86-87 (Section 6.6 EST/RRH/PSH LivingSit) There is an empty table here - is this a formatting issue or is this missing information? 

Apologies if this in not the right venue for this question.

**Comment by nataliesus** [comment]
Hi @kepaton ,

Could you please take a look if the empty table was removed for you? I also see it now. But maybe it is something with onedrive.live.com I use to review the spec.

Thank you!
Natalie
