### ISSUE TITLE
Section 3.3: MoveInDate logic in the spec is different from the Sample Code

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1238]
Hi @MollyMcEvilley ,

1. for rule when MoveInDate is compared with HMISParticipationStatusEndDate:
- Spec uses ">" (`MoveInDate > HMISParticipationStatusEndDate`)
- but Sample Code uses ">=" (`hoh.MoveInDate >= part.HMISParticipationStatusEndDate`)

2. Spec has NULL rules for:
- MoveInDate > Exit.ExitDate
- and MoveInDate = Exit.ExitDate and ProjectType = 3
but in the Sample Code there conditions are reversed:
`when p.LSAProjectType = 3 and (hoh.MoveInDate < hx.ExitDate or hx.ExitDate is null)  
	then hoh.MoveInDate
when p.LSAProjectType in (13,15) and (hoh.MoveInDate <= hx.ExitDate or hx.ExitDate is null) 
	then hoh.MoveInDate`
	
not an issue, but do you think it is possible to update the Sample Code to be exactly as Spec?

![image](https://github.com/user-attachments/assets/1c942e54-e7e0-4e49-9859-384941ea16e2)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
1.  I am updating the code so that it is consistent with the specs.
2. I am not going to change the code here as it is consistent with the logic defined by the specs, 
Thank you!
![image](https://github.com/user-attachments/assets/1c3b2c19-04dd-4457-b99b-69821e3cc5ab)
