### ISSUE TITLE
Section 3.3: ExitDate correlation with HMISParticipationStatusEndDate

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1239]
Hi @MollyMcEvilley ,

1. Could you please confirm we should use "<" instead of "<=" in "HMISParticipationStatusEndDate < ReportEnd" conditions:
![image](https://github.com/user-attachments/assets/87fe0d95-cefb-4479-b895-966e385272b5)

I am asking because "<=" is used in the similar "Project.OperatingEndDate <= ReportEnd" conditions.

2. Rows where [Effective Exit Date] = [LastBedNight + 1 day] or [MoveInDate + 1 day] - shouldn't we check that [Effective Exit Date] is not after [HMISParticipationStatusEndDate]?
![image](https://github.com/user-attachments/assets/87ab8577-389e-4ea7-8f9e-6d0da6e4b4f3)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Changes in the sample code have already been posted.  (See issue #1272)

I've re-written and expanded section 3.3 of the specs to include, among other things, this:
![image](https://github.com/user-attachments/assets/650a477d-9c03-430b-b93f-d5af9d62a822)
