### ISSUE TITLE
New Section 9.6: enrollment universe question

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1241]
Hi @MollyMcEvilley ,

**1.** In Section 3.3 it is said that only valid enrollments should be reported. So project stays where:
- either RelationshipToHoH is not valid (null or not between 1 and 5)
- or the Household has more that 1 HoH

must be excluded:

![image](https://github.com/user-attachments/assets/29374447-3318-484c-8997-1564fb79c4ea)

Should the same principle be used to report OPH Point-In-Time Counts for HIC (section 9.6)? I've confirmed with the Spec and with the Sample Code and there are no restrictions by RelationshipToHoH for HH members, and there is no logic to single HoH.

**2.** And, if it is decided to exclude "invalid" enrollments, should the "excluded" OPH enrollments be added to the DQ section so Customers can find and fix issues?
![image](https://github.com/user-attachments/assets/54b66960-d623-4f92-94ef-907ad37e9d86)

![image](https://github.com/user-attachments/assets/3d24119d-206c-4455-9bf3-406a0c68aae8)

**3.** The Sample Code uses `hn.EnrollmentCoC = rpt.ReportCoC` but the restriction is missing in the Spec:

![image](https://github.com/user-attachments/assets/8e23a901-a4ec-4192-8cc8-3cf115dfd3d1)

**4.** I wonder if we need restrictions by Project OperatingStartDate  and OperatingEndDate similar to step 3.3.1?

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
1.  No, the criteria for inclusion in the PIT count is less rigorous than the criteria for inclusion in the LSA as a whole.  We are not reporting on personal or household characteristics that are contingent on relationship.  We are also not counting households -- i.e., the number of unique combinations of HoHID/HHType -- which requires a single head of household.  
2. No need here.
3. Added the EnrollmentCoC = ReportCoC requirement to the specs in this commit:  https://github.com/HMIS/LSASampleCode/commit/2200b45808b49f011211caa104d74139c60d0481.
4. No, these restrictions are not necessary for a one day report.  Truncating the enrollment dates for the LSA is a rough way to address an AHAR issue related to bed nights, inventory, and utilization rates.  For the HIC, the people have to be counted regardless of HMIS participation.
