### ISSUE TITLE
Step 10.5: possible issue with enrollment universe

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1242]
Hi @MollyMcEvilley ,

Could you please take a look at the changes made for Step 10.5? Using hmis_Enrollment and part.ProjectID is null project stays from the whole system and are not limited to the ReportCoC/selected Projects (previously tlsa_Enrollment was used):

![image](https://github.com/user-attachments/assets/e24a6357-8074-4f97-9d35-220d671a4ea8)

![image](https://github.com/user-attachments/assets/0c1fc3d8-8ba9-42d9-b6c6-ba6d1aaadffd)

---

Also, hmis_Exit should be limited to not deleted only.

---

Just in case, lsa_HMISParticipation already contains non-deleted records, so `part.DateDeleted is null` can be removed:
![image](https://github.com/user-attachments/assets/40bff2aa-6356-4080-b517-f0c13bfa7739)
![image](https://github.com/user-attachments/assets/f0a71308-c89c-42b9-b550-8ab5a127b5d6)

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
1.  Since HMIS participation data are collected only for the whole project and not specific to a given CoC, the restriction based on ReportCoC is not necessary.  
2. Updating the code to include DateDeleted criteria for hmis_Exit.
3. Good point!  Removing the DateDeleted criteria for lsa_HMISParticipation.

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

> Since HMIS participation data are collected only for the whole project and not specific to a given CoC, the restriction based on ReportCoC is not necessary.

Sorry for the confusion. Indeed, nothing is clear from what I submitted. I wanted to write about ReportCoC restriction for enrollments, not for the HMIS participation data so I've submitted #1254.
