### ISSUE TITLE
Sample Code (Step 3.3.1): ho.VictimServiceProvider = 0 restriction was removed

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1244]
Hi @MollyMcEvilley ,

I've noticed that ho.VictimServiceProvider = 0 restriction was removed in the Sample Code (Step 3.3.1):

![image](https://github.com/user-attachments/assets/7313d0f4-c0d0-483a-800d-57371c7022d6)

Could you please confirm it was done on purpose? If yes, then the Spec also requires the update as VictimServiceProvider = 0 restriction is listed there:

![image](https://github.com/user-attachments/assets/4193a1a4-18cb-40ad-a65d-7e6fd2e6c4f7)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
No, that was definitely not intentional -- thank you.
