### ISSUE TITLE
Section 3.3: dependances between HMISParticipationStatusEndDate, ExitDate, and OperatingEndDate

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1246]
Hi @MollyMcEvilley ,

**1.** I.e. we have:
- [rpt.ReportEnd] = 9/30/2024
- [part.HMISParticipationStatusEndDate] = 7/2/2024
- [p.OperatingEndDate] = 8/15/2024
- [p.LSAProjectType] = 0
- [hx.ExitDate] = 8/20/2024

Both [p.OperatingEndDate] and [part.HMISParticipationStatusEndDate] are < than [hx.ExitDate].
[part.HMISParticipationStatusEndDate] < [p.OperatingEndDate].

Just want to confirm that:
- the adjusted Exit Date is [p.OperatingEndDate], not the least of [part.HMISParticipationStatusEndDate] and [p.OperatingEndDate],
![image](https://github.com/user-attachments/assets/b309db82-4a1c-4a34-9a04-9c76782eacd2)

**1.**  I.e. we have:
- [rpt.ReportEnd] = 9/30/2024
- [part.HMISParticipationStatusEndDate] = 8/15/2024
- [p.OperatingEndDate] = 7/2/2024
- [p.LSAProjectType] = 3
- [hx.ExitDate] = 8/20/2024
- [hoh.MoveInDate] = 8/20/2024

Both [p.OperatingEndDate] and [part.HMISParticipationStatusEndDate] are < than [hx.ExitDate].
[part.HMISParticipationStatusEndDate] > [p.OperatingEndDate].
[hoh.MoveInDate] = [hx.ExitDate]

Just want to confirm that:
- the adjusted MoveInDate = null (`hoh.MoveInDate > p.OperatingEndDate` is true, and `hoh.MoveInDate >= part.HMISParticipationStatusEndDate` is true)
- the adjusted Exit Date = [part.HMISParticipationStatusEndDate] (previously the adjusted Exit Date was [hx.ExitDate]). But shouldn't it be the least of [part.HMISParticipationStatusEndDate] and [p.OperatingEndDate]?

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
1. The adjusted Exit Date should be the earlier of Operating End Date /  HMIS participation end date -- i.e., 7/2/2024 and not 8/15/2024.  
2. The adjusted MoveInDate should be NULL and the adjusted ExitDate should be 7/2/2024.

The issues that you are highlighting here have been corrected by the most recent commit https://github.com/HMIS/LSASampleCode/commit/616afbf3b33ba377c34e554ffc1a23227ea802ba.
