### ISSUE TITLE
LSA Vendor Call - HMIS Participation Updates: Back to back transactional records with like status 

### ISSUE THREAD

**Issue by LaurenBianchi** [MollyMcEvilley/LSASampleCode#1247]
Hello, 
Adding this 'issue' for tracking/reference. 
We have identified situations where programs will have back-to-back transactional records for HMIS Participation Status that have the _same_ Status response that may unexpectedly truncate enrollments due to the updated logic when only the most recent HMIS Participation Status is referenced for these adjusted dates. 
Example: 
1.  HMIS Participating - 10/01/2022 - 11/01/2023
2. HMIS Participating - 11/02/2023 - 12/31/2023
3. HMIS Participating - 01/01/2024 - null 
Here the program was HMIS Participating since their operating start date, but only enrollments within the third HMIS Participation records would be utilized for enrollment pulls/calculations. 

Thank you for your time! 
LB

**Comment by MollyMcEvilley** [comment]
The data standards just say 'update as needed to reflect changes' and don't specifically prohibit creating new records just for the heck of it even if there is no status change -- and I would even go so far as to say that including requirements to review data annually under the header of 'Collection Point'  in the data dictionary is a little confusing -- but the cost:benefit here is not in favor of having the LSA elide contiguous records with the same status.  

Thank you so much for raising this issue, though -- it helps to be able to anticipate what issues might arise in the HDX.
