### ISSUE TITLE
LSA Data Dictionary FY2024.xlsx -> LSACalc Values by Row: row 55 changes are missing

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1248]
Hi @MollyMcEvilley ,

Row for ReportRow = 55 on "LSACalc Values by Row" sheet is the same as in the prev FY:

![image](https://github.com/user-attachments/assets/8ab98ef4-501e-4395-9bde-cf213f76946a)

This year a new 9.6 step was added to the Sample Code and the Spec, so I wonder if any changes are needed for "AHAR Counts by Project ID" sub-section and ReportRow = 55 (i.e. changes to the "Population" column as logic is not based on the population):

![image](https://github.com/user-attachments/assets/856e254c-d394-49ec-af44-dfaad21198bc)

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Oof.  The issue here is not in the Dictionary, but in the specs and sample code.  Counts of people for the HIC are pulled from report row 53 and not report row 55.  I'm leaving the DIctionary alone and changing the report row in the specs and code.
