### ISSUE TITLE
Spec: Section 3.2: numeration and Logic corrections

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1249]
Hi @MollyMcEvilley ,

**1.** Somewhy going to the 3.2 section from the Context menu I get to the section 4.2:

![image](https://github.com/user-attachments/assets/0f218625-b553-4089-b84d-305ad06c70b8)

If you have the same issue with the numeration, could you please take a look if any other section numbers should be corrected.

**2.** It looks like "Exit cohorts are included only if LSAScope <>." should be corrected as "Exit cohorts are included only if LSAScope <>3." 
![image](https://github.com/user-attachments/assets/7e557890-aeed-40b3-8fde-992b11ab1fe8)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Adding the 3 to the sentence you highlighted! 

I noticed in other screenshots from you that the section numbering in the document that you are using is off.  Any chance you hit return at the beginning of a header line?  The numbering in the document I'm uploading is consistent:

**
![image](https://github.com/user-attachments/assets/9b678f52-da82-4ce3-ae15-fc7f31c1bbbb)
**
