### ISSUE TITLE
HHAdultAge changes (both Sample Code and Spec)

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1250]
Hi @MollyMcEvilley ,

HHAdultAge logic was updated for steps 5.12.1 and 7.9.3.

I just wonder if it is OK that `when max(n.ActiveAge) <= 17 then -1` was removed from step 5.12.1 but was kept in `ages.MaxAge not between 18 and 65` for step 7.9.3.

**step 5.12.1**
![image](https://github.com/user-attachments/assets/ddda7b54-47a9-4b5d-9db2-d4f6669cdb38)

**step 7.9.3:**
![image](https://github.com/user-attachments/assets/7b13e6da-f2ab-4e2d-8ee1-00bd69b24b8a)

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Neither of them are wrong, but it isn't necessary to specify the case where all ages are <= 17 -- removing it in Section 7.9 so that they are consistent.
