### ISSUE TITLE
Readme.md - minor corrections needed

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1252]
Hi @MollyMcEvilley ,

Really a tiny minor correstions:

**1.** Could you please replace 10 with 12:

![image](https://github.com/user-attachments/assets/b7471644-b246-4304-b7f5-ba00f67500a6)

**2.** Could you please remove the release version similar to how it was removed in the Spec?

![image](https://github.com/user-attachments/assets/81d702cf-9f43-463e-8d27-129990999895)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Thank you!
