### ISSUE TITLE
Question about <>[]{} characters

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1253]
Hi @MollyMcEvilley ,

In the CSV Export spec there is a rule to strip out the next characters in the export process: < > [ ] { }

![image](https://github.com/user-attachments/assets/a9059d3d-fbf6-4257-802b-bc25f1ebcc6d)

In the LSA spec there is a rule to strip out the same < > [ ] { } characters from:
- SoftwareVendor
- SoftwareName
- VendorContact
- VendorEmail

![image](https://github.com/user-attachments/assets/4d045fa2-ea38-4121-8de8-b49dc5f6077d)

The Sample Code has these values hardcoded so there are no replace() rules in the code.

I wonder if < > [ ] { } characters should be stripped out from other string (that are manual-entered text) columns in the CSV files that mimic Export CSV files such as:

- Organization.csv:
-- OrganizationName
- Project.csv:
-- ProjectName
- Funder.csv:
-- OtherFunder
- ProjectCoC.csv:
-- Address1
-- Address2
-- City

The LSA Spec has custom rules and not "(See HMIS CSV documentation)" as in other fields so many no changes are needed?
![image](https://github.com/user-attachments/assets/c8260bfc-084e-4728-9a5f-77ce729f3675)
![image](https://github.com/user-attachments/assets/a8816514-45fd-4b39-b96d-62e4b523ee8e)
![image](https://github.com/user-attachments/assets/dd0648cd-4699-4903-be2e-6018db9a9e93)
![image](https://github.com/user-attachments/assets/e9dcc57c-e885-4fa8-a0ff-69310263d70d)

What do you think?

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
I checked and the HDX doesn't have any checks for special characters in these columns, so no need for a change here.  (Yay!)
