### ISSUE TITLE
Section 10.5 (both Sample Code and Spec): ReportRow = 906: review restriction by HMISParticipationStatusEndDate

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1258]
Hi @MollyMcEvilley ,

It looks like the updated restriction by HMISParticipationStatusEndDate should be updated:

![image](https://github.com/user-attachments/assets/1b412af4-2c0a-46e7-8987-646f851bc539)

I am thinking of the case when project stay is active on the ReportEnd ( `x.ExitDate > rpt.ReportEnd` ). I.e.
- ReportEnd = 9/30/2024
- ExitDate = 10/5/2024
- HMISParticipationStatusEndDate = 10/1/2024

Using `part.HMISParticipationStatusEndDate >= coalesce(x.ExitDate, rpt.ReportEnd)` the project stay is rejected because HMISParticipationStatusEndDate < ExitDate but for this case I think it should be accepted.

Maybe we can replace  `part.HMISParticipationStatusEndDate >= coalesce(x.ExitDate, rpt.ReportEnd)`
with `part.HMISParticipationStatusEndDate >= IF( x.ExitDate < rpt.ReportEnd, x.ExitDate, rpt.ReportEnd )`

What do you think?

Best regards!
Natalie

**Comment by MollyMcEvilley** [comment]
Okay, I'm limiting the join to hmis_Exit so we only see ExitDates <= ReportEnd and including HMISEnd* > ReportEnd as a satisfactory condition.

*I hope that's a clear-enough alias -- typing the longer one drives me nuts. 

![image](https://github.com/user-attachments/assets/ff73e8ce-011a-4cca-a567-09b072b9ea9a)
