### ISSUE TITLE
Section 10.5 (both Sample Code and Spec): ReportRow = 906: question about ProjectType = 1 and EnrollmentCoC 

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1259]
Hi Molly,

ReportRow = 906 was reworked using `hmis_Enrollment` instead of `tlsa_Enrollment`.

Using `tlsa_Enrollment`, we automatically used restrictions such as:
1) having at least one bed-night in the `hmis_Services` table for Project Type = 1
2) EnrollmentCoC = Report CoCCode restriction to limit enrolments to an interested CoC and not report enrollments from the selected project by for other CoCCode

I wonder if we should apply them to the new ReportRow = 906 logic (both the Sample Code and the Spec).

EnrollmentCoC restriction question was submitted and will be discussed under #1254.

But what is about the `hmis_Services` table for Project Type = 1?

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
An open enrollment in HMIS during a period when the project isn't participating in HMIS is enough to flag it for data quality -- it isn't necessary that there are bednights.  

(I am adding the EnrollmentCoC restriction, though!)
