### ISSUE TITLE
Sample HMIS Data.zip: "future" DateCreated/DateUpdated

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1268]
Hi @MollyMcEvilley ,

Our import tool does not allow us to import data with "future" DateCreated and DateUpdated dates.

Could you please update **both** DateCreated and DateUpdated for:
- Organization.csv: OrganizationIDs 321 and 987
- Project.csv: ProjectID = [ 4321, 5321, 9875, 9876 ]
- Client.csv: DateCreated for the next clients: 708426, 708435, 708436, 708442, 708444, 708448, 708481, 708507
- Client.csv: DateUpdated for the next clients: 36958, 529531, 566973, 580815, 580816, 644521, 655618, 674679, 702478, 703993, 707210, 708173, 708322, 708396, 708426, 708435, 708436, 708442, 708444, 708448, 708481, 708507

Thank you!
Natalie

**Comment by eanders** [comment]
@nataliesus and @MollyMcEvilley I'd like to chime in here, that it may be useful to have some invalid data in the test kit.  Especially as some of the LSA DQ checks look for invalid data.  I'm not opposed to having a clean dataset, but also having a dataset that includes some issues (which we see daily in data transfers from HMIS) can help catch issues we might see when running the LSA.

If we fix all the data in the sample data set, then we we're missing a huge opportunity to prevent bad data from breaking the SQL or returning unexpected results when it is run against real-world data.

Perhaps an alternate approach would be to have a tool or mapping that can optionally "correct" the issues in the sample data.
