### ISSUE TITLE
A question about ">=" for OperatingEndDate

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1274]
Hi @MollyMcEvilley ,

I've noticed that `hp.OperatingEndDate >= cd.LookbackDate` was replaced with `hp.OperatingEndDate > cd.LookbackDate` in step 3.3.1.

So I wonder if:

1. `hp.OperatingEndDate >= cd.LookbackDate` should be corrected in 04_01 Get Project Records.sql
![image](https://github.com/user-attachments/assets/c6f442ec-b22a-442a-b5cc-7cf3cf9effb6)

2. `lp.OperatingEndDate >= (select ReportStart from lsa_Report)` should be corrected in 04_02 to 04_08 Get Other PDDEs.sql:
- for insert into lsa_HMISParticipation
![image](https://github.com/user-attachments/assets/9c881009-2a6b-4151-9246-c51eaff4691d)
- for insert into lsa_Affiliation
![image](https://github.com/user-attachments/assets/77d9e60d-0ced-4f47-8d93-17c659785b48)

Just noticed the correct restriction was specified in the noted:
![image](https://github.com/user-attachments/assets/ac76cd79-633e-4686-ac38-027e90b0d3ef)

3. in 10 LSACalculated Data Quality.sql:
- step 10.2 - maybe exits on OperatingEndDate also should be reported here? if yes, then changes are needed here

![image](https://github.com/user-attachments/assets/d8d70229-30a1-452c-acda-5bf0f18830ff)
and here:

![image](https://github.com/user-attachments/assets/adc0ec5a-ae4c-4041-95c3-28623d42bc5b)

- step 10.3: perhaps exits on OperatingEndDate should be excluded

 ![image](https://github.com/user-attachments/assets/2fd143b3-c2e0-4b5d-a0fc-efd3055c60eb)

----

If any other above makes sense, please be sure to update the Spec as well.

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Yes -- thank you for the list!

**Comment by MollyMcEvilley** [comment]
Except -- exits on the OperatingEndDate are fine.

The thought process behind this is:  If a project's operating end date is, for example, September 30, then their funding, insurance, ability to pay employees, etc. is all over as of midnight on 9/30.  They can exit people on 9/30, but clients can't go to bed in the project on 9/30 and wake up in an empty building with no utilities and no staff on 10/1.
