### ISSUE TITLE
A question about ">=" for InventoryEndDate

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1275]
Hi @MollyMcEvilley ,

Just want to confirm if a day on InventoryEndDate is a valid date.

In case date on InventoryEndDate should be ignored `insert into lsa_Inventory` should be corrected (spec also should be reviewed).

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Based on this guidance for creating records to reflect changes, yes.  If there are 30 beds available in November and 40 beds available starting on December 1, the record of 30 beds would have an end date of 11/30 and the record of 40 beds would have a start date of 12/1 -- so the 30 beds would be available for clients to sleep in on the night of 11/30.  

![image](https://github.com/user-attachments/assets/3ab911e8-7bbc-40f8-bd2d-3d06116a0394)
