### ISSUE TITLE
Duplicate join condition in Step 3.3.1

### ISSUE THREAD

**Issue by evaripatis** [MollyMcEvilley/LSASampleCode#1277]
As highlighted in the screenshot below, one of the join conditions for subquery bn, in Step 3.3.1, is duplicated.
![image](https://github.com/user-attachments/assets/22b655e1-8897-4000-8cbb-597eaf40af82)

**Comment by MollyMcEvilley** [comment]
But it's really important!  

Just kidding -- thank you! -- updating 3.3.1.
