### ISSUE TITLE
Spec (4.3): Inventory.csv (+Flags.xlsx)

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1279]
Hi @MollyMcEvilley ,

![image](https://github.com/user-attachments/assets/67d501f3-ed2d-4e98-b0cb-ff8e786cb262)

1. For consistency with the rest of the report, I think `Project.OperatingEndDate >= ReportStart` should be replaced with `Project.OperatingEndDate > ReportStart`.

2. About "Validation for Inventory.csv will require..." - these rules are not for insert into the Inventory.csv, correct? Are they for flags? If yes, do we need a separate ticket to review flags logic and fix all places where OperatingEndDate >= ReportStart

![image](https://github.com/user-attachments/assets/c54a11a8-220d-4971-a1e2-941921027d69)
![image](https://github.com/user-attachments/assets/7ed7b1ba-06b3-4ad8-b270-bfe94bd90bc2)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
1.  I updated the specs in section 4.5 (which is the section that applies to Inventory.csv in my version of the document) on 9/25, so this should already be done.
2. Until the HDX is open for testing, there's no need for separate tickets -- they are still making changes to the flag list for this year.
