### ISSUE TITLE
Section 10.2: OperatingEndDate on ReportStart question 

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1281]
Hi @MollyMcEvilley ,

As recently LSA has been updated to exclude OperatingEndDate on ReportStart, I wonder if ReportRow 901 and ReportRow 902 logic should be updated replacing `OperatingEndDate between ReportStart ...` with  `OperatingEndDate between (ReportStart + 1day) ...` :

![image](https://github.com/user-attachments/assets/2bd7d28c-d449-489f-89f8-61e12c4b6977)

If yes, then:
1. changes in the Sample Code are also needed:
- FY2024 changes list (now it is "none")
- and code for ReportRow 901 and ReportRow 902

2. perhaps, LSA and HIC sample outputs and tmp tables should be regenerated.

3. I am not too familiar with the Flags list file, mention it just in case you know if it also requires an update.

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
1.  No, this is okay -- if the OperatingEndDate = ReportStart and there is no exit on or before ReportStart, there should be.
2. I will regenerate all of the Sample Data as soon as I address all of the open issues.
3. The HDX team is finalizing updates to the HDX and will provide an updated flag list as soon as they're done -- it should be available next week.

Thank you!
