### ISSUE TITLE
Sample HMIS Data.zip: Disabilities.csv

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1284]
Hi @MollyMcEvilley ,

The next EnrollmentIDs don't have record(s) in Disabilities.csv file:

- NXS10212178
- NXS10212179
- NXS10212180
- NXS10212181
- NXS10212182
- NXS10212183
- NXS10212184
- NXS10212185
- NXS10212186
- NXS10212187
- NXS10212188
- NXS10220455
- NXS10220456
- NXS10220457
- NXS10220458
- NXS10220459
- NXS10220460
- NXS10220461
- NXS10220462
- NXS10220463
- NXS10220465
- PSH14828649
- RRH14110376
- RRH14110377
- RRH14110378
- RRH14110379
- RRH14110380
- RRH14110381
- RRH14110382
- RRH14110383
- RRH14110384
- RRH14112359
- RRH14112361
- TRN10428650

Could you please take a look if it was done intentionally?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Is it problematic on your end?  They do not exist in my database, so there is no export error.

**Comment by nataliesus** [comment]
If it is OK, then we can resolve this task - I think I will find a way to skip them in your validation system. Thank you for checking!
