### ISSUE TITLE
Sample HMIS Data.zip: HealthAndDV.csv: InformationDate must be the same as Exit.ExitDate 

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1286]
Hi @MollyMcEvilley ,

HealthAndDV.csv has records with Data Collection Stage = 3 (exit) but InformationDate does not equal to the Exit.ExitDate. Could you please take a look?

HealthAndDVID list is:

- HD124012
- HD124013
- HD124026
- HD124028
- HD124029
- HD124030
- HD124031
- HD124032
- HD124044
- HD124045
- HD124046
- HD124050
- HD124051
- HD124056
- HD124062
- HD124063
- HD124064
- HD124071
- HD124072
- HD124073
- HD124079
- HD124080
- HD124081
- HD124082
- HD124083
- HD124086
- HD124092
- HD124093
- HD124101
- HD124106
- HD124108
- HD124109
- HD124110
- HD124114
- HD124119
- HD124120
- HD124123
- HD124125
- HD124126
- HD124127
- HD124128
- HD124129
- HD124130
- HD124134
- HD124140
- HD124141
- HD124143
- HD124144
- HD124145
- HD124146
- HD124147
- HD124148
- HD124154
- HD124155
- HD124156
- HD124157
- HD124164
- HD124165
- HD124168
and others (cannot provide a full list because of a limit of errors in our validation system)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Deleting all HealthAndDV records where DataCollectionStage <> 1 and setting InformationDate = EntryDate for all remaining records in case there are any discrepancies..
