### ISSUE TITLE
Sample HMIS Data.zip: Exit.csv: AftercareDate

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1288]
Hi @MollyMcEvilley ,

Our validation system prevent the file from import reporting "Exit.csv: Non-null value for AftercareDate when it should be empty or empty when it should be non-null" errors for for the following ExitIDs:

- NBN10521056
- NBN10521529

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Setting all AftercareDate values to null.
