### ISSUE TITLE
Sample HMIS Data.zip: Exit.csv: OtherDestination is null for Destination = 17

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1289]
Hi @MollyMcEvilley ,

According to the CSV Spec, OtherDestination is a mandatory string field for Destination = 17.
Exit.csv has OtherDestination = null  for Destination = 17 which cause the import issue. Could you please set OtherDestination = "" (empty string, but with double-quotes this is a mandatory restriction for CSV string fields) for the next ExitIDs:

- NBN10514979
- NBN10515949
- NBN10517648
- NBN10523647
- NBN10524471
- NBN10525137
- NBN10525594
- NBN10525595
- NBN10525596
- NBN10525597
- NBN10525598
- NBN10525978
- NBN10526098
- NBN10526114
- NBN10527843
- NBN10528301
- NXS10618629
- NXS10625380
- NXS10625384
- NXS10823483
- NXS10825479
- NXS10825928
- NXS10826088
- NXS10826223
- NXS10826239
- NXS10826413
- NXS11021319
- NXS11021872
- NXS11024552
- NXS11221190
- NXS11314806
- NXS11314899
- NXS11315131
- NXS11315271
- NXS11316144
- NXS11316938
- NXS11317091
- NXS11317477
- NXS11318067
- NXS11318287
- NXS11318605
- NXS11320363
- NXS11323533
- NXS11324253
- NXS11324301
- NXS12923092
- NXS13517170
- NXS13518866
- NXS13523400
- NXS14716699
- NXS14717015
- NXS14717048
- NXS14717105
- NXS14717498
- NXS14717739
- NXS14718202
- NXS14718296
- NXS14722493
- NXS14723522
- NXS14724140
- NXS14724963
- NXS14725382
- RRH12315680
- RRH12317763
- RRH13118481
- RRH13416084
- RRH15718309
- RRH15817570
- RRH15817685
- RRH15818122
- RRH15818124
- RRH15818514
- RSO15223550

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Setting OtherDestination to 'Other' where Destination = 17 for all records.
