### ISSUE TITLE
Sample HMIS Data.zip: Exit.csv: records for non-existing enrollments

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1291]
Hi @MollyMcEvilley ,

Exit.csv has records with EnrollmentIDs that are not listed in the Enrollment.csv:

-  NXS10212178
-  NXS10212179
-  NXS10212180
-  NXS10212181
-  NXS10212182
-  NXS10212183
-  NXS10212184
-  NXS10212185
-  NXS10212186
-  NXS10212187
-  NXS10212188
-  NXS10220455
-  NXS10220456
-  NXS10220457
-  NXS10220458
-  NXS10220459
-  NXS10220460
-  NXS10220461
-  NXS10220462
-  NXS10220463
-  NXS10220464
-  NXS10220465
-  RRH14110376
-  RRH14110377
-  RRH14110378
-  RRH14110379
-  RRH14110380
-  RRH14110381
-  RRH14110382
-  RRH14110383
-  RRH14110384
-  RRH14112359
-  RRH14112361

Could you please remove these records from the Exit.csv?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
A poorly-thought-out export criteria excluded the enrollments, but there are supposed to be there.  Fixing that.
