### ISSUE TITLE
Sample HMIS Data.zip: duplicate records

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1292]
Hi @MollyMcEvilley ,

I've noticed there are duplicate records in different files. I.e.

YouthEducationStatus.csv has 3 duplicate records with EnrollmentID = NBN10528644 (omitting the fact that there is no enrollment record in the Enrollment.csv) :
![image](https://github.com/user-attachments/assets/90b75eac-1189-4b40-a4db-a435aec7085d)

----

![image](https://github.com/user-attachments/assets/d35cd9f2-0516-4505-a042-add6aa011822)

It looks like data was written in the YouthEducationStatus.csv without removing the prev data from the file.

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Deleting all YouthEducationStatus records from the sample db as they are not relevant.
