### ISSUE TITLE
Sample HMIS Data.zip: YouthEducationStatus.csv: EnrollmentIDs that are missing in the Enrollment.csv

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1293]
Hi @MollyMcEvilley ,

YouthEducationStatus.csv file has EnrollmentIDs that are not listed in the Enrollment.csv:

- NBN10528644
- NXS10212178
- NXS10220455
- NXS11328642
- PSH14828649
- RRH13228643
- RRH14110377
- RRH15828648
- TRN10428650

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Deleting all YouthEducationStatus records from the sample data as they are irrelevant.
