### ISSUE TITLE
Sample HMIS Data.zip: Project.csv: future OperatingStartDate

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1294]
Hi @MollyMcEvilley ,

Next ProjectIDs has future OperatingStartDate:
-  NBN171
- NXS172
- NXS173
- NXS174

Please let me know if it was done intentionally so I do not submit similar questions in the future.

Thank ou!
Natalie

**Comment by MollyMcEvilley** [comment]
Yes, this is intentional!  Projects and inventory under development should be included in the HIC.
