### ISSUE TITLE
Sample HMIS Data.zip: Client.csv: wrong quotes

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1295]
Hi @MollyMcEvilley ,

There is a CSV structure issue for  PersonalID:
- C16803
- C20733

![image](https://github.com/user-attachments/assets/03da86d3-948a-4534-b5c7-3f8960af2533)

You see, there are double-quotes for the NameSuffix, but it fact there should be 3 double-quotes from each side such as:
- """Josiah"""
- """Marty"""

So in the original DB, value is stored as "Marty". CSV spec says to duplicate double-quotes so we get ""Marty"". And also CSV tells us to use doble-quotes for string fields, and, as a result, it must be """Marty"""between commas in the *.csv file.

Here is the reference to the CSV spec:

![image](https://github.com/user-attachments/assets/7b080eb7-2ae6-4846-89c0-27f2bd54abd5)

Could you please fix?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Not sure where the double-quotes came from -- apologies -- but I am deleting all non-NULL values from the NameSuffix column as they are not relevant.
