### ISSUE TITLE
Sample HMIS Data.zip: HealthAndDV.csv: EnrollmentIDs that are missing in the Enrollment.csv

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1296]
Hi @MollyMcEvilley ,

HealthAndDV.csv file has EnrollmentIDs that are not listed in the Enrollment.csv:
PSH14828649
TRN10428650
RRH14110376
RRH14110377
TRN10428650
NXS10212178
RRH14110377
RRH14110377
NXS10212178
PSH14828649
RRH14110377
RRH14110376
RRH14110376
RRH14110377
PSH14828649
PSH14828649
NXS10220455
NXS10220455
PSH14828649
NXS11328642
RRH13228643
NBN10528644
RRH15828648

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Deleted these and stray records in hmis_Disabilities.
