### ISSUE TITLE
LSAExit issue in Step 7.9.2

### ISSUE THREAD

**Issue by TanyaPieterse** [MollyMcEvilley/LSASampleCode#1297]
Hi Molly,

When executing Step 7.9.2 there seems to be an issue that is causing the insert into lsa_Exit to fail because HHVet has a null value.

Here is what is happening...

![image](https://github.com/user-attachments/assets/d92483c6-23d3-46d6-9421-8d098190131a)

Should we add some kind of cleanup script for these null values, or should we adjust the ExitDate in Step 3.3.1?

Thanks,

**Comment by MollyMcEvilley** [comment]
Making updates to 3.3.1, which I will commit in a few minutes.  

To test, I used EnrollmentID HAV13728525, which has an EntryDate of 9/16/2024 and was previously in tlsa_Enrollment as an active Enrollment. I gave the Project (HAV137) an OperatingEndDate of 9/15/2024 and I gave the enrollment an ExitDate of 10/1/2024.  

The enrollment was excluded from tlsa_HHID and from tlsa_Enrollment after the update; it is the only enrollment that was previously included and is now excluded.

**Comment by TanyaPieterse** [comment]
Hi Molly,

The fix worked perfectly!  This was bad data causing the error, logically a Project cannot start operation after they started participating in HMIS, but unfortunately it is something we will always have to deal with. 
:) 

THANK YOU!!!

**Comment by eanders** [comment]
I hope to have some details before the LSA office hours today, but we're seeing this in one community.  I assume it's bad data, but am not sure what exactly would be useful in tracking it down.

**Comment by eanders** [comment]
Tracked this down to a data bug where a client wasn't present in the Client table, but had data in the enrollments table.  Nothing to see here.
