### ISSUE TITLE
10 LSACalculated Data Quality.sql: question about project type restriction for HIC

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1298]
Hi @MollyMcEvilley,

Section 10 has sub-steps with project type restrictions (9 and 10 are excluded) i.e. ReportRow = 905:

![Screenshot_20241002-083244_Chrome](https://github.com/user-attachments/assets/9e56a398-6ef5-40b1-9cd1-ecfcec1319a3)

I just wonder if these restrictions should be ommited for the HIC submission for this and other ReportRows (both the Sample Code and the Spec).

Please advise. 

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
No, these are fine as is.  We will review for next year after the 2025 HIC.
