### ISSUE TITLE
Section 11: HIC submission

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1299]
Hi @MollyMcEvilley  

Section 11 doesn't have any changes for FY3024.

I wonder if we do should keep the existing logic without changes even if the report is run for HIC purposes. Maybe we need to add Project Type 9 and 10 where LSAscope = 3?

Here is one place, but if changes are needed, some other subsections should be reviewed:
![Screenshot_20241002-094402_Chrome](https://github.com/user-attachments/assets/ee948c81-1c2d-406e-b5c0-7a2a5c66bfdc)

If it makes sense, could you please review the logic (both the Sample Code and the Spec) for:
- NoCoC
- NotOneHoH
- MoveInDate

Thank you, 
Natalie

**Comment by MollyMcEvilley** [comment]
No, this is fine as is -- but thank you for raising the issue.
