### ISSUE TITLE
Spec: 4.1 Get Project.csv requires an update for LSAScope = 3 (HIC)

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1301]
Hi @MollyMcEvilley ,

**1.** The chart for Project.csv provides logic for ProjectIDs for LSAScope = 2:
![image](https://github.com/user-attachments/assets/cbccbb06-0126-4cf5-a18b-d553157174d2)

Could you please take a look if the chart requires an update for a new LSAScope = 3 option?

**2.** The Logic section has subsections for:
- Systemwide LSA 
![image](https://github.com/user-attachments/assets/800b0550-52c9-4e4f-a63b-a27d0e39c7d5)

- Project-Focused LSA 
![image](https://github.com/user-attachments/assets/858c08e7-8a71-477e-bd66-a241f7d79c76)

- Systemwide and Project-Focused LSA
![image](https://github.com/user-attachments/assets/36c8f1dd-7236-49bd-8365-86517f5a8697)

but there is no sub-section for a HIC submission. Could you please take a look and update the Spec?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
1. The graphic is still correct -- the HIC is defined as a systemwide report in section 3.1.  
2. As a reminder that the HIC is a systemwide report, I tweaked the language for Systemwide in section 4.1 as follows:
![image](https://github.com/user-attachments/assets/7d9409dd-b6ca-4cde-914a-6f70ceff6415)
