### ISSUE TITLE
Sample Code: 04_01 Get Project Records.sql

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1302]
Hi @MollyMcEvilley ,

`insert into lsa_Project` SQL query has a restriction by `ProjectType in (0,1,2,3,8,9,10,13)`:

![image](https://github.com/user-attachments/assets/1254e4fc-ad09-407e-9354-3b9d45142175)

**1.** According to the spec, `ProjectType in (0,1,2,3,8,9,10,13)` restriction is valid for LSAScope = 1 (Systemwide).
But for LSAScope = 2 (Project-Focused) ProjectTypes should be 0,1,2,3,8,13 so ProjectTypes 9 and 10 should be excluded:

![image](https://github.com/user-attachments/assets/bf87bfae-30d9-45eb-b7b2-bd9b162b2187)

**2.** What is about LSAScope = 3? Could you please add a rule that for LSAScope = 3 ProjectType restriction should be the same as for ProjectType = 1?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
The projects available for a user to select when they are running a Project-Focused LSA must be limited to (0,1,2,3,8,13), so there is no need for the code to exclude project types 9 and 10.  

The HIC is a systemwide report, so no changes are required.  (See #1301)
