### ISSUE TITLE
Spec: possible formatting issue

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1303]
Hi @MollyMcEvilley ,

I open the Spec in https://onedrive.live.com/ and I see some text moved out from the page layout. I.e.:

![image](https://github.com/user-attachments/assets/c8c13aae-3166-41eb-9223-34561d829953)

Could you please take a look if you do not have such issue? But if you have, could you please review all pages of the Spec as there are actually many places to fix padding.

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
That is really weird!  I don't know how it happened, but I had the same issue when looking at the document on my desktop.
