### ISSUE TITLE
Sample Code: step 9.6

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1304]
Hi @MollyMcEvilley ,

I've noticed that enrollment dates are compared with MoveInDate in the Sample Code, but they are compared with ReportStart in the Spec:

![image](https://github.com/user-attachments/assets/4c40b096-cb33-43a8-818e-159ef00b8e2e)

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
The spec is correct, so I'm tweaking the sample code.  Also adding to both the specs and sample code a validation check for the MoveInDate (must be >= EntryDate for the head of household).
