### ISSUE TITLE
Spec (section 10.5): conditions are different from the Sample Code

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1305]
Hi @MollyMcEvilley ,

I've compared the Spec with the Sample Code and there are a few conditions that are not specified in the Spec.
Just wonder if you want to add them for consistency:

![image](https://github.com/user-attachments/assets/55ecbc3a-6090-490e-8251-f2f4274abe5d)

1. `n.EntryDate <= rpt.ReportEnd`
2. `(x.ExitDate is null or x.ExitDate >= ReportStart)`
3. `EnrollmentCoC = ReportCoC` is applied for HoH only to select Households (as it is programmed in the Sample Code). But the spec doesn't mention it is how households should be selected, instead `EnrollmentCoC = ReportCoC` looks like it should be applied to the current project stay, and, as a result, only HoH are reported.

Best regards,
Natalie

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

Sample Code 10.5 has been updated recently. And `HMISParticipationStatusEndDate >= x.ExitDate` was replaced with `HMISParticipationStatusEndDate > x.ExitDate`. Could yo please update the spec as well?

![image](https://github.com/user-attachments/assets/afb8be67-4f43-487b-86a2-55be0efa49e2)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
An exit date that occurs on the HMIS participation end date is okay -- I have corrected the code in 10.5 and left the specs alone on that point.  I made the other changes in the specs.
