### ISSUE TITLE
Follow-up for #1279: Spec (4.3): Inventory.csv

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1307]
Hi @MollyMcEvilley 

Original issue:

> 1. For consistency with the rest of the report, I think Project.OperatingEndDate >= ReportStart should be replaced with Project.OperatingEndDate > ReportStart.

Resolve comment #1279:
> 1. I updated the specs in section 4.5 (which is the section that applies to Inventory.csv in my version of the document) on 9/25, so this should already be done.

I've reviewed the most recent Spec and it looks like the correction is still needed:

![image](https://github.com/user-attachments/assets/09208639-34fa-4aae-98b5-6baa30da39cb)

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
That is odd!  My version of the specs show that the change was made on 9/25, and I did a commit for the specs on 9/25.  It's possible that I made the change after I did the commit on 9/25, but there have been a few commits since then.  I am about to upload a fresh version...

**Comment by nataliesus** [comment]
Confirm it is fixed now so this ticket can be resolved. Thank you!
