### ISSUE TITLE
Follow-up for #1283: Follow-up for #1256: Spec (7.9): HHFleeingDV

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1308]
Hi @MollyMcEvilley ,

I've downloaded the most recent version of the Spec and it looks like the recent changes you made are vanished because I see a FY2023 version of HHFleeingDV section:

![image](https://github.com/user-attachments/assets/6361d224-f3fa-4559-a41d-896c495b7303)

I've confirmed with the Sample Code just to be sure it is an issue in the Spec. Sample Code looks correct:

![image](https://github.com/user-attachments/assets/cf45448b-da44-4e31-8810-27de28d7d03e)

Could you please double-check the Spec and correct it? Just wonder if other places were mistakenly reverted to the old logic...

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
The change is still there in the version on my desktop... I am going to commit again in a few minutes.
