### ISSUE TITLE
CRITICAL: Sample HMIS Data.zip: Disabilities.csv: InformationDate must be the same as Exit.ExitDate for the following DisabilitiesID: XXX with Data Collection Stage = 3

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1309]
Hi @MollyMcEvilley ,

hmis_Disabilities table is used in the Steps:
- 3.4.5
- 3.4.6
- 3.4.7

There is no Data Collection Stage restriction, instead, the InformationDate is used.

Our validation system prevents import because there are records in the Disabilities.csv for Data Collection Stage = 3 where InformationDate != Exit.ExitDate.

Could you please take a look at fix? 

Here are  CSV Spec requirements:

![image](https://github.com/user-attachments/assets/14fdad75-a52e-4896-b350-211f449bd2d9)

Sample Test KIT:
I.e.:
![image](https://github.com/user-attachments/assets/15193839-9161-4f3c-b445-0b0d043eacbb)

There are 78136 records in the Disabilities.csv with this issue...

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
I have fixed this in my database -- will commit and push to GitHub later today.
