### ISSUE TITLE
Step 3.3.1: ProjectCoC.CoCCode = ReportCoC  condition question

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1311]
Hi @MollyMcEvilley ,

Projects in Step 3.3 are not limited to ProjectCoC.CoCCode = ReportCoC , only hoh.EnrollmentCoC = rpt.ReportCoC is used:

![image](https://github.com/user-attachments/assets/3a764edc-78bd-47d9-9d33-bc82c2f0f443)

Test Case:
- rpt.ReportCoC = XX-500
- Program A:
-- hmis_Project.ProjectID = 1
-- ProjectCoC.CoCCode = AA-101
- Household A:
-- hoh.ProjectID = 1
-- hoh.EnrollmentCoC = XX-500
-- household is selected in Step 3.3.1

So we have a situation, when a Household A is selected and data is inserted into `tlsa_HHID` table, but there is no record in the `lsa_Project` table because ProjectCoC.CoCCode != rpt.ReportCoC.

What do you think? If it makes sense for you, then both the Sample Code and the Spec should be updated.

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
I'm going to leave this one alone.  I'd rather trigger a flag at upload / opportunity to get the discrepancy resolved than quietly exclude it.  Thanks for raising the issue, though -- it's worth thinking about.
