### ISSUE TITLE
Step 3.3.1: hx.ExitDate = rpt.LookbackDate case

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1312]
Hi @MollyMcEvilley ,

Under https://github.com/HMIS/LSASampleCode/issues/1272 you wrote that enrollments with ExitDate = LookbackDate should be excluded:

![image](https://github.com/user-attachments/assets/b6019338-8fb3-4aa6-b44e-957dbba01b30)

I wonder if you can update both the Sample Code and the Spec replacing `ExitDate >= LookbackDate` with `ExitDate > rpt.LookbackDate`:

![image](https://github.com/user-attachments/assets/279df9b3-5ef9-4baa-a7cd-77a0811e6331)

Otherwise, the mapping table under #1272 should be corrected.

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Thank you!
