### ISSUE TITLE
Spec (Section 3.3.1): HMISParticipationStatusStartDate <= ReportEnd is not listed

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1313]
Hi @MollyMcEvilley ,

The Sample Code uses `HMISParticipationStatusStartDate <= ReportEnd` restriction when the most recent HMISParticipation record is selected.
But the Spec does not have such a condition in the Record Selection logic (HMISStart logic works only for enrollments with non-null ExitDate):

![image](https://github.com/user-attachments/assets/0f4d3c19-e0d8-43b3-957b-ec06f489c2dd)

Could you please add a condition to the Spec?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
It is in the section above re: HMISStart and HMISEnd:
![image](https://github.com/user-attachments/assets/ecfcb6aa-a88d-4fe6-aa56-c7d6ec331912)
