### ISSUE TITLE
LSA Upload Error - HHFleeingDV

### ISSUE THREAD

**Issue by TanyaPieterse** [MollyMcEvilley/LSASampleCode#1320]
Hi,
I am testing our LSA Uploads, and we are receiving this error indicating an incorrect value for HHFleeingDV.  Our CSV files have the value "3" in the rows indicated.  

![image](https://github.com/user-attachments/assets/21c8cd99-6efe-475e-b41c-895eeb1d4184)

The list in the Data Dictionary indicates only values 0, 1, and 2.  

![image](https://github.com/user-attachments/assets/b9dab620-8da5-4ec8-899c-d58fb94a50b7)

I am using Molly's lates code on GitHub (THANK YOU SO MUCH MOLLY, it is a life saver!!!).  

Script 07 looks for DVStatus between 1 and 3 on tlsa_Enrollment:

![image](https://github.com/user-attachments/assets/f3b3eb98-f65b-4c0b-9467-5294ba4d8e58)

This lines up with the LSA Specifications indicating for tlsa_Exit the values can be 1, 2, or 3.

![image](https://github.com/user-attachments/assets/ff135f8f-e8c8-46a3-9c9a-a12e3bac330d)

I believe the HUD HDX should not be flagging this as an error and the list in the LSA Dictionary should be updated.

Thanks,

**Comment by cwanska** [comment]
@MollyMcEvilley it looks like this is actually a disconnect between the LSA Data Dictionary and the code so I'm assigning to you to take a look.

**Comment by MollyMcEvilley** [comment]
I am about to commit the very most current version of the Dictionary with the value for 3.  I am not sure when that got out of sync.

**Comment by MollyMcEvilley** [comment]
Actually, I'm going to re-open this and send it back to you for the HDX dictionary update... :)

**Comment by cwanska** [comment]
The change to the data dictionary has been implement on HDX.

**Comment by JessFleming** [comment]
@cwanska - I'm still getting a file rejection when uploading to HDX when HHFleeingDV is 3. I attempted an upload on Friday 10/18 and again today, Monday 10/21.

**Comment by cwanska** [comment]
@JessFleming I'm seeing the same and sorry for the false start here. I am working with the developer and reopening this ticket and figured out how to replicate this issue so I can better test before passing back.

**Comment by cwanska** [comment]
@JessFleming this has been updated and I retested and am now able to upload a file with HHFleeingDV value of 3 in LSAExit. It turns out I updated our dictionary in the wrong place and that was the culprit.
