### ISSUE TITLE
Question about hp1 logic in Step 3.3.1

### ISSUE THREAD

**Issue by evaripatis** [MollyMcEvilley/LSASampleCode#1323]
I may be missing something, but wouldn't the hp1 logic (see screenshot) reduce your tlsa_HHID data to only records associated with a single project?  Are we truly grabbing the top 1 HMISParticipationID, or is this really supposed to be the top 1 according to a certain grouping?
![image](https://github.com/user-attachments/assets/0c30a1c4-58c9-4310-af52-04fdbd9d4162)

**Comment by evaripatis** [comment]
This excerpt, from Step 3.3 in the specifications document, makes it seem like it should be the top 1 HMISParticipationID per ProjectID.
![image](https://github.com/user-attachments/assets/7ffd1eec-6a63-48d5-a7e3-57ebf4ed19fd)

**Comment by nataliesus** [comment]
Hi @evaripatis ,

Just in case, isn't `hp1.ProjectID = hoh.ProjectID` what you are looking for?

![image](https://github.com/user-attachments/assets/b1747dec-2447-45ad-a760-e03e4a9a73b4)

Best regards,
Natalie

**Comment by evaripatis** [comment]
Hey @nataliesus, I appreciate that, thanks!  I think I was expecting to see something like that outside of the sub-query, which is likely why I missed it.

This ticket can be closed.
