### ISSUE TITLE
Questions about MoveInDate values

### ISSUE THREAD

**Issue by evaripatis** [MollyMcEvilley/LSASampleCode#1324]
Perhaps I've been looking at all of this for far too long today, but I'm not seeing how/why the sample tlsaHHID and tlsaEnrollment files are being populated with a value for MoveInDate.  The most recent Enrollment file, from the Sample HMIS Data zip, has MoveInDate as Null for every single record.  The Step 3.3 specifications state that the MoveInDate "is set for the head of household from the HMIS enrollment record only if it occurs before the end of the report period and is logically consistent with the project type, the head of household’s entry/exit dates, and the project’s operating/HMIS participation dates. Under some circumstances, the LSA will use an adjusted MoveInDate."  In the provided chart, it shows that a Null MoveInDate from the Enrollment file should result in a Null MoveInDate for tlsaHHID.  I'm curious then how MoveInDate is being populated with a value in tlsaHHID.  As an example, look at EnrollmentID PSH11910008.  They have a Null MoveInDate in the Enrollment file and a MoveInDate of 4/22/2015 in both the tlsaHHID and tlsaEnrollment file.
Again, it is entirely possible that I have been staring at this for far too long and am missing something as a result, but it definitely feels like something is off here.  Please advise.

**Comment by evaripatis** [comment]
@nataliesus curious if you have any insight on this, seeing as you have a pretty good eye.  Am I missing something, or is there an issue in the code?

**Comment by evaripatis** [comment]
@MollyMcEvilley, could you review and reply?  This is proving to be a blocker in our testing efforts.

**Comment by nataliesus** [comment]
Hi @evaripatis !

>  I'm not seeing how/why the sample tlsaHHID and tlsaEnrollment files are being populated with a value for MoveInDate.

The changes are done in step 3.3.1 for tlsaHHID:

![image](https://github.com/user-attachments/assets/1d172003-b216-46ad-ba06-75f37c81b2fa)

> As an example, look at EnrollmentID PSH11910008. They have a Null MoveInDate in the Enrollment file and a MoveInDate of 4/22/2015 in both the tlsaHHID and tlsaEnrollment file.

I haven't generated the LSA report on the LSA Test Kit yet (I hope to do it on the weekends), also I expect Sample Outputs be re-generated after some tickets are resolved.

Best regards!
Natalie

**Comment by evaripatis** [comment]
@nataliesus, I appreciate you looking.  Sorry if I wasn't clear in my original message.  I know _where_ and _how_ MoveInDate gets populated, generally speaking.  Where I am confused is specifically in regard to the sample data.  Based on the logic, I'm not seeing how tlsa_HHID and tlsa_Enrollment are getting values when hmis_Enrollment has none.
