### ISSUE TITLE
Sample Code (3.3.1): pEnd calculation

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1326]
Hi @MollyMcEvilley ,

![image](https://github.com/user-attachments/assets/3804dd74-b37c-43cd-907f-c533d5734e6f)

1. `part.HMISEnd <= p.OperatingEnd or (part.HMISEnd is not null and p.OperatingEnd is null)` maybe you wanted to use AND instead of OR? Because if HMISEnd > OperatingEnd then the OR part works and the pEnd will be HMISEnd, and not OperatingEnd.

2. Could you please confirm `p.OperatingStart` should be used and not `p.OperatingEnd` in the second WHEN condition?

----

maybe we can simplify the rules to 

case when part.HMISEnd <= p.OperatingEnd then part.HMISEnd
	when part.HMISEnd > p.OperatingEnd then p.OperatingEnd 
	else null end as pEnd

Best regards,
Natalie

**Comment by jbloescw** [comment]
The updated sample code is using SQL keywords Least and Greatest.  @MollyMcEvilley I could be wrong but it looks like these functions operate as kind of an OR statement and the LSA documentation has some of these selections as more of an AND statement.  From what I can gather, especially in the bed night selection criteria could possibly alter the results.  How much of this section was changed to use these functions as opposed to only correcting what @nataliesus brought up.
