### ISSUE TITLE
Spec (3.3.1): Effective Exit Date for ProjectType = 1

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1327]
Hi @MollyMcEvilley ,

1. Sample Code has `LSAProjectType = 1 and LastBednight = rpt.ReportEnd then null` rule which is not listed in the Spec.

2. I wonder if the current Spec priority rules 1 and 2 can be combined into one? So in the result we have:
priority1: if LSAProjectType = 1 and LastBednight = rpt.ReportEnd then Effective Exit Date = null
priority2: if LSAProjectType = 1, Effective Exit Date = LastBednight +1

![image](https://github.com/user-attachments/assets/6f3a985b-7486-4b28-bb4a-b5d657c7abbd)

3. I still wonder of a case when [LastBedNight + 1 day] = either HMISEnd or OperatingEnd. With currently programmed logic in both Sample Code and Spec this case is not covered:

![image](https://github.com/user-attachments/assets/6c257151-dde3-4d49-bbd5-3c90d44e3bc2)

I.e.
- ReportEnd = 10/1/2024
- LSAProjectType = 1
- hx.ExitDate = 9/25/2024
- p.OperatingEnd = 9/25/2024
- part.HMISEnd = 9/25/2024
- LastBedNight =  9/24/2024

According to the current instructions. Effective Exit Date = LastBedNight + 1 = 9/25/2024. But:
- on this date we also have HMISEnd and OperatingEnd so we have a situation when Effective Exit Date = OperatingEnd and it is not allowed for other Project Types
- if we set Effective Exit Date = null it is not correct either, because we have OperatingEnd and HMISEnd before ReportEnd. 
- and if we set Effective Exit Date = LastBedNight then it is against other parts of the spec that tells us that LastBedNight should be less that Effective Exit Date.

![image](https://github.com/user-attachments/assets/9c4358c7-4736-45b4-a579-380752b2e59a)

![image](https://github.com/user-attachments/assets/7c9ab9b4-6257-4355-a528-2ace684f439d)

Please advise where I am wrong and what the expected logic should be.

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
No ExitDate that is greater than ReportEnd is included in tlsa_HHID or tlsa_Enrollment -- they are always NULL.  

If the bed night is 9/30 and ReportEnd,is 9/30, then the effective ExitDate is 10/1 -- which is excluded from tlsa_HHID and tlsa_Enrollment because it's not relevant to the report.

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

Could you please double-check the original 2 points and re-open this ticket?

> No ExitDate that is greater than ReportEnd is included in tlsa_HHID or tlsa_Enrollment -- they are always NULL

Exactly! That is why I wrote that it is covered in the Sample Code (my point 1):
![image](https://github.com/user-attachments/assets/bee21c1c-4de6-466f-9641-9db1bf1a5eee)

but it is **not listed in the Spec** because for Project Type 1 there are 2 first rules and both then say that Effective Exit Date is [LastBedNight + 1 day] and the case then the Effective Exit Date is null for Project Type 1   because of LastBedNight = ReportEnd is not listed (in the spec only, not in the sample code):

![image](https://github.com/user-attachments/assets/304bc860-50bf-448b-8bb0-aaa2c206c8cf)

----

About point 3 (LastBedNight is before ReportEnd but Effective Exit Date = OperatingEnd =  HMISEnd ) -  gave it a second thought and I think it is correct so point 2 is not an issue and you can skip it.

Thank you!
Natalie
