### ISSUE TITLE
Follow-up for #1311: question if we do not need ProjectCoC.CoCCode = ReportCoC restriction in 3.3.1

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1329]
Hi @MollyMcEvilley ,

#1311 was closed with a comment:

> I'm going to leave this one alone. I'd rather trigger a flag at upload / opportunity to get the discrepancy resolved than quietly exclude it. Thanks for raising the issue, though -- it's worth thinking about.

Thus, project stays with hoh.EnrollmentCoC = rpt.ReportCoC but  hoh.EnrollmentCoC is not one of allowed ProjectCoC.CoCCode values are included in the tlsa_HHID table, as it is OK for us.

**1.** So I want to confirm with you if it is OK that projects that are not included in lsa_project are reported for

- **lsa_Calculated step 10.2**:

![image](https://github.com/user-attachments/assets/c123dbef-4482-44ab-a519-9a162eeab837)

- **lsa_Calculated step 10.3**:

![image](https://github.com/user-attachments/assets/fb877347-c40e-4a26-b079-628442706e3b)

**2.** Also, do you know which flag will report the issue that hoh.EnrollmentCoC = rpt.ReportCoC but hoh.EnrollmentCoC is not one of allowed ProjectCoC.CoCCode? I thought that maybe such project stays are counted for [NoCoC] as one of the conditions is ` EnrollmentCoC <> any ProjectCoC.CoCCode for the ProjectID` but then I realised that [NoCoC] is limited to lsa_projects (inner join), and lsa_projects have only projects with CoCCode = ReportCoC. Please advise.

![image](https://github.com/user-attachments/assets/acf476d2-d074-4a46-9e1f-0e87a58c1f49)

Thank you for your insight!
Natalie

**Comment by MollyMcEvilley** [comment]
1.  Yes, it's fine.
2.  The counts in section 9 do not join to lsa_Project, so if the enrollment is in tlsa_HHID/tlsa_Enrollment, there will be a count for the ProjectID in LSACalculated. There is at least one flag that checks ProjectIDs in LSACalculated vs. Project.csv (I don't know the flag number).
