### ISSUE TITLE
Spec: sections 6.2, 7.4, 7.5, 7.7, 7.8: formatting issue

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1331]
Hi @MollyMcEvilley,

Could you please check if you see 6.2, 7.4, 7.5, 7.7, and 7.8 the same as I see and they can be updated?
![image](https://github.com/user-attachments/assets/f88b2c66-68ac-49a5-b9fd-5469476f2936)

![image](https://github.com/user-attachments/assets/d3e201a7-99b7-4c49-acee-c5e286ce260d)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Hi Natalie!  That is very peculiar.  I am not seeing those issues in my version of the specs.  I am about to commit an updated version of the document -- I hope it will be a better reading experience!
