### ISSUE TITLE
Flags List: never generated

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1333]
Hi @MollyMcEvilley , @JulesABrown ,

I've submitted our test LSA output to look at flags list: https://hdxsandbox.abtsites.com/dataset/1150/flag-report

It is said to wait for a few minutes, but the message is still there and no flag is reported even after 3 hours:
![image](https://github.com/user-attachments/assets/8bc76d79-6e05-40a1-99f8-fefe8c4ce728)

Could you please take a look?

Thank you!
Natalie

**Comment by nataliesus** [comment]
Just in case,
I've checked flags list today and I still see the message
![image](https://github.com/user-attachments/assets/66436d56-92be-4de6-b8d7-05e27ca19720)

**Comment by cwanska** [comment]
I'm confirming receipt of this. It could be the developers were working on the system over the weekend but I'm having them look in the log. We will then attempt to reupload the dataset and will let you know when it has been refreshed.

**Comment by cwanska** [comment]
@nataliesus can you please try to replace the upload and confirm it's now generating flags? We identified an error in the Data Dictionary update that seemed to be preventing flags from generating that we believe is now fixed. If you can tag me in your confirmation I'll close this ticket. Thanks!

**Comment by nataliesus** [comment]
Hi @cwanska !

I've submitted another upload - https://hdxsandbox.abtsites.com/dataset/1156/flag-report - and the flags list was successfully generated.

Thank you!
