### ISSUE TITLE
06 LSAHousehold.sql: hhid.Active = 1 condition was removed

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1340]
Hi @MollyMcEvilley ,

In the text for the last commit it was said that no changes to the output was done, but I want to confirm with you one of the updates.

Spec says that we should use `Active = 1` condition for tlsa_HHID table:
![image](https://github.com/user-attachments/assets/9ff71c93-94c5-4abf-982a-5b852c0f31df)

Somewhy `hhid.Active = 1` condition was removed from the Sample Code with the last commit:

![image](https://github.com/user-attachments/assets/6045a419-9062-4e27-81bb-802c38f9f390)

Could you please take a look and restore it for ESTGeography, RRHGeography, and PSHGeography?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Hi Natalie,

I added Active = 1 back into the current version of 6.5, but there was no change to the output without it.  The most recent ES/SH/TH enrollment reflected in tlsa_HHID for a household served in ES/SH/TH during the report period (ESTStatus > 2) must by definition be during the report period.  The output will be the same regardless of whether it is there or not.
