### ISSUE TITLE
Sample Code (3.6.2): ActiveHHType rewritten query

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1341]
Hi @MollyMcEvilley ,

Step 3.6.2 has been updated recently under #1336 (please notice that under #1336 only Exit1HHType and Exit2HHType were discussed, not ActiveHHType; also. no changes for ActiveHHType were submitted for the Spec) :

![image](https://github.com/user-attachments/assets/c53ff1fa-d8dd-4c4a-b50d-9b8b4a816782)

I have a few concerns:

Both the Sample Code and the Spec have a rule that if `ExitDate  < CohortStart` then `ActiveHHType = EntryHHType`:

Sample Code:
![image](https://github.com/user-attachments/assets/3b4d73d2-0f4a-4bd1-830c-0620a847f95b)

Spec:
![image](https://github.com/user-attachments/assets/dae2595e-449e-47ff-8b9c-ce7ff19b4d00)

With the recent update (tlsa_Enrollment are limited to `ExitDate is null or ExitDate >= CohortStart`) households exited before CohortStart:
- are **ignored** (because of inner join for hh) so we lose cases for  `if ExitDate  < CohortStart then ActiveHHType = EntryHHType`
- their ActiveHHType in DB is null, not 99 or any other value

So either the updated part of the Sample Code should be re-written, or both Spec and Sample Code should be rewritten where `ExitDate  < CohortStart` then `ActiveHHType = EntryHHType` is used.

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
This is complete.

![image](https://github.com/user-attachments/assets/9b64e97a-afd2-4a2b-8092-0de015db269f)
