### ISSUE TITLE
Sample Code (3.6.3 and 3.6.4): Exit1HHType and Exit2HHType issues

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1343]
Hi @MollyMcEvilley ,

Exit1HHType and Exit2HHType have been updated recently under #1336.

I think there are **2 issues** in the Sample Code now:

**Issue 1:**
Both the Sample Code and the Spec have a rule that records where `ExitDate < CohortStart` are valid and then Exit(1|2)HHType = EntryHHType:

![image](https://github.com/user-attachments/assets/b29f28df-abd1-4c81-aca7-1b35e73d5631)

But because of the new `and (n.ExitDate is null or n.ExitDate > cd.CohortStart)` row in the Sample Code, if a household has only project stays with ExitDate < CohortStart, then such household is ignored because of `inner join ( ... ) hh` so `when hhid.ExitDate < cd.CohortStart` is never checked and Exit(1|2)HHType is not set to EntryHHType:

![image](https://github.com/user-attachments/assets/239e7131-f90e-4878-9453-87c15265e48d)

I wonder if instead of  `inner join ( ... ) hh` you want to use  `left join ( ... ) hh`?

**Issue 2:**

The spec was updated using `tlsa_Enrollment.EntryDate < CohortEnd` condition for Exit1HHType/Exit2HHType ( `For all other households ...`):

![image](https://github.com/user-attachments/assets/1517cb3a-aab9-4dcf-9a0b-17326599e6aa)

But this rule wasn't added to the Sample Code for Exit1HHType and Exit2HHType. Please take a look.

Best regards,
Natalie

**Comment by TanyaPieterse** [comment]
Hi Molly,

We are experiencing the same issue with the Sample Code.  Because Exit1HHType and Exit2HHType is being set to null under the above conditions Natalie explained, Step 7.2.1 will cause an insert fail error:  "Cannot insert the value NULL into column 'HHType', table 'dbo.tlsa_Exit'; column does not allow nulls. INSERT fails."

Thank you

**Comment by MollyMcEvilley** [comment]
https://github.com/HMIS/LSASampleCode/commit/b4e99bdae5c878f51bfa4ac40d717e5b235e0f05

This has been addressed in the commit linked above.
