### ISSUE TITLE
Flags list is not generated

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1345]
Hi @cwanska ,

I've uploaded the new LSA report today - https://hdxsandbox.abtsites.com/dataset/1158/flag-report - and didn't get the flags list:

![image](https://github.com/user-attachments/assets/e8f0ed25-7c2d-450e-8a07-5c3e94dc399e)

Could you please take a look?

Thank you!
Natalie

**Comment by nataliesus** [comment]
Just in case, after 1.5 hours I still see that message

**Comment by cwanska** [comment]
@nataliesus our team looked into this and discovered your Inventory file has a CoC listed as XX-501 but the CoC in LSAReport is NV-501. Can you try to correct that and upload again? I'd also invite you to try the upload on the new upgraded Sandbox environment https://hdx-sandbox.abtsites.com/ (it should work with your existing credentials.

**Comment by nataliesus** [comment]
Hi @cwanska ,

I've generated a new report, fixed CoC Codes in Inventory.csv, LSAReport.csv, and ProjectCoC.csv files and uploaded to https://hdx-sandbox.abtsites.com/.

The new uploaded file URL is https://hdx-sandbox.abtsites.com/dataset/1193/flag-report

![image](https://github.com/user-attachments/assets/9ba6ee90-85d6-4316-9a9d-92754d685ee4)

Could you please take a look?

Thank you!
Natalie

**Comment by nataliesus** [comment]
The flags list was successfully generated. Thank you, @cwanska !
