### ISSUE TITLE
Race Case Found in Step 6.5.1

### ISSUE THREAD

**Issue by evaripatis** [MollyMcEvilley/LSASampleCode#1349]
I've identified what appears to be a race case in Step 6.5.1.  This occurs if two tlsa_HHID records, for the same LSAProjectType group (EST, RRH, or PSH), have the same HoHID, ActiveHHType, ExitDate, and EntryDate, but different GeographyType values.  As an example, please see HoHID C28764.  This individual has two tlsa_HHID records for different projects, both with an LSAProjectType of 13.  One project, RRH123, has a Geography value of 2, while the other project, RRH149, has a value of 1.  Your results currently have the value of 2 making it into the tlsa_Household record, but it seems as if it could just as easily come up 1.  Our system currently also includes an ordering by EnrollmentID, descending, after ExitDate and EntryDate, to avoid any such race cases.  Does EnrollmentID need to be added to the ordering in the sample SQL?  If so, is descending the appropriate choice, as we are currently doing?  Thanks.

**Comment by MollyMcEvilley** [comment]
The specs don't specify additional sorting criteria, so however you want to approach it is fine.  My instinct would also be to use EnrollmentID DESC as additional criteria, but whether or not that would get you the most recently created enrollment is entirely dependent on how EnrollmentIDs are generated -- e.g., GUIDs don't sort sequentially.
