### ISSUE TITLE
Flag 808: Geography Type Alignment

### ISSUE THREAD

**Issue by LaurenBianchi** [MollyMcEvilley/LSASampleCode#1350]
Hello and Happy LSA Season, @cwanska! :) 

We are getting customer inquiries concerning Flag 808: "The Geography Type you reported for this zip code ({zip}) does not align with the crosswalk published by HUD. The Geography Type reported is {geographytype}, but what we expect is {geographytype_expected}." 

When reviewing the output and comparing it to the [HUD Crosswalk](https://www.hudexchange.info/resources/documents/Zip-Code-to-Geography-Crosswalk.xlsx) released in March 2024 - the LSA is producing a GeographyType that aligns with the crosswalk. The zip code lines up with GeographyType = 2 but the LSA Flag states "The Geography Type you reported for this zip code does not align with the crosswalk published by HUD. The Geography Type reported is 2.0, but what we expect is 1.0."

Please let me know if there is any additional information that is helpful for this review. 
Thank you for your time and insight! 
LB

**Comment by cwanska** [comment]
@LaurenBianchi we are looking into this issue and it was reported via a CoC as well. I will post an update here as soon as we have a resolution. Thanks!

**Comment by LaurenBianchi** [comment]
@cwanska Thank you for your time and support! 
I did a quick comparison between the March 2024 version of the HUD Crosswalks and the previous version. I'm not sure if this information is useful, but I wanted to share it just in case. All the reported zip codes for which we received inquiries were included in this filtered list of shifts resulting from the update. https://bitfocus.box.com/s/tqdmj5fwouw963f5hltllcznx5n844xu

**Comment by cwanska** [comment]
@LaurenBianchi  we have pushed out changes that should clear up any erroneous 808 flag issues.
