### ISSUE TITLE
Section 10.5 does not apply required ProjectType filter

### ISSUE THREAD

**Issue by eccovia-csmith** [MollyMcEvilley/LSASampleCode#1351]
The current code does not meet the specification requirements for ProjectType in section 10.5. Projects with ProjectType 9 and 10 should be excluded, but they are currently being included.
https://github.com/HMIS/LSASampleCode/blob/02cae7778f94327f8fdcb074f6f10eceffd38ca9/10%20LSACalculated%20Data%20Quality.sql#L108

https://github.com/HMIS/LSASampleCode/blob/02cae7778f94327f8fdcb074f6f10eceffd38ca9/04_01%20Get%20Project%20Records.sql#L47C3-L47C44

The insert into lsa_Project includes these 2 project types (9,10) so section 10.5 needs to apply the required filter.

Specification:
> •	ProjectID = lsa_Project.ProjectID and ProjectType is not in (9,10); and

**Comment by nataliesus** [comment]
Just in case, a similar issue can be found here: #1346

**Comment by MollyMcEvilley** [comment]
Closed by [this commit](https://github.com/HMIS/LSASampleCode/commit/39729928ca6e25aff8d1b46ada4dbc6f830c19d0)
