### ISSUE TITLE
Follow-up for #1346: Spec: 10.5

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1358]
Hi @MollyMcEvilley ,

Follow-up for #1346:

The Sample Code has instructions that are not listed in the Spec:
- x.ExitDate <= rpt.ReportEnd
- 
![image](https://github.com/user-attachments/assets/1af996c3-a96e-441f-b04c-49f687b0d0fa)

Could you please take a look and update the Spec?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
The specs are locked for changes.  I'm updating the sample code.
