### ISSUE TITLE
Step 3.4.4: issue with tlsa_Enrollment.DVStatus

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1359]
Hi @MollyMcEvilley , @cwanska ,

I need to confirm with you Step 3.4.4.

tlsa_Enrollment.EntryDate and tlsa_Enrollment.ExitDate were significantly changed this year. And I think it can cause some kind of an issue with DVStatus value and other tables/rows that use DVStatus in their calculation logic.

I.e. a client has ES E-E project that started on 9/1/2024 and is still active, only enroll screen was collected with HealthAndDV info included. So:
hmis_HealthAndDV has next data:
- InformationDate = **9/1/2024**
- DomesticViolenceSurvivor = 1
- CurrentlyFleeing = 1

hmis_Project.OperatingStartDate = 8/30/2024

But hmis_HMISParticipation = 9/5/2024 - active.

In this case, **tlsa_Enrollment.EntryDate = 9/5/2024** (adjusted because of HMISParticipationStatusStartDate).

Step  3.4.4 uses tlsa_Enrollment.EntryDate and tlsa_Enrollment.ExitDate restrictions. As a result, **tlsa_Enrollment.DVStatus is 98**, not 1
![image](https://github.com/user-attachments/assets/83fc3eaf-20bb-42a0-84cd-70c0152888ec)

Could you please confirm it is a correct logic and no changes are needed either to the Sample Code or the Spec?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Yes, this is acceptable.
