### ISSUE TITLE
HDX Flag 1340 - Affiliation.csv (No Results Expected per LSA Specs)

### ISSUE THREAD

**Issue by LaurenBianchi** [MollyMcEvilley/LSASampleCode#1361]
Hello and Happy Monday! @cwanska 

One of our customers is getting flag 1340 as the project Operating End Date was one day prior to the LSA Report Start Date. 
Based on the logic for the affiliation records, we would not expect this project to populate the affiliation.csv - but the flag logic appears to only throw when `any_affiliation=0 & residentialaffiliation=1` without any additional conditions. 

Is it possible to add an additional condition to the logic to only throw this flag when the Operating End Date is null or after the LSA Report Start, suppress the flag when the Operating End Date is before the LSA Report Start Date, or shift to a Warning so the community can add notes to explain this situation? 

Thank you for your time and assistance! 
LB

**Comment by vlopez0603** [comment]
Hi @LaurenBianchi,

We'll take a look at this flag! In the meantime, would it be possible for you to identify which CoC this flag is for so we can make sure the right liaison reaches out to them?

Best,
Victoria

**Comment by LaurenBianchi** [comment]
Thank you, @vlopez0603 !
The CoC is Glendale (CA-612).

**Comment by vlopez0603** [comment]
Thanks, @LaurenBianchi! I've reviewed the CoC's LSA files, confirmed the issue, and put in a ticket for our flag team to do a deeper dive into the best solution. I'll also have Glendale's liaison reach out to keep them informed.

**Comment by vlopez0603** [comment]
This was resolved 12/10/2024. CoCs were notified and details were listed on the [HDX Weebly](https://hudhdx2infoissues.weebly.com/).
