### ISSUE TITLE
LSA Upload error

### ISSUE THREAD

**Issue by brimckinney** [MollyMcEvilley/LSASampleCode#1362]
I’m currently working on the LSA audit for Decatur/Macon CoC IL-516. This morning, I tried to replace my report after fixing some errors like I’ve done at least twice since we’ve started the LSA process. It will not let me upload my new report at all. It’s saying there is a server processing error. I’ve tried to reupload at least 5 times today. All getting the same error. I have not done anything differently with the upload process since I figured it out the first time. I’m led to believe this is an issue with HDX. Please if anyone can reach out and give urgent guidance would be very appreciated. My team would like to get back to correcting those errors.

I also noticed that in HDX the timeframe category for the rejected reports is way off. It's stating that the timeframe dates are 01/01/2000-01/01/2000.  Obviously that's not right, and before the upload when i exported these reports, i obviously put the correct dates (10/1/23-9/30/24).

**Comment by cwanska** [comment]
Sorry we were having a storage issue which has been resolved. You should be able to upload without issue now.
