### ISSUE TITLE
Spec (Step 5.4): HIV, SMI, SUD logic for clients who are neither adults or childer

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1366]
Hi @MollyMcEvilley ,

In the Sample Code HIV, SMI, SUD  are calculated as -1 for clients with ActiveAge > 65:

![image](https://github.com/user-attachments/assets/f193277b-0aff-4f7e-89f0-cc4c0f3e1e93)

The Spec has instructions for:
- People under 18 ( HIV, SMI, SUD = -1 )
- adults

But there is no logic for clients with ActiveAge > 65:

![image](https://github.com/user-attachments/assets/bd33a21f-c3dd-4be2-b5d4-f42129bd1fe6)

Please advise what logic is missing in the Spec.

If anything should be updated, it is should be done for 3 columns: HIV, SMI, SUD 

Thank you!
Natalie

**Comment by nataliesus** [comment]
Another point I am curious about is that in the Spec it is said to use hmis_Disabilities for *any person*, but in the Sample Code we use *adult only* clients:

![image](https://github.com/user-attachments/assets/6c007c35-6316-444c-b92c-57df08213db9)

Which one should be corrected? Spec or Sample Code? (This question also relates to 3 columns: HIV, SMI, SUD)

**Comment by MollyMcEvilley** [comment]
We're going to leave this alone this year.  The data were intended for use for the HIC/PIT and the counts are only relevant to HUD for adults but including them for all clients doesn't hurt anything.
