### ISSUE TITLE
Sample Code (Step 5.4): HIV, SMI, SUD - client logic used in hmis_Disabilities table

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1367]
Hi @MollyMcEvilley ,

Another point I am curious about is that in the Spec it is said to use hmis_Disabilities for any person, but in the Sample Code we use adult only clients:

![image](https://github.com/user-attachments/assets/69ffc36e-910c-4f7f-a587-294f3fd90e3c)

Which one should be corrected? Spec or Sample Code? (This question also relates to 3 columns: HIV, SMI, SUD)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
We're going to leave this alone this year.  The data are intended for use for the HIC/PIT and the counts are only relevant to HUD for adults but including them for all clients doesn't hurt anything.
