### ISSUE TITLE
InformationDate usage: different logic for hmis_Disabilities and hmis_HealthAndDV 

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1369]
Hi @MollyMcEvilley ,

Maybe it is for the next FY, but I wonder why we use different  InformationDate restrictions selecting data from the hmis_Disabilities and hmis_HealthAndDV tables (both Sample Code and the Spec):

When HIV, SMI, SUD (steps 3.5.6, 3.5.7, 3.5.8) are calculated, for the **hmis_Disabilities** table we just use InformationDate <= ReportEnd restriction and do not check that InformationDate is within the real or adjusted Entry/Exit dates:

![image](https://github.com/user-attachments/assets/705f0d8d-06ba-478f-a8ee-d491b069a449)

When DVStatus (step 3.4.4) is calculated, we check that in the **hmis_HealthAndDV** table:
- InformationDate <= ReportEnd,
- InformationDate >= n.EntryDate (adjusted)
- InformationDate <= n.ExitDate (adjusted, and if it exists)

![image](https://github.com/user-attachments/assets/24ca4f55-8973-4a8d-bef8-8ab50a9a3f4a)

Could you please advise?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
We will take a look at this for next year.
