### ISSUE TITLE
Sample Code (Step 6.12.2.b) suggestion to move to a separate insert query (for FY 2025)

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1370]
Hi @MollyMcEvilley ,

I have an idea for FY2025.

sys_TimePadded table can be very big. I think if 6.12.2.b is moved from the UNION to a separate INSERT statement (plus extra join to exclude dates if they are already covered by existing ranges) will help us to exclude the unnesessary rows:

I.e. for the client C15480 the 2023-08-03 - 2024-01-16 period ( `C15480,1,1,2023-08-03,2024-01-16` row)  generated in the 6.12.2.a step already includes periods generated by ES NbN services (green rows), so green rows do not impact on the report logic but increase the sys_TimePadded table size:

![image](https://github.com/user-attachments/assets/e5bdccab-b5c5-4efd-89fb-875e68544cc5)

What do you think?

If you like the idea, then the same approach can be applied to the sys_TimePadded_exit table.

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
I added a link to this issue in the Performance Monitoring discussion so that I don't lose track of it for next year.
