### ISSUE TITLE
Sample Code (7.8.1): issue for the CHTime = 365, CHTimeStatus = 1

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1371]
Hi @MollyMcEvilley ,

Comparing our report output with the Sample Output, I think I found an issue in Sample Code Step 7.8.1.

In the Spec (7.8.1) it is said to set program CHTime and CHTimeStatus values **if they are not previously set in the Step 7.4** :

![image](https://github.com/user-attachments/assets/500189ff-1a9f-4c01-a950-d9c25215c64b)

But in the Sample Code Step 7.8.1 there is no `WHERE CHTime is null` restriction, so if CHTime was set on 7.4 then for some cases it is rewritten on Step 7.8.1:

![image](https://github.com/user-attachments/assets/6bd8819f-e0fc-4c9f-917d-619139031dc0)

Could you please take a look? The update can impact other calculations.

Here are some rows from tlsa_ExitHoHAdult that can be helpful to see there is an issue:

![image](https://github.com/user-attachments/assets/8db13069-686e-4af3-99a4-60a8592cee77)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
This step (7.8.1) is setting a value based on ch_Episodes_exit, which is populated from records in ch_Include_exit.  

The insert statements for ch_Include_exit are either limited to records in tlsa_ExitHoHAdult where CHTime is null (7.6.1, 7.6.2, and 7.6.3) OR are based on records already in ch_Include_exit (7.6.4).

The intent behind setting CHTime/CHTimeStatus to 400/2 based on 3.917 for the QualifyingExitHHID is just to cut down on processing overhead / avoid all of the ch_Exclude/Include/Episodes stuff for people we already know are CH.  

If there are records in ch_Episodes_exit for an adult/HoH that meet the criteria for 365/1, that's fine -- what actually goes into tlsa_Exit (and ultimately LSAExit.csv) is the same.

![image](https://github.com/user-attachments/assets/ce6a31f3-f119-4298-940b-a070b89b90f3)
