### ISSUE TITLE
Flag 1318-1.6058 - query

### ISSUE THREAD

**Issue by eanders** [MollyMcEvilley/LSASampleCode#1372]
@cwanska and @MollyMcEvilley,

We are trying to investigate a flag for a customer and are somewhat confused about how it can come about.

**1318-1.6058**: In your LSA data, <project name>, has reported 4.0 more household enrollments among all clients served during the report period than the total number of enrollments among all clients served during the report period. Within a project, the number of household enrollments among all clients served during the report period cannot be greater than the total number of enrollments among all clients served during the report period. You may need vendor assistance to resolve this error.

We've verified that the project is in the database but does not have any enrollments that overlap the report range.
The enrollments appear to be reasonable, every one is their own HoH (RelationshipToHoH = 1) and all of the HouseholdIDs are unique.

Some of the clients do have other enrollments in the universe, but can either of you think of a reason why the project would have enrollments in this flag when there are no active enrollments during the report range?  The last enrollments were exited 9/30/2023.  The latest move-in dates are also 9/30/2023.  The Operating End Date of the project is also 9/30/2023.

The flag file mentions 
> DQ  Household Entry (ReportRow=909) where Cohort=1 (Active in the current report period) & HHType=0 (All) & Population=0 (households)

Any insight on where to dig would be greatly appreciated.

**Comment by eanders** [comment]
@MollyMcEvilley I was able to track this down.  Not sure if something needs to change, but the issue is that the clients moved-in on their exit date and are exited on the day before the report period starts.

In 3.3.1, there's logic that moves their exit date for `tlsa_HHID` forward one day.
```
case 
		when LSAProjectType = 1 and LastBednight = rpt.ReportEnd then null
		when LSAProjectType = 1 and ExitDate < rpt.ReportEnd then dateadd(dd, 1, LastBednight)
		when dateadd(dd, 90, LastBednight) <= rpt.ReportEnd then dateadd(dd, 1, LastBednight)
		-- When RRH MoveInDate = ExitDate, uses an effective ExitDate of MoveIn + 1 day so that subsequent
		--	sections can use the same logic for RRH and PSH.
		when LSAProjectType in (13,15) and core.MoveInDate = ExitDate and ExitDate = rpt.ReportEnd then NULL
		when LSAProjectType in (13,15) and core.MoveInDate = ExitDate and ExitDate < rpt.ReportEnd then dateadd(dd, 1, ExitDate)
		when pEnd is not null and (ExitDate is null or ExitDate >= pEnd) then pEnd   
		else ExitDate end
```

Maybe this should move their move-in date back one day?
By extending their enrollment, they are now enrolled after the project operating end date, even though the original HMIS data did not have this issue.

**Comment by MollyMcEvilley** [comment]
We can't adjust the MoveInDate without changing the specs, but we can fix the code so that this doesn't happen.

![image](https://github.com/user-attachments/assets/1c493e15-1377-4b06-975b-30c1c1bb8e9c)

**Comment by eanders** [comment]
Thanks @MollyMcEvilley, just to see if I understand that change.  This means the Exit Date is only moved if both of the following are true:

1. The move-in-date is on the exit date
2. The project does not have an operating end date or the move-in-date is strictly before the operating end date (with some complexity in determining what to use for the operating end date)

I think that works.  Will that break the original reason for moving the exit date further down the line?  (Sorry, the original reasoning is unclear to me.)
