### ISSUE TITLE
Section 3.3 ExitDate

### ISSUE THREAD

**Issue by jbloescw** [MollyMcEvilley/LSASampleCode#1373]
We had a flag show up (1237-1.120) stating that the average stay length of bed total bed nights divided by total number of people cannot be greater than the report period (366).

I have investigated this particular flag down to one client and it revolves around their exit date.  I noticed that the client's exit date is coming in past the report period end date.

I see in the specs:  _An ExitDate > ReportEnd should be evaluated as NULL prior to making any adjustments_
However, I cannot see the sample code doing this or restricting it to be cut off at the report end.

I'm curious if I am missing something here or if we need to alter the code to set exit dates after the report end to a null before the alterations happen.

**Comment by eanders** [comment]
@jbloescw this sounds like the same issue I'm seeing from a different angle.
https://github.com/HMIS/LSASampleCode/issues/1372

Basically, 3.3.1 moves the exit date if the move-in date is on the exit date.  Is that your case?

**Comment by jbloescw** [comment]
@eanders In my case, no.  The client has a move in date, but is not in a project type that would have been picked up by the case when statement to set it as an exit date.  In my case, the client has an exit date after report end and that's what is coming through.  I'm pretty sure that in my case, the exit date needs to be capped off at the report end date.
I interpreted the specs to state: "If an exit date is present and it is after the report end, to treat it as null."  I don't see any alteration of the exit date in this way within the sample code and I'm pretty sure it's giving clients longer times in the system which is tripping flags.
