### ISSUE TITLE
Possible flag issue for flag 791

### ISSUE THREAD

**Issue by candiceh214** [MollyMcEvilley/LSASampleCode#1377]
Flag 791 states "Seasonal   inventory records need to have an end date. This record for seasonal bed inventory is missing an end date". 

I have spot checked several records on different sites and found that where the Seasonal End Date is greater than the Report End Date that these are triggering flag 791.  The records do have an end date.  You can see this on the MI-509 upload.

**Comment by vlopez0603** [comment]
Hello @candiceh214 - Can you please confirm that MI-509 is the upload we should be looking at? In reviewing this CoC's flag file, I do not see that they have flag 791.

Is there another CoC that you know of that has flag 791 with a Seasonal End Date that is greater than the report period?

**Comment by candiceh214** [comment]
Hi @vlopez0603 it looks like they made some updates after I spotted it and before I could get this posted.  I am not seeing this issue any longer.  The others I spot checked must be the same (they are updating records before we can investigate).  I think we are ok to close this out.
