### ISSUE TITLE
ref_Calendar question

### ISSUE THREAD

**Issue by jbloescw** [MollyMcEvilley/LSASampleCode#1379]
Hi Molly,
I see that the ref_Calendar is hardcoded to go to 9/30/2025.  Is there a particular reason that it needs to go that far?  From what I can tell in the code, it might only need to go out 1 day past the report end date.

We have a customer stating that 9.5 is letting in dates past 9/30/2024 and capping that off will fix a flag they are seeing (774-2.674).  I'm wondering if this would have surfaced previous to the recent fix in 3.3.2 exit dates that would now be capped.  Curious for your take on this.

**Comment by MollyMcEvilley** [comment]
If it is going to be possible to use the sample code to generate local use LSA files in the coming months, it's necessary to have dates that extend at least through the end of the current fiscal year.

Joins to ref_Calendar are restricted by ReportStart and ReportEnd in 9.5 -- I might be overlooking something, but I don't think there's an issue there.  Do you see something specific?

I'll leave this open in case you have additional info about a bug in 9.5.  If not and this answers your question, please feel free to close it!
