### ISSUE TITLE
Flag 1004-1 Utilization regarding Inventory and LSACalculated

### ISSUE THREAD

**Issue by 2008zjqc** [MollyMcEvilley/LSASampleCode#1380]
Hi Molly,

We got the couple utilization flag such as 1004-1 in our report. The full message is as below:
All households in ES: An average of (XXX) people were served in (XXX) available beds on a given night. That results in a low utilization rate of (xxx). Please check your data and let us know if 1) only the average number of people (XXX) is inaccurate, 2) only the average number of available beds (XXX) is inaccurate, 3) both numbers are inaccurate, or 4) the data is accurate. If either number is inaccurate, please update your data and reupload it to HDX. If both numbers are accurate, please explain why the utilization rate  is so low.

Could you please assist us or explain to us how the above Average people and Available beds been calculated? Or in other words, how the utilization been calculated? 

Thanks in advance for your time and help,
Best,
Chen

**Comment by MollyMcEvilley** [comment]
Available beds on a given night is calculated based on Inventory.csv using the number of beds and InventoryStart/EndDates.

Average people served on a given night is calculated based on the number of bed nights (ReportRow 56) divided by the number of nights in the report period.

Please let me know if you need additional info!  Thank you.  -Molly
