### ISSUE TITLE
HousingType equals NULL

### ISSUE THREAD

**Issue by bdavis-pcl** [MollyMcEvilley/LSASampleCode#670]
I am receiving an error when running the report.

> Msg 515, Level 16, State 2, Line 15
> Cannot insert the value NULL into column 'HousingType', table 'LSA.dbo.lsa_Project'; column does not allow nulls. INSERT fails.

It is occuring at this line here, but that isn't helpful. I'm including it for clarity.
https://github.com/HMIS/LSASampleCode/blob/5698aa2f808c7408c1fd1196e46175d6c4b17e8a/04_01%20Get%20Project%20Records.sql#L15

The actual error is here:
https://github.com/HMIS/LSASampleCode/blob/5698aa2f808c7408c1fd1196e46175d6c4b17e8a/02%20LSA%20Output%20Tables.sql#L46

The HMIS CSV allows for HouseType to be null. Yet the lsa_Project table is requiring them to not be Null.

This can be fixed by removing the not NULL restriction.

**Comment by MollyMcEvilley** [comment]
The HMIS CSV allows for null values because housing type is n/a for non-residential projects. However, the LSA only includes residential project types and the HDX will not accept uploads with NULL values for HousingType.
