### ISSUE TITLE
01 Temp Reporting and Reference Tables.sql: comment needs correction

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#671]
Hi @MollyMcEvilley ,

Just in case, "tlsa_Pops" is no longer a table used in LSA. Instead, there are 2 other tables:
- tlsa_AveragePops
- tlsa_CountPops

![image](https://user-images.githubusercontent.com/28144855/136195774-2a5bc53e-db1d-4cad-9ef1-1754a2dccd51.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Thank you!  Commit forthcoming.
