### ISSUE TITLE
lsa_Organization table: OrganizationName and OrganizationCommonName have wrong size 

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#672]
Hi @MollyMcEvilley ,

Could you please double-check element size for:
- OrganizationName
- OrganizationCommonName

In LSA FY2022 they are string 100:
![image](https://user-images.githubusercontent.com/28144855/136202097-aa5d8864-aa69-4561-9466-34d8b475a0e3.png)
![image](https://user-images.githubusercontent.com/28144855/136202428-92dd670c-699c-4c66-accc-13578b447349.png)

But in Export CSV FY2022 they are string 50:

https://www.hudhdx.info/Resources/Vendors/HMIS_CSV_Specifications_FY2022_v1.2_clean.pdf
![image](https://user-images.githubusercontent.com/28144855/136201842-c87021f1-2939-4d0c-993b-e1f5c27c752a.png)

Best regards,
Natalie

**Comment by kiadso** [comment]
Thank you Natalie! I'm checking on this.

**Comment by MollyMcEvilley** [comment]
Leaving this alone as n/a to the LSA logic.

**Comment by nataliesus** [comment]
Hi @kiadso , @MollyMcEvilley ,

I just wonder if OrganizationName with length > 50 symbols be included in the flags list because of 
![image](https://user-images.githubusercontent.com/28144855/136402336-8463d0ef-1a20-4c94-a326-a51aa4c6df86.png)

Maybe you still need to fix max length for OrganizationName as it was originally requested?

Best regards,
Natalie
