### ISSUE TITLE
lsa_Project: ProjectCommonName has wrong size

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#673]
Hi @MollyMcEvilley ,

Could you please double-check the element size for ProjectCommonName? It is string **100** in LSA FY2022.

![image](https://user-images.githubusercontent.com/28144855/136203383-ea27316e-1819-4ec7-b2a9-0a5166efc4fb.png)

But in Export CSV FY2022 it is string 50:
https://www.hudhdx.info/Resources/Vendors/HMIS_CSV_Specifications_FY2022_v1.2_clean.pdf
![image](https://user-images.githubusercontent.com/28144855/136203301-5c300dfd-ea6b-4249-a9ed-a46b9a0ab522.png)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
I am going to leave this alone as n/a -- the HDX doesn't import it one way or the other.  Given that other field sizes have expanded, it might make sense for the HMIS CSV to go to 100, but that's a separate issue.
