### ISSUE TITLE
LSA Programming Specifications FY2021.docx: Revision History FY reference

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#674]
Hi @MollyMcEvilley ,

I just want to confirm the most recent version of LSA is for FY20**22** because if yes, then it is a bit confusing to see FY2021 and not FY2022 in the revision history.

![image](https://user-images.githubusercontent.com/28144855/136206432-47872382-9943-4e6a-85b2-5966b4211023.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
The reporting period is FY2021 -- 10/1/2020 through 9/30/2021.

**Comment by nataliesus** [comment]
Thank you, @MollyMcEvilley! It is just a bit confusing with other federal reports that are also should be run on 10/1/2020 through 9/30/2021 but their spec and data dictionary say it is FY2022.
