### ISSUE TITLE
Step 3.3.1: Project.OperatingEndDate >= 10/1/2012 restriction is missing in the Sample Code

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#676]
Hi @MollyMcEvilley ,

In the spec there is Project.OperatingEndDate >= 10/1/2012 restriction. But this restriction was removed from Sample Code when it was updated.

**Spec:**
![image](https://user-images.githubusercontent.com/28144855/136216780-fb7ae12b-e426-4745-a369-27aaeede036e.png)

**Sample Code:**
![image](https://user-images.githubusercontent.com/28144855/136216881-95bc4345-5bfe-46ea-9336-019e5f38701a.png)

Could you please advise?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Thank you -- commit forthcoming.
