### ISSUE TITLE
Step 3.3.1: tlsa_HHID.ExitDate calculation question

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#677]
Hi @MollyMcEvilley ,

Could you please advise why next rows were added for tlsa_HHID.ExitDate calculation? They appeared in Sample Code FY2021 only and are not listed in the LSA Spec.

**Rows:**
`when p.ProjectType = 13 and hoh.MoveInDate = hx.ExitDate and hx.ExitDate = rpt.ReportEnd then NULL
when p.ProjectType = 13 and hoh.MoveInDate = hx.ExitDate then dateadd(dd, 1, hx.ExitDate)`

**Sample Code:**
![image](https://user-images.githubusercontent.com/28144855/136226554-f704759d-0b25-440e-ab9e-fe1513b5aef3.png)

**LSA Spec:**
Cannot find where MoveInDate should be used for adjusted ExitDate calculation:
![image](https://user-images.githubusercontent.com/28144855/136226930-de5c0399-1fc9-4f8d-8439-0ba2bd5b43e0.png)

BTW, in the same 3.3.1 step tlsa_HHID.MoveInDate is adjusted for ProjectType = [3, 13]. So if tlsa_HHID.ExitDate should use MoveInDate logic, shouldn't it be adjusted MoveInDate?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Thank you -- corrected in the specs -- upload forthcoming.

WRT the effective **ExitDate** -- it would differ from the HMIS _ExitDate_ based on move-in date only in two very specific circumstances where an RRH MoveInDate = ExitDate -- so any potential difference between the recorded and effective **MoveInDate** is already accounted for in the **ExitDate** logic (e.g., an adjustment based on _OperatingEndDate_).

![image](https://user-images.githubusercontent.com/6156815/136230437-5c9c2f13-6c6c-4433-ab4b-b5c0d71d86cf.png)

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

**Q1.**
In Sample Code there is p.OperatingEndDate **<=** rpt.ReportEnd.
![image](https://user-images.githubusercontent.com/28144855/136359372-8e92497b-40a8-4d37-9e07-1ee384f7d768.png)

but in Spec it is if Project.OperatingEndDate **<** ReportEnd, so Project.OperatingEndDate == ReportEnd is ignored.
![image](https://user-images.githubusercontent.com/28144855/136359075-805de140-2059-426c-affe-d748873af8ec.png)

Could you please take a look?

**Q2.**
Also, in Sample Code Effective Exit Date = null for [p.ProjectType = 13 and hoh.MoveInDate = hx.ExitDate and hx.ExitDate = rpt.ReportEnd] but this scenario is not listed in the updated instructions your provided in your last comment.
![image](https://user-images.githubusercontent.com/28144855/136360454-9bb69a1e-a438-467a-ab65-534d2da98acf.png)

**Q3.**
For "MoveInDate = ExitDate", do we need to use "Effective Move-In Date" or "HMIS Move-In Date"?

Thank you!
Natalie

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley , @kiadso ,

Could you please take a look at Q1, Q2, and Q3? Or is it better to create a separate ticket? Thank you!
