### ISSUE TITLE
HUD CSV Export EnrollmentCoC.csv contains duplicate EnrollmentID & DataCollectionStage

### ISSUE THREAD

**Issue by kiadso** [MollyMcEvilley/LSASampleCode#681]
Hi @bdavis-pcl  

In some internal testing, I found that EnrollmentCoC.csv has two rows for the same EnrollmentID & DataCollectionStage (EnrollmentID 171845).

The CSV Specs don't allow it, and it is causing issues with joining Enrollment to EnrollmentCoC.

Thank you!

**Comment by bdavis-pcl** [comment]
Thanks for bringing this to my attention. I've resolved this duplicate issue in the HMIS CSV sample data set, and I'll close this issue once the new sample data set is available.

**Comment by bdavis-pcl** [comment]
The newest sample data set is currently available on the Vendor HUB.
