### ISSUE TITLE
Some duplicate Enrollments (into same Project on same day) in Enrollment.csv and Exit.csv

### ISSUE THREAD

**Issue by kiadso** [MollyMcEvilley/LSASampleCode#682]
Hi @bdavis-pcl,

For PersonalIDs 73657, 73920, 74479, and 74489, there are enrollments into the same project on the same date. Not sure if these were added intentionally for error testing, but wanted to point them out just in case. 

On PersonalID 73657, one of the enrollments is a same-day entry & exit, so this wouldn't affect the LSA, but the other 3 do have bed nights on both records and the Entry and Exit Dates match within the pair of duplicates.

Only submitting this in case it's not a feature, feel free to leave this if it's ok! :) 

Thank you

**Comment by bdavis-pcl** [comment]
Clean up the HMIS CSV sample data set for HDX has removed some projects as the HDX would not take uploads with those projects listed. This has had a collateral effect of removing these duplicate records. I'll close this issue once the new sample data set is available.

**Comment by bdavis-pcl** [comment]
The newest sample data set is currently available on the Vendor HUB.
