### ISSUE TITLE
HUD CSV Export: Funder.csv missing some records from Project.csv

### ISSUE THREAD

**Issue by kiadso** [MollyMcEvilley/LSASampleCode#683]
Hi @bdavis-pcl,

In the HUD CSV Export specs, it says "For exports that require Funder.csv, there must be at least one record in Funder.csv for each record in Project.csv where ContinuumProject is equal to 1 (Yes)."

The following ProjectIDs do not have a corresponding record in Funder.csv:
1009, 1011, 1012, 1099, 1100, 1101, 1102, 1103, 1492, 1493, 1494, 1495, 1496, 1497, 807, 942, 239, 959, 789, 790, 791, 792

Thanks!

**Comment by kiadso** [comment]
For the last six that I listed, I manufactured Funder records for those for my own purposes- let me know if you are interested in seeing that code. (It's in R though.)

**Comment by bdavis-pcl** [comment]
All projects now have a corresponding record in Funder.csv in the latest copy of the HMIS CSV sample data. 

The newest sample data set is currently available on the Vendor HUB.
