### ISSUE TITLE
HUD CSV Export sample data: Only 6 bed nights, some Enrollments with 0 bed nights

### ISSUE THREAD

**Issue by kiadso** [MollyMcEvilley/LSASampleCode#684]
Hi @bdavis-pcl ,

In the HUD CSV Export specs, it says 

> "Records of bed nights should only be present for `EnrollmentID`s in emergency shelters that use the night-by-night method of tracking shelter utilization. For these shelters, there should be a record of a bed night with a `DateProvided` that corresponds to the `EntryDate` in Enrollment.csv."

In the data for `ProjectID` 882 (the only NBN shelter), there are 37 enrollments, but the only `EnrollmentID` that has any bed nights in Services.csv is 181667, and the `DateProvided` does not correspond to the `EntryDate` in Enrollment.csv. 

Also, the rest of this shelter's Enrollments have 0 bed nights represented in Services where `RecordType` == 200. This would make the other 36 Enrollments not pull into the LSA. @MollyMcEvilley please add any further context if I've missed something! 

Thanks!

**Comment by bdavis-pcl** [comment]
The most recent upload of the HMIS CSV sample data set has resolved this issue. There is now a matching bed night to the EntryDate. Additionally the other 36 Enrollments with 0 bed nights have been removed.

The newest sample data set is currently available on the Vendor HUB.
