### ISSUE TITLE
Section 5.13: ActiveAge period discrepancy between Spec and Sample Code

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#698]
Hi @MollyMcEvilley ,

**Spec:**
`ActiveAge between 21 and 65` is used for:
- Adult(EST/RRH/PSH)
- AHARAdult(EST/RRH/PSH)
![image](https://user-images.githubusercontent.com/28144855/136799789-ee175080-573a-4b86-8eba-9b2fb80bcd7f.png)

**Sample Code:**
`ActiveAge between 18 and 65` is used for:
- Adult(EST/RRH/PSH)
- AHARAdult(EST/RRH/PSH)
![image](https://user-images.githubusercontent.com/28144855/136799818-11d1cb12-a925-42cd-88ae-f4e9a1faef5c.png)

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
No change to either the specs or the sample code -- these evaluate to the same result.
