### ISSUE TITLE
Step 8.3.37: AC3Plus condition is different between Sample Code and Spec

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#705]
Hi @MollyMcEvilley ,

In the spec it is said to use AC3Plus = **3** but in Sample code AC3Plus = **1** is used.

**Sample Code:**
![image](https://user-images.githubusercontent.com/28144855/136977268-2d6cc456-8d93-4293-9621-a82a0bd589e4.png)

**Spec:**
![image](https://user-images.githubusercontent.com/28144855/136977035-ecffc44c-e0a2-4c15-8bd1-b2e156eb3a89.png)

It looks like Spec should be fixed using AC3Plus = **1**.

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Yes, this is a specs issue -- bad copy/paste on my part... Commit forthcoming.

![image](https://user-images.githubusercontent.com/6156815/137154784-677b8c93-5631-458d-8d35-091421747e00.png)
