### ISSUE TITLE
ref_PopHHTypes: Issue with some combinations

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#706]
Hi @MollyMcEvilley,

**1.**
Could you please move `insert into ref_PopHHTypes (PopID, HHType) values (1279,2);` from roq 470 to where all other inserts into  ref_PopHHTypes are done.
![image](https://user-images.githubusercontent.com/28144855/137092167-7e1c7d5b-c641-4bac-8686-2157674f8421.png)

**2.**
Sample Code has row for PopID = 13 and HHType = 99. But there is no such combination in Spec.
**Sample Code:**
![image](https://user-images.githubusercontent.com/28144855/137092605-a495f343-5bc5-4c5d-8bd9-cacb929899e0.png)
**Spec:**
![image](https://user-images.githubusercontent.com/28144855/137092735-df470f7e-3f27-4896-9740-3991b387a018.png)

**3.**
Sample Code has rows for [PopID, HHType]:
- [1178,1]
- [1179,1]
- [1278,2]
- [1279,2]

But in Spec (Please see "Household Type and Populations" section on page 139):
- PopID = **1178** was replaced with **1176**
- PopID = **1179** was replaced with **1177**
- PopID = **1278** was replaced with **1276**
- PopID = **1279** was replaced with **1277**

**Sample Code:**
![image](https://user-images.githubusercontent.com/28144855/137097217-f4db3832-c25a-428e-96c7-260b9e2a0f2e.png)

**Spec:**
![image](https://user-images.githubusercontent.com/28144855/137096437-e8590de9-69c0-488c-988e-2b5af11eb6fb.png)

Best regards,
Natalie

**Comment by nataliesus** [comment]
So if it is decided to update ref_PopHHTypes, then rpt_ref_RowPopulations also should be updated.

**Comment by MollyMcEvilley** [comment]
The specs are correct WRT the age 18-21 and 22-24 populations in AO Youth / AC Parenting Youth households -- the IDs are 1176, 1177, 1276, and 1277 -- and I've made the corrections in the sample code.

WRT veteran household types... I added 99 to the specs.  Commit forthcoming.
