### ISSUE TITLE
Section 8.7: Spec needs corrections

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#710]
Hi!

**1.** Could you please replace "RRHMoveIn in = 0" with "RRHMoveIn = 0"?
![image](https://user-images.githubusercontent.com/28144855/137124539-436268b2-0453-4539-8400-161dc52ad4a5.png)

**2.**  "ReportRow  = Rows 10 and 11" should be replaced with "ReportRow  = Rows 12-16" in the "Target" section.
![image](https://user-images.githubusercontent.com/28144855/137125279-dfb1381d-31a1-4b16-baef-bfc1fccc7dcf.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Thank you!  Commit forthcoming...

![image](https://user-images.githubusercontent.com/6156815/137162547-a1a505c7-dde9-40fb-b13a-f6606721900d.png)
