### ISSUE TITLE
Question about AHARAdultEST, AHARAdultRRH, AHARAdultPSH

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#719]
Hi @MollyMcEvilley ,

You changed column order for AHARAdultEST, AHARAdultRRH, AHARAdultPSH in **tlsa_Person** table.

Should it be done for **lsa_Person** table as well? I think yes, because they are listed this way in LSA Data Dictionary FY2021.xlsx.

Also, there is an issue in the Spec Section 5: there is no [AHARAdultEST] column either under [AdultEST] or under [AHARHoHEST]. The same isssue is with AHARAdultRRH, AHARAdultPSH.

![image](https://user-images.githubusercontent.com/28144855/137277281-b1ab2910-e427-4c24-b136-ddee12a1edcb.png)

Please fix lsa_Person table, and Spec Section 5.

Best regards,
Natalie

**P.S.** Just wonder why in LSA Data Dictionary FY2021.xlsx it was decided to put AHARAdultEST under AdultEST and not under 
AHAREST and AHARHoHEST. It could be consistent because i.e. AHARHoHEST is not under HoHEST
![image](https://user-images.githubusercontent.com/28144855/137280891-ef251775-1af0-469b-ae57-d3576149ba80.png)

**Comment by MollyMcEvilley** [comment]
Yes, thank you!  To answer your question about why... there was, alas, not a whole lot of thought involved -- originally, I think the Dictionary, the sample code, and the specs were all in different orders.  The Dictionary went to the HDX development team right when the specs were released, so the order there wins when there is a discrepancy.
