### ISSUE TITLE
Section 9.2:  issues with ES NbN project stays (Sample Code)

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#724]
Hi @MollyMcEvilley ,

**1.**
According to Spec, **ES NbN project stays** should be selected this way:
- EntryDate <= CohortEnd
- _and_ BedNightDate = CohortStart
- _and_ ExitDate is NULL, or ExitDate > CohortStart
correct?

**Spec:**
![image](https://user-images.githubusercontent.com/28144855/137300987-4cf9d4c3-638c-4f0d-9011-fe5765453274.png)

But in Sample code next restrictions are missing:
- EntryDate <= CohortEnd
- _and_ ExitDate is NULL, or ExitDate > CohortStart

**Sample Code:**
![image](https://user-images.githubusercontent.com/28144855/137301285-268eb3b2-4052-424c-9fc1-c91fa54c254d.png)

Could you please take a look?

**2.** I believe it is not correct to use hmis_Services only once. Instead, there should be 4 hmis_Services left join to check date for each CohortStart. Because CohortStart = bn.DateProvided can be true for one cohort at a time. 
I.e. Client has Project Stay with 3 bed-nights:
- on cd1.CohortStart
- on cd2.CohortStart
- and later that cd2.CohortStart and not on any other CohortStart.
 
So tlsa_Enrollment table will be updated 3 times (per each bed-night). Lets see what will be written into tlsa_Enrollment:
- first time (bn.DateProvided = cd1.CohortStart):
-- PITOctober = 1
-- PITJanuary = 0
-- PITApril = 0
-- PitJuly = 0
- second time (bn.DateProvided = cd2.CohortStart):
-- PITOctober = 0 NOTE: previoulsy store value 1 is rewritten with 0
-- PITJanuary = 1
-- PITApril = 0
-- PitJuly = 0
- thirt time (bn.DateProvided != anyCohortStart):
-- PITOctober = 0
-- PITJanuary = 0 NOTE: previoulsy store value 1 is rewritten with 0
-- PITApril = 0
-- PitJuly = 0

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Commit forthcoming:

Q1:  Added relevant EntryDate and ExitDate criteria to 9.2.2.
Q2:  You are correct!  Modified the query to correct.

    update n
	set n.PITOctober = PIT.PITOctober
		, n.PITJanuary = PIT.PITJanuary
		, n.PITApril = PIT.PITApril
		, n.PITJuly = PIT.PITJuly
	from tlsa_Enrollment n
	inner join (select nbn.EnrollmentID 
		  , PITOctober = max(case when cd1.Cohort is null then 0 else 1 end)
		  , PITJanuary = max(case when cd2.Cohort is null then 0 else 1 end)
		  , PITApril = max(case when cd3.Cohort is null then 0 else 1 end)
		  , PITJuly = max(case when cd4.Cohort is null then 0 else 1 end)
		from tlsa_Enrollment nbn
		inner join tlsa_CohortDates cd on cd.CohortEnd >= nbn.EntryDate 
			and (nbn.ExitDate is NULL or nbn.ExitDate > cd.CohortStart) 
		inner join hmis_Services bn on bn.EnrollmentID = nbn.EnrollmentID
			and nbn.EntryDate <= bn.DateProvided
			and (nbn.ExitDate is NULL or nbn.ExitDate > bn.DateProvided)
		left outer join tlsa_CohortDates cd1 on cd1.CohortStart = bn.DateProvided and cd1.Cohort = 10 
		left outer join tlsa_CohortDates cd2 on cd2.CohortStart = bn.DateProvided and cd2.Cohort = 11 
		left outer join tlsa_CohortDates cd3 on cd3.CohortStart = bn.DateProvided and cd3.Cohort = 12 
		left outer join tlsa_CohortDates cd4 on cd4.CohortStart = bn.DateProvided and cd4.Cohort = 13 
		where nbn.LSAProjectType = 1
			and nbn.AHAR = 1
		group by nbn.EnrollmentID) PIT on PIT.EnrollmentID = n.EnrollmentID

**Comment by MollyMcEvilley** [comment]
Resolved in commit  f54b07b
