### ISSUE TITLE
Section 9.4: issue in the Spec

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#726]
Hi @MollyMcEvilley,

**1.**
It looks like a copy/paste issue in Universe and ProjectID section. "Report rows 53 and 54" should be replaced with  "Report row 55"
![image](https://user-images.githubusercontent.com/28144855/137312518-968ab421-f14c-49a7-8c4f-90fc662d2bcb.png)

**2.**
Please fix ProjectType for Universe = 15:
![image](https://user-images.githubusercontent.com/28144855/137313284-23b2e2d1-77fd-4bda-98e5-94f8d530cf46.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Thank you!
