### ISSUE TITLE
Section 9.4: question about PopId = 51 and 52

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#730]
Hi @MollyMcEvilley ,

Sample Code doesn't have `tlsa_Enrollment.RelationshipToHoH = 1` restriction for PopId = 51 and 52:
![image](https://user-images.githubusercontent.com/28144855/137335400-f8b10f7b-012e-40b4-9cca-b754bb7ef0b5.png)

I wonder if `tlsa_Enrollment.RelationshipToHoH = 1` should also be removed from Spec?
![image](https://user-images.githubusercontent.com/28144855/137335407-90515f2e-aff9-4991-adcf-a3af4c781ed3.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
That's a good point -- it's redundant to **HHParent**.  Commit forthcoming with the following change:
![image](https://user-images.githubusercontent.com/6156815/137348132-f3c47873-5734-45b2-9f3e-22c49f348b33.png)
