### ISSUE TITLE
Section 9.2: corrections for the Spec

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#734]
Hi @MollyMcEvilley ,

Could you please update Logic section using "LSAProjectType" to be consistent with "Source" section?

![image](https://user-images.githubusercontent.com/28144855/137714991-364cb68e-a0f5-4abe-96ea-fc2f331fa8d9.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Done... commit forthcoming.
