### ISSUE TITLE
5.4 - schema should be fixed

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#744]
Hi @MollyMcEvilley ,

Last year this issue (#522) was closed without any resolution. But it is still in Spec. Could you please take a look at it now?

It looks like "hmis_Enrollment" and “hmis_HealthAndDV” should be removed from the schema as they are not used and not described in Source table:
![image](https://user-images.githubusercontent.com/28144855/138037745-292bf777-8b7c-489f-8fea-78bf820fc799.png)

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Commit forthcoming -- thank you!
