### ISSUE TITLE
New sections 7.4 - 7.8: Schema is missing (Spec)

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#757]
Hi @MollyMcEvilley ,

This year new sections 7.4-7.8 were added. Right after the section title it is Source table. But all other LSA sectiions do have Shema before the Source table. i.e. section 7.9:
![image](https://user-images.githubusercontent.com/28144855/138268746-d3968c10-2d66-4bf4-9d05-19529e137dfd.png)

I wonder if there are any plans to add Schema for sections 7.4-7.8 to be consistent with the rest of the Spec?

Best regards,
Natalie

**Comment by kiadso** [comment]
Thanks Natalie- commit forthcoming!
