### ISSUE TITLE
Step 7.4.2: missing parentheses

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#759]
Hi @MollyMcEvilley ,

I believe highlighted part should be in parentheses
![image](https://user-images.githubusercontent.com/28144855/138275046-ca5a622b-18c1-4390-bd07-86617d5bb03b.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
You are absolutely correct!  Thank you.
