### ISSUE TITLE
Section 7.5: Spec corrections

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#764]
Hi @MollyMcEvilley,

![image](https://user-images.githubusercontent.com/28144855/138289423-db92fefd-26d6-4fa8-9ed8-01f6a9054d09.png)

1. Schema is missing
2. `tlsa_ExitHoHAdult.CHTime` is missing
3. `tlsa_Enrollment.CH` is not used in the Logic section. Should it be removed?
4. I think the hightlighted section can be completely removed from the spec because This year LSA was programmed the way that MoveInDate = ExitDate is no longer possible.
![image](https://user-images.githubusercontent.com/28144855/138290708-9625573f-ae7e-45da-832e-8697cbe24833.png)
5. in case point 4 makes sense, then `[Date] < tlsa_Enrollment.ExitDate` can be moved from the ProjectType restriction to the main condition.

Thank you!
Natalie

**Comment by kiadso** [comment]
thanks Natalie! commit imminent!
