### ISSUE TITLE
9.3 LSA Code issue

### ISSUE THREAD

**Issue by 2008zjqc** [MollyMcEvilley/LSASampleCode#767]
In 9.3 there is an issue with the following code:
count(distinct hhid.HoHID + hhid.ActiveHHType)

HoHID is of data type varchar
and
ActiveHHType is of data type int

This piece need additional cast we think. Thanks.

Best,
Chen

**Comment by MollyMcEvilley** [comment]
Hi Chen, 

Yes, thank you!  Query 9.3.1 has been updated to cast the ActiveHHType as a varchar.
