### ISSUE TITLE
LSAPerson.csv - Upload Error - AC3PlusEST/AC3PlusPSH/AC3PlusRRH 

### ISSUE THREAD

**Issue by TanyaPieterse** [MollyMcEvilley/LSASampleCode#773]
Hi Molly,

Firstly, thank you for the Sample Code!  My code is reflecting your most recent changes in GitHUB.

I tested a LSA upload and received these errors that rejected the file: 
IDType Description Column 
invalid_value -1 AC3PlusEST 
invalid_value -1 AC3PlusPSH
invalid_value -1 AC3PlusRRH

According to the GitHUB LSA Dictionary these 3 fields use list 5 which has the values 0/No and 1/Yes.  The Programming Specifications also indicate it should be set to a 0 or 1.  In the Sample Code step 5.13 it is set to a 0 or a 1; but in the update statements directly afterwards, the 3 fields are set to -1 if they are null.  Should this instead me set to a 0?

Thank you!
Tanya Pieterse
Bell Data Systems, Inc.

**Comment by MollyMcEvilley** [comment]
There is an update to the dictionary forthcoming and the HDX team will integrate the correction -- -1 is a valid value.
![image](https://user-images.githubusercontent.com/6156815/139120010-8cb03c6e-e5bb-42f7-8db1-be7946c2a96a.png)

**Comment by TanyaPieterse** [comment]
Thanks Molly!

**Comment by MollyMcEvilley** [comment]
Status update:  Still an issue in HDX 2.0.
