### ISSUE TITLE
Follow up for Issue #771 about lowercase table/column names

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#774]
Hi @kcourtneywellsky and @MollyMcEvilley ,

Follow-up for #771.

We don't have problem with case-sensitive table/column names, but if it is important for you - there are several more places to fix:
- tlsa_hhid (instead of tlsa_HHID)
![image](https://user-images.githubusercontent.com/28144855/139211079-1570d6ab-c807-42d8-9e8d-a14d4f407d61.png)
- ahar (instead of AHAR)
![image](https://user-images.githubusercontent.com/28144855/139211132-dc897919-e0b3-4d8f-8f4c-09ea2dd18f54.png)
- popID (instead of popID)
![image](https://user-images.githubusercontent.com/28144855/139211191-25c198c0-a3e6-473e-aba0-17b71440c00c.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Thank you!
