### ISSUE TITLE
Section 7.4 - question about logic

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#783]
Hi @MollyMcEvilley , @kiadso ,

It is not clear for me why section 7.4 is programmed in two steps: 7.4.1 and 7.4.2.

In Step 7.4.1 HHChronic = 0 for scenarios that Spec use for LastActive.

Spec doesn't have HHChronic = 0 programming logic in Section 7.4, but in LastActive it refers to HHChronic = 0 but only in contest of LastActive, not the entire tlsa_ExitHoHAdult.

![image](https://user-images.githubusercontent.com/28144855/139254213-7ee3933c-1d52-4929-90ec-243df06db8ed.png)

![image](https://user-images.githubusercontent.com/28144855/139266349-6b55a59d-f7c1-47eb-9b19-4b2b78ef4fe4.png)

Please advise.

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Thank you for pointing this out -- the information about which HHIDs are excluded from the CH determination makes more sense as part of the Record Selection section, so I'm making revisions to both the specs and the sample code.  This won't alter the output, but it does make things clearer than the way I had it set up before.

![image](https://user-images.githubusercontent.com/6156815/139915928-b7fa2036-2b33-4852-875d-4c122d22a417.png)
![image](https://user-images.githubusercontent.com/6156815/139916055-75890585-93eb-44e9-8048-45e433e49c30.png)
