### ISSUE TITLE
Follow-up for #738: Steps 9.5.1, 9.5.3, 9.5.7: hmis_Services restrictions question

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#784]
Hi @MollyMcEvilley ,

Follow-up for #738:

![image](https://user-images.githubusercontent.com/28144855/139261038-ba032224-14f8-4519-a0c5-356c73ce853b.png)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
I am sorry I missed those!
