### ISSUE TITLE
Section 7.5: "active cohort" question

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#786]
Hi @MollyMcEvilley , @kiadso ,

"active cohort" is mentioned in Section 7.5 in the Spec.

![image](https://user-images.githubusercontent.com/28144855/139276837-6065f192-c498-4e03-979b-7c7ae156ad1d.png)

But there is no "active cohort" logic either in Logic section (Spec) or in Step 7.5 (Sample Code).

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
The sample code addresses this by deleting the records created in 5.7.
