### ISSUE TITLE
Step 7.5: latest LastActive issue in Sample Code

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#787]
Hi @MollyMcEvilley,

With last update for Step 7.5 not all nesessary changes were made. Please compare

**Spec**
![image](https://user-images.githubusercontent.com/28144855/139278457-7a609914-2646-4613-9137-744ae10cda8b.png)

**Sample Code**
![image](https://user-images.githubusercontent.com/28144855/139278330-84831c06-b929-47ad-890d-027811004ea7.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Thank you!
