### ISSUE TITLE
Step 10.3 - Issue in Group By

### ISSUE THREAD

**Issue by TanyaPieterse** [MollyMcEvilley/LSASampleCode#788]
Hi Molly,

 I just implemented your most recent changes.  The 'Group By' in Step 10.3 had an issue and had to be changed to match the select statement before the SQL would run.  

Thanks!

**Comment by bdavis-pcl** [comment]
Noticed the same error, specifically pointed at lines 58 - 60 in section 10.3 of the sample code.

`group by case when hx.ExitDate is null then 60
			else 61 end 
		, p.ProjectID, cd.ReportID`
		
Doesn't match the Select statement above it

**Comment by nataliesus** [comment]
Hi @TanyaPieterse , @bdavis-pcl ,

This issue is one of two that were already reported in #775

**Comment by MollyMcEvilley** [comment]
Thank you!  Closed by [this commit](https://github.com/HMIS/LSASampleCode/commit/12ea480b3caf2b9427b1c2bbbb0bc39f7b7b6f08).
![image](https://user-images.githubusercontent.com/6156815/139952901-1a573bfc-1ea0-4240-86ab-9b331734c534.png)
