### ISSUE TITLE
Step 7.5: Sample code uses EntryDate restriction not listed in the Spec

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#789]
Hi @MollyMcEvilley , @kiadso ,

Spec uses `EntryDate < latest LastActive` restriction that is not listed in the Spec. Could you please take a look?

![image](https://user-images.githubusercontent.com/28144855/139415124-4b95598e-51fd-4ca9-9e5f-318c6ac2a811.png)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Corrected this to incorporate the earliest CHStart and latest LastActive criteria into to join to ref_Calendar.
![image](https://user-images.githubusercontent.com/6156815/139952371-d9b0bd9d-2e6f-437d-9f68-89f3efa049c2.png)
