### ISSUE TITLE
Step 7.6.2 - issue with bed-night services (Sample Code)

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#790]
Hi @MollyMcEvilley,

Sample Code uses hmis_Services for HoH only, but the whole report was reworked to look at each project stay bed-nights, not for HoH only. Could you please take a look?
![image](https://user-images.githubusercontent.com/28144855/139429363-290ae114-c13c-47a9-918c-b8214fff850e.png)

If tlsa_HHID still should be used, then I think spec should be updated.

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Yikes!  Thank you -- commit forthcoming!

![image](https://user-images.githubusercontent.com/6156815/139953178-c2f98ad9-e2d2-48e4-a91f-3002f6375c91.png)
