### ISSUE TITLE
Section 7.6 - question about "EntryDate > CHStart" restriction (Spec)

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#791]
Hi @kiadso ,

`earliest CHStart` is used in "Enrollment in Entry/Exit ES or SH" section.

I wonder if `earliest CHStart` should also be used in "ES/SH/Street Dates from 3.917 Living Situation" section to be consistent.

![image](https://user-images.githubusercontent.com/28144855/139433795-d969fbc4-181b-4ad1-b0ca-25d3028196e3.png)

Please advise.

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Yes, fixing this!
