### ISSUE TITLE
HDX 2.0 Testing: mismatch between  site error description and Flags File

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#795]
Hi @kiadso, @cwanska.

Not sure if it is a question for you, so please re-assign if needed.

I've uploaded LSA report to https://testing.hudhdx2.info/home 

After a while, three flags appeared on Errors/Warnings tab:
![image](https://user-images.githubusercontent.com/28144855/139679332-9628e566-e297-4325-8e58-5b19a5b47405.png)

I am investigating because I think it is a problem on our side, but I noticed that Flag 757 sub-flags 8 and 11 do not match the identical flags in `Flag List_FY2021.xlsx` and I believe it is an issue in HDX 2.0.

HDX 2.0:
- Flags J757-8 and J757-11 are both about ES project stays;
![image](https://user-images.githubusercontent.com/28144855/139679729-099315e8-3622-462c-aece-fba315cfbf7b.png)

Flag List_FY2021.xlsx:
- 757-8 flag is about SH project stay:
`Adult-Only (AO) households in SH: The sum of the project-level counts of bed nights among all SH projects is less than the unduplicated CoC-wide SH count of bed nights for the following: households served during the current report period.`
- 757-11 flag is about PSH project stay:
`Adult-Only (AO) households in PSH: The sum of the project-level counts of bed nights among all PSH projects is less than the unduplicated CoC-wide PSH count of bed nights for the following: households served during the current report period.`

Could you please take a look?

Also, Flag 757-24 has a discrepancy in Household type:
![image](https://user-images.githubusercontent.com/28144855/139681020-2d0cf9fe-0327-40ce-b6cf-ccf83f56a93a.png)
**vs**
`Adult-Only (AO) households in ES/SH/TH: The sum of the project-level counts of bed nights among all ES/SH/TH projects is less than the unduplicated CoC-wide ES/SH/TH count of bed nights for the following: youth-only households (where the oldest adult is 22-24) served during the current report period.`
Please notice there is "**youth-only households (where the oldest adult is 22-24)**" restriction in `Flag List_FY2021.xlsx`.

Also, is it possible to include formulas in `Flag List_FY2021.xlsx`? I believe there were some formulas in the Flags File last year so it can help finding the problem faster.

Thank you!
Natalie

**Comment by kiadso** [comment]
Thank you Natalie, I have submitted this to dev and will update Friday.

**Comment by kiadso** [comment]
Hi Natalie,

I have checked these flags and while I'm not seeing 757-8 anymore, the other two (757-11 and 757-24) are both showing as expected and as you indicated in this question. Let me know if you are still seeing the wrong household types and project types for these (or any other) flags. This was addressed by the flag team.
