### ISSUE TITLE
Follow-up for #672: lsa_Organization table: OrganizationName and OrganizationCommonName have wrong size

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#796]
Hi @MollyMcEvilley , @kiadso ,

This is a follow-up ticket for #672:

I just wonder if OrganizationName with length > 50 symbols will be reported in flags because of
![image](https://user-images.githubusercontent.com/28144855/140048519-e3ab12f3-0ea6-41a0-b63a-04bc4dcbdbe9.png)

Maybe you still need to fix max length for OrganizationName as it was originally requested?

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Sorry -- I should have changed this in the temp tables when you first submitted... It drives me a little nuts that the ProjectName column was changed to 100 in the HMIS CSV but ProjectCommonName, OrganizationName, and OrganizationCommonName were all left at 50...  changing it now. 

Also correcting the DataType for Organization.VictimServiceProvider in the LSA Data Dictionary to int.
