### ISSUE TITLE
Funder.csv in LSA CSV Export.zip contains Funder with EndDate before ReportStart in LSAReport.csv

### ISSUE THREAD

**Issue by kcourtneywellsky** [MollyMcEvilley/LSASampleCode#797]
The Funder.csv file located in the "LSA CSV Export.zip" in the "Sample Data Output" directory contains a Funder record with an EndDate that is before the ReportStart specified in LSAReport.csv.

In Funder.csv, FunderID 1902 for ProjectID 792 has an EndDate of 2015-12-31.

The report criteria in LSAReport,csv show that ReportStart is 2020-10-01.

However, Funder.csv is generated from table lsa_Funder. Sample code script "04_02 to 04_06 Get Other PDDEs.sql" shows that a funder record must have an EndDate on or after the ReportStart date in lsa_Report to be inserted into lsa_Funder.

insert into lsa_Funder	
		 (FunderID, ProjectID, Funder, OtherFunder
		, StartDate, EndDate
		, DateCreated, DateUpdated, ExportID)
	select distinct hf.FunderID, hf.ProjectID, hf.Funder, hf.OtherFunder
		, format(hf.StartDate, 'yyyy-MM-dd')
		, case when hf.EndDate is not null then format(hf.EndDate, 'yyyy-MM-dd') else null end
		, format(hf.DateCreated, 'yyyy-MM-dd HH:mm:ss')
		, format(hf.DateUpdated, 'yyyy-MM-dd HH:mm:ss')
		, lp.ExportID
	from hmis_Funder hf
	inner join lsa_Project lp on lp.ProjectID = hf.ProjectID
	inner join lsa_Report rpt on cast(lp.ExportID as int) = rpt.ReportID
	where hf.DateDeleted is null 
		**and (hf.EndDate is null 
			 or	(hf.EndDate >= rpt.ReportStart
				 and hf.EndDate > hf.StartDate)**
			)

Running the Sample Code scripts using the test kit data in "LSA HMIS CSV Export FY2022.zip" should result in this Funder being excluded from the Funder.csv file.

**Comment by bdavis-pcl** [comment]
My report was not pulling the lsa_funder table but the hmis_funder table instead. That has been fixed with this most recent report. Thanks for bringing this to my attention.
