### ISSUE TITLE
Section 7.5: new issue after changes related to #787

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#798]
Hi @MollyMcEvilley ,

It looks like a new issue appeared after changes for #787.

Spec has `ExitDate > the earliest CHStart` restriction that is now missing in the Sample Code.

![image](https://user-images.githubusercontent.com/28144855/140308203-53acf88e-47b8-43e9-846d-dda64c6c4ca9.png)

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
This is covered by the fact that cal.theDate has to be between the earliest CHStart and the latest LastActive and also has to be between Entry/MoveInDate and ExitDate...
