### ISSUE TITLE
Section 7.6: discrepancy between Spec and Sample Code after last changes

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#799]
Hi @MollyMcEvilley ,

In one of your last commits, ` ExitDate > than the earliest CHStart and EntryDate <= the latest LastActive` restriction was removed from the Sample Code but it is still in the Spec. Could you please take a look?

**Spec:**
![image](https://user-images.githubusercontent.com/28144855/140312140-9d6d5ff6-2740-4116-b250-9ff734072194.png)

Shouldn't  ` ExitDate > than the earliest CHStart and EntryDate <= the latest LastActive` restriction be added to steps:
- 7.6.1
- 7.6.2
- 7.6.3

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
This is covered by the joins to ref_Calendar -- the requirement that cal.theDate must be between the earliest CHStart and the latest LastActive effectively imposes this requirement.
