### ISSUE TITLE
Section 7.8 - question about "CHTime is NULL"

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#800]
Hi @MollyMcEvilley ,

Both sections 7,5 and 7,6 have "not set in step 7.4 (i.e., where **CHTime is NULL**)" condition that is programmed as `WHERE CHTime is NULL` in Sample Code.

I am a bit confused because in section 7.8 there is "not already set in step 7.4" text but " (i.e., where **CHTime is NULL**)" text is missing. So I wonder why "**CHTime is NULL**" is not included in the Spec Section 7.8, and also was not included in Sample Code step 7.8.1 but was included in step 7.8.2.
![image](https://user-images.githubusercontent.com/28144855/140318398-760c74a6-c184-46db-a01d-d8e1d598fe8d.png)

Please advise.

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Added the parenthetical to 7.8!
![image](https://user-images.githubusercontent.com/6156815/140436499-bda8fbae-453b-4369-978f-f12a8546c9a9.png)

Also, I noticed that there was an incomplete sentence in your screenshot of 7.5, so I completed it:
![image](https://user-images.githubusercontent.com/6156815/140436644-f5a8ce12-f3e5-4d93-8c75-7740d3b7118d.png)
