### ISSUE TITLE
Step 7.8.2 - episode discrepancy between Sample Code and Spec

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#801]
Hi @MollyMcEvilley,

**Q1:**
Could you please check spec?
-  "LastA**a**ctive" has extra "a"
-  is it correct to use "LastInactive" for "Set CHTime = 365 and CHTimeStatus = 3". Shouldn't it be "LastActive"?
![image](https://user-images.githubusercontent.com/28144855/140322818-bb27a05b-8a65-4c58-aac3-ea2a9ad7e5e9.png)

**Q2:**
Spec says to use "**episodeStart** <= LastActive" restriction, but Sample Code uses "**episodeEnd** <= LastActive". Could you please take a look?

**Spec:**
![image](https://user-images.githubusercontent.com/28144855/140320676-62bde4dc-4315-4ede-baff-2fb88b670844.png)

**Sample Code:**
![image](https://user-images.githubusercontent.com/28144855/140320963-d932b78a-300c-480b-a685-88d0f178b3a8.png)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Q1:  Yes, should be **LastActive** -- thank you!
Q2:  The logic in the specs was overly prescriptive -- the requirement is just that the episodes overlap with the **CHStart**-**LastActive** period, which the logic in the sample code does enforce -- so I updated the description in the specs.
![image](https://user-images.githubusercontent.com/6156815/140437671-4de34ef1-aeb7-4350-a4a1-7d805f938545.png)
