### ISSUE TITLE
Step 7.8.2: CHTime and CHTimeStatus possible issues in Sample Code

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#802]
Hi @MollyMcEvilley ,

**1.**
According to the Spec, **CHTimeStatus** should be NULL for scenario when CHTime <= 270 (points 4 and 5).
But in Sample Code CHTimeStatus is 3.

**2.**
According to the Spec, **CHTime** should be NULL if [COUNT of ch_Include.ESSHStreetDates] < 270 (point 5).
But in Sample Code CHTime is 0.
![image](https://user-images.githubusercontent.com/28144855/140328738-8a634242-1905-4cca-ae02-efbf80c928ae.png)

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
This won't impact output, but I am updating the sample code to 'else NULL' in both of the highlighted spots.
