### ISSUE TITLE
https://testing.hudhdx2.info/ generates 10,379 flag errors 

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#805]
Hi @MollyMcEvilley ,

Is there any flag system reporting error on https://testing.hudhdx2.info?

I submitted LSA archive that is provided with Sample Code and there are 10,379 flags reported.

LSA report: https://github.com/HMIS/LSASampleCode/blob/master/Sample%20Data%20Output/LSA%20CSV%20Export.zip

Received Flags:
![image](https://user-images.githubusercontent.com/28144855/140527845-870a0d07-5fde-4964-8a46-a8ff0f3354ac.png)

I just feel we do not have enough time to find and fix actual flags for our LSA implementation before Customers start using the report on the announced date: November 15th.

Best regards.
Natalie

P.S. having Excel flags file for a submittion was really helpful for us so Customers can provide all their flags to report developers for investigation. It will be hard for Customer to do it this year without ability to export flags file...

**Comment by MichelleNevius** [comment]
Hi Natalie, I'd like to amplify (not diminish) your concerns about the timing--but I believe the announced date is not November 15th for our customers, but rather November 22nd.  Still--very soon!

**Comment by MollyMcEvilley** [comment]
They are currently a work in progress — I know the HDX team is working very hard to get them working properly.  We will give more info on the progress there as soon as we have it. I didn’t see a way to export the errors — or to figure out row numbers in flags that say “the following row”.

**Comment by kiadso** [comment]
The Flag Export button is working now and we encourage vendors to check their flags and enter Issues here if there are specific concerns.
