### ISSUE TITLE
Step 7.4.2: potential issue in Sample Code after last update

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#806]
Hi @MollyMcEvilley ,

**1.**
I wonder if `n.PersonalID = hoha.PersonalID` was omitted on purpose.

![image](https://user-images.githubusercontent.com/28144855/140532831-282051ff-79c5-41fa-b345-1539d57a2cab.png)

Please advise.

**2.**
In the spec it is said that "EntryDate > [**LastActive** – 1 year]" and I can see it in Sample code.
But Sample Code has also "**hn.EntryDate > dateadd(yyyy, -1, n.ExitDate)**" I cannot find in Spec.

![image](https://user-images.githubusercontent.com/28144855/140541676-3a0fadb2-5e60-49c8-b881-05cb560dc0a1.png)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
1.  Yes -- as long as any (adult or HoH) household member is going to result in **HHChronic** = 1, there's no need to go through the process in 7.5-7.8 for any of them.  I added a clarifying sentence in the specs (highlighted in pink below).
2. I added a note to the specs that the HMIS _EntryDate_ must match the tlsa_Enrollment.**EntryDate** (highlighted in yellow below) and am updating the code accordingly.  We don't want to rely on 3.917 data when we can't be sure exactly when it was collected (i.e., is the _EntryDate_ correct and they just forgot to record a bednight or was the _EntryDate_ a typo?).

![image](https://user-images.githubusercontent.com/6156815/141326384-0e1efed5-4a16-4f6d-afe1-cfd16ccf5edc.png)
