### ISSUE TITLE
Spec: title page needs update

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#813]
Hi @MollyMcEvilley ,

There is "Version 1.0 August 2021" on the title page of LSA Programming Specifications FY2021.docx.

![image](https://user-images.githubusercontent.com/28144855/140711905-b01a35a3-aa77-4a23-b7d9-ac04a7cb4e26.png)

Could you please take a look?

Thank you,
Natalie

P.S. Also, maybe you can take a look at Revisin History page as well?
![image](https://user-images.githubusercontent.com/28144855/140712219-783647ca-5cf7-43c5-975d-26c8c46a5ed4.png)

**Comment by MollyMcEvilley** [comment]
I don't know when this is going to be posted to the HUD Exchange, but the version/date will be sorted out when it's being finalized...
