### ISSUE TITLE
Inconsistency btw CSV dataset and LSA Export Results

### ISSUE THREAD

**Issue by 2008zjqc** [MollyMcEvilley/LSASampleCode#814]
Hi Molly,
We got a cut of everything (HMIS CSV dataset and LSA sample code and LSA export result) end of last Friday. After applied updated sample code, we found there are big discrepancy btw LSA sample report output and our output mainly due to the datasets been used to get out the sample result may different from the one provided here. 
i.e. In HMIS CSV project, there is one project ID 240 (total there are 19 projects). However in the LSA result, when the places used lsa_project (total 18, missing project ID 240) and used hmis_project (total 19). Those are causing numbers are different place to place. 
Please take a look. If possible, could you please re-release dataset and export result with the current LSA query?
Thanks.
Best,
Chen

**Comment by jbloescw** [comment]
Looks like I'm seeing the same thing.  I'm comparing my tlsa_HHID to the sample export and I'm now producing more records.  I was spot on before and since that section hasn't changed in a month it makes sense that the export needs to be ran with the updated sample code.

**Comment by kcourtneywellsky** [comment]
I also ran into the problem mentioned here. The HMIS test data has project ID 240, but LSA Export's lsa_Project does not contain that project.

**Comment by bdavis-pcl** [comment]
The most recent HMIS CSV upload has project 240, as does the LSA report. Thanks for bring this to my attention, I can only assume I forgot to include it previously.
