### ISSUE TITLE
Follow-up for #809 about CHTimeStatus (Step 7.8.2)

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#817]
Hi @MollyMcEvilley ,

I wonder if you can use 
```
ha.CHTimeStatus =
         CASE
            WHEN time_sum.count_days < 365 THEN NULL
            WHEN time_sum.count_eps >= 4 THEN 2
            ELSE 3
         END
```
that follows the spec instead of the most recent Sample Code changes
![image](https://user-images.githubusercontent.com/28144855/141470293-9c1a05bc-9d52-4187-aa3c-8a8494024c2b.png)
because there is no way to get to `else NULL` rule but `CHTime = 270 AND CHTimeStatus = NULL` scenario must be possible and is described in the spec:
![image](https://user-images.githubusercontent.com/28144855/141470723-b2ff74f0-25bf-49b4-8792-0caf3779086f.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
I think we're okay here -- the intention with the note that **CHTimeStatus** is not applicable when **CHTime** = 270 is to convey that it doesn't matter what **CHTimeStatus** is set to -- it isn't relevant to the logic in subsequent sections.
