### ISSUE TITLE
Follow-up for #791: Section 7.6 - question about "EntryDate > CHStart" restriction

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#821]
Hi @MollyMcEvilley ,

Under #791 you made needed changes, but we overlooked to update step 7.6.3.

What is about `EntryDate > earliest CHStart` restriction used in the Spec? Sample Code uses `EntryDate > CHStart` but not "earliest" CHStart.

![image](https://user-images.githubusercontent.com/28144855/141774503-399dae95-907b-4c13-a1c3-3ed1a0781934.png)

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Since we're inserting distinct dates by person (vs. by person and cohort), the join to tlsa_Enrollment will pick up all enrollments with entry dates after the earliest CHStart in tlsa_ExitHoHAdult.
