### ISSUE TITLE
Section 8.3 - subpopulation discrepancy between Spec and Sample Code

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#822]
Hi @MollyMcEvilley ,

Could you please confirm "Parent Populations" column values for IDs:
- 34 (ref_RowPopulations table does not have a record for Pop1=15 for Pop2=34 that is included in the Spec)
- 35 (ref_RowPopulations table does not have a record for Pop1=15 for Pop2=35 that is included in the Spec)
- 36 (ref_RowPopulations table does not have a record for Pop1=[13 or 15] for Pop2=36 that is included in the Spec)

Numbers in red are what we actually have in ref_RowPopulations table:
![image](https://user-images.githubusercontent.com/28144855/142408684-d052afd7-b883-421e-bde6-4f4376d35fa0.png)

It looks like either Spec of Sample Code should be updated.

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
You are an absolute genius of cross-checking / validation and I can't thank you enough for your contributions.  
Commit forthcoming.
