### ISSUE TITLE
HUDX test site: replace LSA report file error

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#823]
Hi @MollyMcEvilley ,

Just in case:
https://testing.hudhdx2.info/module/lsa/uploads/1203

![image](https://user-images.githubusercontent.com/28144855/142412137-b588b5a7-0ae6-4a03-966c-fdb06102b519.png)

**Comment by kiadso** [comment]
I can recreate this problem on that particular dataset, but whenever I try to recreate it on another dataset, I'm able to replace my file just fine. Is it possible this particular dataset is just corrupted but otherwise the site is working as intended?

**Comment by nataliesus** [comment]
Thank you for taking a look, @kiadso ! I will close this ticket.

**Comment by nataliesus** [comment]
Hi @kiadso ,

I have the same issue again. Now it is with https://testing.hudhdx2.info/module/lsa/uploads/1324

![image](https://user-images.githubusercontent.com/28144855/145028527-b59c6806-6ee4-49d3-99bb-892dd86bfa6c.png)

Maybe for `SELECT COUNT(*) ...` sql query  `name` parameter should be compared with value after addslashes() applied? Because now query looks like an sql injection.

Best regards,
Natalie
