### ISSUE TITLE
HUDX Test site: closing flag pop-up, active page is set to first

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#824]
Hi @MollyMcEvilley ,

Is it possible to stay on the same page (not first, in my scenario it is the very last page with flags) after flag pop-up is closed? Now it redirects to the first page.
![image](https://user-images.githubusercontent.com/28144855/142412865-91664ed9-535b-422d-823d-d1000e1384d6.png)

Thank you!
Natlaie

**Comment by kiadso** [comment]
This has been fixed- thank you for the suggestion!
