### ISSUE TITLE
Step 8.4-8.7 - Add line

### ISSUE THREAD

**Issue by TanyaPieterse** [MollyMcEvilley/LSASampleCode#826]
Hi Molly,
Just a small oversight in Step 8.4-8.7...
We need to add the delete line so that the table starts with 0 records each time, similar to the other tables in the Code.

/*
	8.4-8.7 Average Days from LSAHousehold 
 */
	delete from lsa_Calculated

Thanks!

**Comment by MollyMcEvilley** [comment]
Thank you!  Closed by [this commit](https://github.com/HMIS/LSASampleCode/commit/a98894f6d72d384dee935988eec7f3ce1782b614#diff-b8320bfc2a71548e3010205655cd2f323b4c9e43b7259c6e5585807b70a3f940).

![image](https://user-images.githubusercontent.com/6156815/143302489-8b9c0ad9-2ddf-4c25-8f01-56b54eaedc21.png)
