### ISSUE TITLE
Step 9.4.1: subpopulations are not included in Sample Code

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#828]
Hi @MollyMcEvilley ,

We have some doubts about 9.4.1.

In Spec it is said:
![image](https://user-images.githubusercontent.com/28144855/142639934-9bd40fef-8ae1-404c-aa7a-3e75dcdf019b.png)

In Sample Code subpopulation 5055 is never selected. 
![image](https://user-images.githubusercontent.com/28144855/142640598-9282ea04-76d7-46c9-a486-7720459b1765.png)

I used LEFT JOIN for ref_PopHHTypes to show that Population = 5055 is never selected because of INNER JOIN in the Sample Code
```
  SELECT rv.*, rp.*, ph.*
    FROM ref_RowValues AS rv
    JOIN ref_RowPopulations AS rp ON ( rv.RowID BETWEEN rp.RowMin AND rp.RowMax )
    LEFT JOIN ref_PopHHTypes AS ph ON ( rp.PopID = ph.PopID )
   WHERE rv.RowID = 55
     AND ( rv.Universe = 10 OR rp.ByProject IS NULL )
```
![image](https://user-images.githubusercontent.com/28144855/142640203-c8f100b8-dfd6-49e0-9ccb-012d5e3a2732.png)

`ref_PopHHTypes` table doesn't have PopID for combined popupaltion/subpopulation (i.e.5055) so none of subpopulations will be selected. Maybe `rp.PopID = ph.PopID` should be replaced with something else?

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Thank you!  

![image](https://user-images.githubusercontent.com/6156815/143305106-2a4c6401-524b-4a15-9214-7cd8bdfbe2b7.png)

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

Could you please also check 8.4 and 8.9 sections that should use subpopulation logic as well?

Thank you!
Natalie

**Comment by nataliesus** [comment]
Just in case, to avoid overlooking what else should be changed for pop/subpop combinations, I simply included pop/subpop in ref_PopHHTypes and do not use `ph2` in sections 8 and 9
```
INSERT INTO ref_PopHHTypes ( PopID, HHType )
SELECT DISTINCT rp.PopID, ph1.HHType
  FROM ref_RowPopulations AS rp
  JOIN ref_PopHHTypes AS ph1 ON ( rp.Pop1 = ph1.PopID )
  JOIN ref_PopHHTypes AS ph2 ON ( rp.Pop2 = ph2.PopID AND ph1.HHType = ph2.HHType )
 WHERE Pop1 > 0
   AND Pop2 > 0
```

**Comment by eanders** [comment]
Reopening since I think I'm seeing warnings in the HDX that sound like they could be coming from a related mis-match.  @MollyMcEvilley can you confirm if these need to be updated or not? Thanks!

**Comment by MollyMcEvilley** [comment]
Natalie, I think that your approach -- adding the pop/subpop combinations to ref_PopHHTypes -- is the best.  I added those records to the INSERT statements in Section 1 and went back to a single join to that table in 9.4.1.  

(Closed by [this commit](https://github.com/HMIS/LSASampleCode/commit/b2817761c1421988e9cf5d4a3fd35af4ea3819f9#diff-36370f2de7282e1a7b7863363bc29c99832b602050595d0b11a42782fad0625d).)
