### ISSUE TITLE
Step 9.1.22: question

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#829]
Hi @MollyMcEvilley ,

Under #825 you updated step 8.3.38 adding `or (p1.PopID = 0 and p2.PopID = 0)`
![image](https://user-images.githubusercontent.com/28144855/142857558-a53f8dcd-526e-43c7-83ca-771588f953de.png)

I wonder step 9.1.22 should be updated as well? Now it has
```
(p2.PersonalID = p1.PersonalID or p1.PersonalID is NULL)
and (p2.HouseholdID = p1.HouseholdID or p1.HouseholdID is null)
```
![image](https://user-images.githubusercontent.com/28144855/142858596-e3ff9d9f-3304-4c2e-bf04-b906bacfa01e.png)

but what if it should be updated as 
```
( p2.PersonalID = p1.PersonalID or ( p1.PersonalID is null AND p2.PersonalID is null ))
and ( p2.HouseholdID = p1.HouseholdID or (p1.HouseholdID is null AND p2.HouseholdID is null ))
```
Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
- 9.1.22 is just inserting the population/subpopulation combinations required for the section 9 counts.
- Only section 9.4 (row 55 for universe 11-16) requires pop/subpop combinations. 
- All of the required pop/subpop combinations require a match on PersonalID, but none of them require a match on HouseholdID -- the characteristics of the subpopulations aren't enrollment-specific (e.g., race, gender, ethnicity).  As such, I'm removing HouseholdID criteria and "or p1.PersonalID is NULL" from the join.   
![image](https://user-images.githubusercontent.com/6156815/143312895-4231e845-7465-4b80-82ec-8387cdaa394e.png)
