### ISSUE TITLE
Steps 8.4-8.7: "rv.SystemPath = hh.SystemPath" question

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#830]
Hi @MollyMcEvilley ,

**Step 6.18** has a scenario to set `tlsa_Household.SystemPath = -1`

![image](https://user-images.githubusercontent.com/28144855/143061715-4d2abcc7-3ef7-484c-b8f9-54823dfde2f9.png)

**Steps 8.4-8.7** query has `rv.SystemPath = hh.SystemPath` as one of the conditions.

![image](https://user-images.githubusercontent.com/28144855/143062029-30cd5c74-d1b8-4ac8-bcef-7d85ea0d0320.png)

Please correct me, but I believe `rv.SystemPath = -1` is used to ignore hh.SystemPath, not to limit to households with `hh.SystemPath = -1`. What I am missing?

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
As usual, you are not missing anything -- the code was missing this:

![image](https://user-images.githubusercontent.com/6156815/143290898-10a98223-d6e9-4686-a5af-cf955a7b8724.png)
