### ISSUE TITLE
Steps 8.8-8.11: Possible issue with `ex.HHType` in SELECT and GROUP BY statements in Sample Code

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#831]
Hi @MollyMcEvilley,

I have doubts about `ex.HHType` in SELECT and GROUP BY statements for Steps 8.8-8.11:
![image](https://user-images.githubusercontent.com/28144855/143220028-996e4910-d643-42c6-bd5c-b85f25de8742.png)

Shouldn't hightlighted `ex.HHType` be replaced with `ph.HHType` so `lsa_Calculated` has statistics for `ph.HHType = 0` that means "regardless ex.HHType"?

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Thank you!  Closed by [this commit](https://github.com/HMIS/LSASampleCode/commit/a98894f6d72d384dee935988eec7f3ce1782b614), which also corrects issues in 9.3-9.5.
