### ISSUE TITLE
Steps 9.3.1, 9.4.1: Possible issue with hhid.ActiveHHType in SELECT and GROUP BY statements in Sample Code

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#832]
Hi @MollyMcEvilley,

I have doubts about using `hhid.ActiveHHType` in SELECT and GROUP BY statements for Steps:
- 9.3.1
- 9.4.1

![image](https://user-images.githubusercontent.com/28144855/143235159-9bd6cf86-2b21-4e68-a14b-43e9e9a61b8d.png)

Shouldn't hightlighted `hhid.ActiveHHType` be replaced with `ph.HHType` so `lsa_Calculated` has statistics for `ph.HHType = 0`?

----
I think it was confusing because in the Spec column name is "ActiveHHType" but in fact it should be "HHType" for `lsa_Calculated` table (because ActiveHHType cannot be 0, but HHType = 0 is what we actually expect to insert into `lsa_Calculated` table )
![image](https://user-images.githubusercontent.com/28144855/143236297-3aeaa3cb-d506-44f1-8e3d-fa54746e2f7f.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Thank you!  Sample code corrected by [this commit](https://github.com/HMIS/LSASampleCode/commit/a98894f6d72d384dee935988eec7f3ce1782b614).
