### ISSUE TITLE
Step 9.1.22: possible issue combining population with subpopulation (Sample Code)

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#833]
Hi @MollyMcEvilley ,

According to the spec, for row 55 (Universe 11-16) we should report clients by [population & subpopulation] combination.

![image](https://user-images.githubusercontent.com/28144855/143248411-f48a613b-3020-4871-b1ee-bbae2b3877f2.png)

Lets check what it will be i.e. for population = 52 and subpopulation = 53:

1. Population = 52 is generated on step 9.1.13 for [hhid.HoHID, hhid.HouseholdID]

2. Subpopulation = 53 is generated on step 9.1.14 for [n.PersonalID] (**Please notice** that HouseholdID is not used)

3. new PopID = 5253 should be generated on step 9.1.22.
In our case, `p1.PopID = 52` and `p2.PopID = 53`, correct?
Both `p1` and `p2` have `PersonalID` so `(p2.PersonalID = p1.PersonalID or p1.PersonalID is NULL)` is a true condition.
But what is about `(p2.HouseholdID = p1.HouseholdID or p1.HouseholdID is null)`? 
- `p1.HouseholdID` is not null (see step 9.1.13)
- `p2.HouseholdID` is null (see step 9.1.14)

Thus,  `(p2.HouseholdID = p1.HouseholdID or p1.HouseholdID is null)` is always false so no client is ever reported for PopID = 5253, correct?

![image](https://user-images.githubusercontent.com/28144855/143248068-a7e52740-5763-4e92-95f6-873385da50b5.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Thank you!  Commit forthcoming.
![image](https://user-images.githubusercontent.com/6156815/143297799-cb89113c-1923-4533-8e34-742dae010064.png)
