### ISSUE TITLE
Steps 9.5.x: Possible issue with `hhid.ActiveHHType` in SELECT and GROUP BY statements in Sample Code

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#834]
Hi @MollyMcEvilley,

I have doubts about using `hhid.ActiveHHType` in SELECT and GROUP BY statements for Steps:
- 9.5.1
- 9.5.2

because, according to the spec, for RoportRow = [56, 57] we should be able to export data to `lsa_Calculated` table with `HHType` = 0. But we use group by `hhid.ActiveHHType` that is never 0...
![image](https://user-images.githubusercontent.com/28144855/143259395-7258ee59-eda5-46a0-998b-da8fcd071370.png)

Please advise.

If changes are needed, please also review and fix other 9.5.x steps.

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Thank you!  Closed by [this commit](https://github.com/HMIS/LSASampleCode/commit/a98894f6d72d384dee935988eec7f3ce1782b614), which also corrects issues in 8.8-8.11.
