### ISSUE TITLE
New LSA report based on last changes in Sample Code

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#835]
Hi @MollyMcEvilley , @kiadso ,

Yesterday many tickets were resolved with commits in Sample Code.

1. Could you please re-generate `LSA CSV Export.zip` based on the most recent version of Sample Code?
2. Could you please try to validate it on https://testing.hudhdx2.info/? It is expected that no flag is reported, correct?

I just want to be sure that if any flag is found doing my report upload it is an issue in my report code and not Sample Code or Flags system.

Best regards,
Natalie

**Comment by kiadso** [comment]
Bryan uploaded a new file yesterday, so I think this one is ok to close, but pushing it to Bryan in case there's something else that needs to be done.

**Comment by nataliesus** [comment]
There are some issues in sample code still open, LSA sample report should
be regenerated when these issues are fixed. Thank you!

**Comment by nataliesus** [comment]
Hi @kiadso , @bdavis-pcl ,

Today LSA sample code was updated. Could you please re-generate LSA sample report and validate it on https://testing.hudhdx2.info/ ? If there are any issues, could you please escalate them to LSA flag validation system team?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Hi Natalie,

The upload is currently being rejected by the HDX for records in LSACalculated with population IDs 1336 and 1534 -- this will be addressed as soon as the HDX team incorporates the updates to the LSA Data Dictionary that were completed this morning.  (They have been notified and are working on it.)

**Comment by nataliesus** [comment]
Update:

population ID = 1336 still prevents from LSA report successful upload:

![image](https://user-images.githubusercontent.com/28144855/144390809-6ac41d41-425c-4c27-b144-465ff0d7dbdf.png)

@kiadso , @bdavis-pcl , could you please take a look?

Also, now ID column is empty. Is it possible to display distinct [ReportRow] there? 
![image](https://user-images.githubusercontent.com/28144855/144391823-d81fc3d2-34dd-4995-bc20-060222c9e907.png)

**Comment by kiadso** [comment]
The 1336 problem should be solved now. Also there is a new set of sample data available on Sakai and on this repo.

Thanks for your patience-
