### ISSUE TITLE
LSA upload rejected: could you please check if it is OK?

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#839]
Hi @MollyMcEvilley , @kiadso ,

My upload was rejected: https://testing.hudhdx2.info/module/lsa/uploads/1243/error-report

It looks like an error in the validation system. because Population 1015, 1115, 1215, 1315 are allowed for ReportRow = 1 and SytemPath = -1
![image](https://user-images.githubusercontent.com/28144855/143596687-268f4aac-82ad-4687-964a-a2987ca59362.png)

i.e. here is what I have on row 142 in LSACalculated.csv:
![image](https://user-images.githubusercontent.com/28144855/143597481-c242195d-f6e2-4a7e-8765-14613b6763ef.png)

Best regards,
Natalie

**Comment by kiadso** [comment]
Hi, I escalated this, thank you Natalie!

**Comment by kiadso** [comment]
Hi this should be fixed, Natalie!

**Comment by nataliesus** [comment]
Hi @kiadso ,

Today I uploaded other LSA report and it was rejected again with the similar validation error
![image](https://user-images.githubusercontent.com/28144855/144045913-75a8dcd3-96c3-4cdd-929d-b98dbee8bede.png)

Could you please reopen this ticket as not all flags were fixed?

Thank you!!
Natalie

**Comment by kiadso** [comment]
Hi Natalie, 
Using List 32 in the Data Dictionary, 1336, 1534, and 1536 are not listed in the Data Dictionary as valid responses, so these flags would be accurate.

**Comment by nataliesus** [comment]
Hi @kiadso ,

Who should we address a question to fix LSA Data Dictionary? 

Please re-open this ticket and re-assign to @MollyMcEvilley because combinations 1336, 1534, 1536 were added in LSA sample code as fixes for:
- https://github.com/HMIS/LSASampleCode/issues/822
- https://github.com/HMIS/LSASampleCode/issues/827

Thank you!
Natalie

**Comment by kiadso** [comment]
Thank you, Natalie- I have escalated this.

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

Today you added two out of three missing rows:
![image](https://user-images.githubusercontent.com/28144855/144242809-fabb2d91-e877-4903-a920-fc01f98e2616.png)

Please add 1535.

Thank you!
Natlaie

**Comment by nataliesus** [comment]
Thank you, Molly!

**Comment by LaurenBianchi** [comment]
![image](https://user-images.githubusercontent.com/92442726/144256205-4ef82361-602e-460b-90b5-4f9247f44200.png)
Can "1535 Chronically Homeless Household - Parenting Child" also be added to the Pop Crosswalks tab? 

Thank you for your time,
Lauren

**Comment by MollyMcEvilley** [comment]
Yes indeed.

**Comment by nataliesus** [comment]
Hi @kiadso !

Could you please reopen this ticket? The issue with Population ID = 1336 still exists even if this code exists in LSA Data Dictionary:
![image](https://user-images.githubusercontent.com/28144855/144417509-47638dfe-df58-4d62-8bec-173c323103cd.png)

![image](https://user-images.githubusercontent.com/28144855/144417140-cdfa59c8-ffea-452f-a4c8-a7bf54bd1a1a.png)

Thank you!
Natalie

**Comment by kiadso** [comment]
Escalated! Thank you Natalie!

**Comment by kiadso** [comment]
Natalie, could you check this again?

**Comment by nataliesus** [comment]
Hi Genelle!

The upload was approved today. Thank you! Now it is time for us to review why we have 18.291 flags. But it will be another ticket.  :)
![image](https://user-images.githubusercontent.com/28144855/144589590-93b05d0d-e57f-44ed-80f3-ff72c4dc7489.png)

Thank you!
Natalie
