### ISSUE TITLE
LSA HMIS CSV Enrollment CSV issue

### ISSUE THREAD

**Issue by 2008zjqc** [MollyMcEvilley/LSASampleCode#840]
Good afternoon,
We are thinking there is an issue regarding LSA HMIS CSV Enrollment.csv for enrollment ID '181697_26179' and '181697_26181' both associated with person '76820' and with householdID '181697'. The two enrollments are of different entry date, under this case, one of the enrollment should with a different Household ID. Same household ID can't be re-use for readmission to the project as data dictionary suggested. 

I do understand the LSA report result current is generate based on this HMIS CSV. However due to this issue, when we trying to import HMIS CSV into our system, we are encounter duplicated key issue. 
Please take a look and provide a suggestion. 
Thanks very much.

Best,
Chen

**Comment by jbloescw** [comment]
I believe we are seeing the same issue on our end.  Can we get this corrected and new files pushed out here today please?

**Comment by 2008zjqc** [comment]
> I believe we are seeing the same issue on our end. Can we get this corrected and new files pushed out here today please?
Hi Jeff
Greeting~~ We manually removed the record from HMIS CSV import, and manually added back to LSA temp table in order to compare the numbers...... It takes some efforts : ( Hope they can resolve it soon....
Chen

**Comment by bdavis-pcl** [comment]
According to page 89 of the Data Dictionary:
"Persons may join a household with members who have already begun a project
start or may leave a project although other members of the household remain in
the project. A common Household ID must be assigned to each member of the
same household. Persons in a household (either adults or children) who are not
present when the household initially applies for assistance and later join the
household should be assigned the same Household ID that links them to the rest
of the persons in the household. The early departure of a household member
would have no impact on the Household ID. **A household member who leaves
and returns to the same household while others in the household remain
enrolled should be reassigned the same Household ID as that member’s earlier
enrollment.**"

This specific enrollment is exited on 12/2/2019 and then has an intake into the same household on 12/16/2019. Their RelationshipToHoH is 3. The Head of Household is enrolled from 12/3/2018 - 9/18/2020. As far as I can tell PersonalID 76820  should have the same household ID across both enrollments.

If you have further issues with the Data Dictionary, please submit an AAQ.

**Comment by MollyMcEvilley** [comment]
I think there's only one record in the HMIS CSV where a household member has two EnrollmentIDs with the same HouseholdID.  For LSA purposes, it's not necessary -- maybe the second enrollment could just be removed?  

(I'm not dismissing the issue of DE 5.09, but it's a separate issue... The language in bold above was added to the dictionary in 2020.  It would represent a big functionality change in a lot of applications, but it wasn't noted in the revision summary for DE 5.09 -- and I'm not sure that the majority of vendors were aware that this requirement had been added.)

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

> household member has two EnrollmentIDs with the same HouseholdID

Just in case, in live systems we also sometimes have Households where household member has two or more EnrollmentIDs.

**Comment by MollyMcEvilley** [comment]
That is definitely correct per the data standards, but I’m not sure that requirement is universally understood.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
