### ISSUE TITLE
LSA Data Dictionary: Missing rows on "Pop Crosswalks" tab

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#841]
Hi @MollyMcEvilley , @kiadso ,

It looks like rows for pop/suppop combinations where popId= 15 are completely missing. The list ends on FY2021 ID = 1434
![image](https://user-images.githubusercontent.com/28144855/144209192-275038f1-edfd-426b-9b02-c240275efe11.png)

Could you please take a look?

Thank you!
Natalie

**Comment by nataliesus** [comment]
Also, If you can sort by ask pop/subpop for Section 9 it will be helpful for review:
![image](https://user-images.githubusercontent.com/28144855/144210084-717e4ec1-49a2-46d7-adc9-3a9ee7e70f51.png)

**Comment by MollyMcEvilley** [comment]
Hi Natalie -- I added the Veteran + subpopulation combinations to the Pop Crosswalks tab.  I added that tab to make sure that all of the old population IDs were represented in the new list, so it's sorted by the old population ID -- but you should be able to sort it in any way that is useful to you!
