### ISSUE TITLE
LSA Data Dictionary: LSACalc Values by Row missing rules

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#842]
Hi @MollyMcEvilley , @eanders ,

I think there are two issues with "AHAR Counts by Project Groups".

**1.**
According to the spec (section 9.4) row 55 should be reported also for PopID =1176, 1177, 1276, 1277

![image](https://user-images.githubusercontent.com/28144855/144213343-0492a6d8-810c-4f86-9a06-086c25e40704.png)

**2.**
According to the spec (section 9.4) row 56 should be reported only for PopID = 0, 10, 11:
![image](https://user-images.githubusercontent.com/28144855/144214573-2c04c4f5-02b1-4637-815e-8dedb340f92f.png)

But in LSA Data Dictionary PopID = 1, 2 are used instead of PopID = 10, 11
![image](https://user-images.githubusercontent.com/28144855/144214240-cf059c01-0a2b-4b33-8d9e-b95a74a0d5aa.png)

**3.**
"AHAR Counts by Project ID" has the same issue with PopID = 0, 1, 2 for row = 65. It should be PopID = 0, 10, 11
![image](https://user-images.githubusercontent.com/28144855/144215179-de648f4b-e9e5-414e-9731-1e5b3e6c6021.png)

Best regards,
Natalie

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

Just wonder if HUDX team who works on flag validation system should be informed that LSA Data Dictionary was changed to review and fix flags?

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
They only use the Files, Columns, and Lists tabs of the Dictionary in their validations... They requested the addition of 1336, 1534, and 1536 to the list of populations and they have been notified that it was updated in [this commit](https://github.com/HMIS/LSASampleCode/commit/f6475ca82f6911787d37a68fd882cc40af380016#diff-982821f33e9cddd4d8b9cff0f4462b707bb6fdcef468194ac0e1e864fb1186bd).
