### ISSUE TITLE
Flag 781 (missing Inventory records)

### ISSUE THREAD

**Issue by MollyMcEvilley** [MollyMcEvilley/LSASampleCode#850]
![image](https://user-images.githubusercontent.com/6156815/144305517-728dc1ef-5121-4ff5-8ebf-f36879f68230.png)
Flag says there is no inventory record for ProjectID 960 with an InventoryStartDate <= LSA Report End.  There IS an inventory record for this project with a start date of 1/1/2010, which is < ReportEnd (9/30/2021).
![image](https://user-images.githubusercontent.com/6156815/144305616-55b25aee-3360-4c99-abd3-d3eca6c844fb.png)

**Comment by kiadso** [comment]
Hi Molly, 

This issue has been addressed. Please let me know if you continue to see this

**Comment by kiadso** [comment]
(Will close this once fix is deployed)

**Comment by MollyMcEvilley** [comment]
Closing -- flag not showing up for upload today of the same dataset that generated this when I submitted the issue.

**Comment by kiadso** [comment]
This one is showing up again on Test, dev is reviewing.

**Comment by kiadso** [comment]
This flag actually had true and false positives. The false positives were resolved, but the true positives remain. Projects 1099 and 1497 are actually missing Inventory records in the HMIS CSV sample data. They are project types 2 and 3, so they should have Inventory records.
Thanks!

**Comment by bdavis-pcl** [comment]
Yes, I'm working on a cleaned up sample data set that fixes this issue.

**Comment by bdavis-pcl** [comment]
This issue has been resolved with the most recent sample data set I just uploaded.
