### ISSUE TITLE
Request to add temp table to output file

### ISSUE THREAD

**Issue by jbloescw** [MollyMcEvilley/LSASampleCode#851]
Good afternoon,
When the next round of output is generated for the temp tables, can tlsa_ExitHoHAdult be added please?  It would aid in the troubleshooting of some numbers that it uses to populate tlsa_Exit.

Thank you.

**Comment by bdavis-pcl** [comment]
Will do.

**Comment by kiadso** [comment]
Thank you Bryan! I'm seeing this on this repo and on Sakai
