### ISSUE TITLE
Export Flags option doesn't work

### ISSUE THREAD

**Issue by OksanaSukhorukova** [MollyMcEvilley/LSASampleCode#852]
Hi @kiadso,
Today we've received 18,291 flags from our test upload (https://testing.hudhdx2.info/dataset/1299/warning), but unfortunately, the button Export Flags returns the issue "This page isn't working"
![image](https://user-images.githubusercontent.com/71442061/144589923-b2ba98a5-04a4-46c2-b80c-4cc04e46ff34.png)
Could you please check?

**Comment by kiadso** [comment]
Hi Oksana,
Thanks for reporting this. I escalated it to the HDX team. I am getting the same problem when I go to the link you provided, but whenever I click Export Flags on my own upload, it does work! Anyway, we are working on it, thanks again.

Genelle

**Comment by kiadso** [comment]
@OksanaSukhorukova, is this happening on your other uploads or just this one? Is this a showstopper for you? We are trying to prioritize things over here- thank you!

**Comment by kiadso** [comment]
Hi, I have confirmed that this is no longer an issue. It was a memory issue that affected very large Error files. We increased the memory available.

Thank you

Genelle
