### ISSUE TITLE
LSA Sample report: Flags generated on 12/3/2021

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#853]
Hi @MollyMcEvilley ,

Yesterday @bdavis-pcl generated **LSA CSV Export.zip** based on the most recent LSA sample code.

I've uploaded it to https://testing.hudhdx2.info/ and 102 flag error records were generated (you can also find them in **FlagsExport.csv** file).

There are 8 created flag tickets currently open that you generated previously for flags:
- 781
- 799
- 800
- 1263
- 1264
- 1267
- 1268
- 1283

What is about flags reported in **FlagsExport.csv** file that do not have flag tickets? Is it something you will investigate in the nearest future, or they can be resolved themselves after 8 already reported flags are resolved?

Please advise.

Thank you!
Natalie

**Comment by kiadso** [comment]
We are monitoring the flags being thrown by the sample data as well and are planning to get to all of them. Molly has been kind enough to help us with documenting the list in your question. Thank you for your subsequent tickets documenting the remaining flags, Natalie!

Genelle
