### ISSUE TITLE
Flags 718 and 719

### ISSUE THREAD

**Issue by MollyMcEvilley** [MollyMcEvilley/LSASampleCode#861]
![image](https://user-images.githubusercontent.com/6156815/144662233-3204fefa-8cb0-4f6a-b5a6-7e4e34426493.png)
![image](https://user-images.githubusercontent.com/6156815/144665848-040e6177-8b23-4a63-9640-02c091f6c078.png)

Flag **718**: For ReportRow 54, there is 1 AC (hhtype = 2) veteran household (population = 13) housed in PSH (universe = 15) during the report period (cohort = 1), but there are no veterans (population = 50) in the same universe/cohort/HHType.  

Flag **719**:  A little redundant, but indicates that for ReportRow 53, there are 2 people counted in the veteran household described above, but (again) no veterans.

The flags indicate that this is a data error, but that is not accurate.  

- A head of household (not a veteran) was enrolled in a PSH project with a spouse/partner (a veteran) and a child in 2020.  
- Because the spouse is a veteran, they are a veteran household.
- The HoH and child moved into housing on 3/15/2021 -- so the veteran household was housed in PSH.
- One veteran household (Row 54) and 2 people in a veteran household (Row 53) were counted in LSACalculated.
- However!  The spouse/partner -- the veteran -- EXITED the project on that date, and thus was not counted as housed in PSH.

**Comment by kiadso** [comment]
Hi, the flag team addressed this and it is no longer flagging in the PCL data set. Thanks for documenting this, Molly!
