### ISSUE TITLE
Flags 722 & 758 (overlaps)

### ISSUE THREAD

**Issue by kiadso** [MollyMcEvilley/LSASampleCode#863]
Flags 722 & 758 are about overlapping enrollments. These are examples of a true positive and vendors have asked for a dataset that does not throw any errors, so these overlapping enrollments may need to be cleared up to get to that. I'm attaching all the overlaps that I detect using my old R code from when I was at COHHIO, but my R code was not written necessarily to match the LSA flags because I didn't know how they were being calculated when I wrote it. Either way, these are overlaps we would have chased in my former CoCs that I worked for. It should at least get us to under the threshold. Hope it helps!

[overlaps.xlsx](https://github.com/HMIS/LSASampleCode/files/7652577/overlaps.xlsx)

**Comment by bdavis-pcl** [comment]
These flags have been cleaned out of the sample data set I just uploaded.
