### ISSUE TITLE
Flag 686 (HHVetEST)

### ISSUE THREAD

**Issue by OksanaSukhorukova** [MollyMcEvilley/LSASampleCode#864]
Hi @kiadso, 
Molly reported the issue about flag 686 (HHFleeingDVEST ), but my issue flag 686 (HHVetEST). 
My LSA test submission flags list:  https://testing.hudhdx2.info/dataset/1313/warning
Could you please ask the dev team about Flag 686-1(HHVetEST )?
![image](https://user-images.githubusercontent.com/71442061/144834510-078249d8-f107-4060-9ef2-3cf0ca37f350.png)
Row 4 use the condition `HHTypeEST>-1 and HHVetEST>-1 and AHAREST>-1 and HHVetEST == -1 and HHTypeEST>-1 and HHVetEST>-1 and AHAREST>-1 and HHVetEST == -1`
According to the flag description we should report veteran household types from the LSAPerson where **`HHVetEST>-1 AND HHVetEST == -1`**  It is a really confusing condition. HHVetEST can't be more then -1 and equal 1 at the same time.
Also, each condition exists twice in row4. Is it OK?

**Another descriptions for flag = 686 have a similar issue, for example `HHVetPSH > -1 AND HHVetPSH == -1` or `HHChronicEST > -1 AND HHChronicEST == -1`. Could you please ask HDX team about checking all conditions for flag 686**

**Comment by kiadso** [comment]
Yes, thank you for documenting this Oksana. I had noticed this too- it is in the queue for dev.

**Comment by nataliesus** [comment]
Hi @kiadso ,

I have a bit different value for SAS logic but it also has contraversion logic and duplicate conditions
![image](https://user-images.githubusercontent.com/28144855/145049948-b3baad5c-a51c-4d56-80e7-3ae024812a10.png)

Could you please escalate it to dev team?

Thank you!
Natalie

**Comment by OksanaSukhorukova** [comment]
The issue was fixed.
