### ISSUE TITLE
Flags 799-1 and 800-1

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#866]
Hi @kiadso ,

Submission: https://testing.hudhdx2.info/dataset/1322/warning

Could you please take a look if description = "null" should be fixed for flags:
- 799-1
- 800-1

![image](https://user-images.githubusercontent.com/28144855/145015356-8b7b9b1f-f7d1-40ee-aba8-8c0f1352d3e8.png)
![image](https://user-images.githubusercontent.com/28144855/145015261-1b8e45b2-b91e-43ac-b6a6-75378a8e7f5b.png)

Thank you!
Natalie

**Comment by kiadso** [comment]
Thank you for documenting this Natalie! Escalating now

**Comment by kiadso** [comment]
Hi Natalie, the fix for this was pushed to all three sites an hour ago and the last upload I'm seeing from you was before that, so could you re-upload and see if this is resolved? Thank you!

**Comment by nataliesus** [comment]
Hi Genelle!

Confirm there are no more null variables for these flags. Thank you!
