### ISSUE TITLE
Flag 24- Multi-ProjectCoC

### ISSUE THREAD

**Issue by eanders** [MollyMcEvilley/LSASampleCode#867]
We're receiving reports that the HDX is rejecting files where a project has multiple ProjectCoC records within the same CoC.  There's a clear restriction on this in the LSA spec, but this appears to be allowed in the HMIS CSV spec.  In this case the projects operate in multiple zip codes and geography types within the CoC, so the records are distinct.  Is there any guidance on how we should pick the correct Project CoC record for upload?  Would it make sense to allow the upload through and then flag them as data quality issues? (I'm guessing not, there's probably an inner join somewhere in the sample code that would cause duplicates.)

Any direction would be greatly appreciated.

**Comment by kiadso** [comment]
Hi Elliott,

Thanks for the question. In the HMIS Data Manual, in the section about DE# 2.03, it says:

> There must be a one-to-one relationship to Project Information if the project only serves one CoC.

So within a given CoC and ProjectID, there should be a single record.

Also, for the definition of ZIP Code, it states:

> The ZIP code of the project's principal site or, for scattered-site projects, the ZIP code in which most of the project's clients are housed.

So if a single project serves across multiple ZIP codes, this data element would not be the place to record that information.

As to whether this should be a Data Quality Error or an Upload Error, I can look further into that.

**Comment by eanders** [comment]
Thanks!

**Comment by kiadso** [comment]
Reopening until we can either change it to a Data Error instead of an Upload Error or answer Elliott's question about how to decide which record to choose if their implementation is using the data element incorrectly.

Thanks!

**Comment by eanders** [comment]
Noted on the office hours call.  This won't be adjusted in HDX, but it should be safe to remove the extra ProjectCoC records from the LSA prior to upload as counts should be done as distinct counts.
