### ISSUE TITLE
Flags 758-1 and 758-5

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#870]
Hi @kiadso ,

"Variables" table is completely empty for flag 758. Could you please take a look?

![image](https://user-images.githubusercontent.com/28144855/145051449-caf70e0b-a06b-4931-928c-0da3f6261797.png)

Thank you!
Natalie

**Comment by kiadso** [comment]
Confirmed that these are fixed- thanks for documenting this, Natalie!
