### ISSUE TITLE
ERROR: "Your dataset encountered an error during error checking process. Please contact administrator."

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#872]
Hi @kiadso ,

I get "Your dataset encountered an error during error checking process. Please contact administrator." error message when flags are generated for my new submission.

https://testing.hudhdx2.info/dataset/1331/warning

![image](https://user-images.githubusercontent.com/28144855/145081348-536cd2ca-8d7c-44f6-a18f-aeccc526e3b7.png)

Is there anything I do wrong?

Best regards,
Natalie

**Comment by kiadso** [comment]
We are thinking this may have something to do with the AWS outage today. I'll leave this open until we hear from you that it's resolved. Thank you for reporting this.

**Comment by nataliesus** [comment]
Hi Genelle,

I don't have this error message anymore doing a new upload. Closing this ticket. Thank you!
