### ISSUE TITLE
Request to add "Regenerate Flags List" button

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#873]
Hi @kiadso ,

I wonder if it is possible to add a "Regenerate Flags List" button next to the "Export Flags" (or somewhere else) so we can easily get the updated flags list if i.e. the report is the same but some flags were fixed on HDX side?

![image](https://user-images.githubusercontent.com/28144855/145208512-7c39e826-ba76-43c5-9fa1-f2edfdc2ed4f.png)

I am not sure how to get the updated flags list now, so I usually make another report submission. But it will really help if nothing should be re-uploaded from our side.

Thank you!
Natalie

**Comment by kiadso** [comment]
Hi Natalie,

We may add something like this next year but we cannot add this for this year. Til then, we have to continue using Replace Upload to get the flags to recalculate on the same data.

Thanks for your patience!
