### ISSUE TITLE
1246-983

### ISSUE THREAD

**Issue by OksanaSukhorukova** [MollyMcEvilley/LSASampleCode#874]
Hi @kiadso,

"Variables" table is completely empty for flag 1246-983. Could you please take a look?
![image](https://user-images.githubusercontent.com/71442061/145214613-f8de68e6-dbb6-486d-a527-ffb529e89bcb.png)
Also, according to spec for Population 18 to 21 years old, we need to use `HHtype = 1`, so we don't report `HHtype = 0` for 18 to 21 years old.  I am not sure that the comparison from the task description is the correct `Sum of HHType AO, AC, CO, UN values < all HHs value`
![image](https://user-images.githubusercontent.com/71442061/145214607-5e137352-c4c7-4e85-96af-0ccaf46f29a0.png)
Could you please take a look?

**Comment by kiadso** [comment]
Escalated, thank you Natalie!

**Comment by kiadso** [comment]
Hi Oksana, this is resolved now, thanks for documenting the issue!

**Comment by nataliesus** [comment]
Hi @kiadso,

Could you please re-open this ticket because the variables table is still empty?
![image](https://user-images.githubusercontent.com/28144855/145435115-866a6158-1a8d-491e-8a83-e1d887a56392.png)

The most recent upload is https://testing.hudhdx2.info/dataset/1348/warning
Thank you!

**Comment by OksanaSukhorukova** [comment]
@kiadso thank you, this is resolved. Closing this ticket!
