### ISSUE TITLE
Unexpected EST/RRH/PSHParent values in Flags

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#876]
Hi @kiadso,

Please correct me if I am wrong, but according to the Spec, EST/RRH/PSHParent must be either 0 or 1:
![image](https://user-images.githubusercontent.com/28144855/145242374-1203a336-dc87-4b8d-b7cc-d440cb4596d8.png)

So it looks pretty odd to see flag conditions similar to `PSHParent in (2,12,23,29,123,129,239,1239)` in i.e. Flag 645-1:

![image](https://user-images.githubusercontent.com/28144855/145243199-98d55e15-40a2-4d99-ad9f-fcc42b71d840.png)

There may be other flags as well. Please ask dev team to review and fix. Also, it is weird that in i.e. Flag 645-1 completely different PSHParent values are checked thgat can be a real issue:
- `PSHParent in (2,12,23,29,123,129,239,1239)`
- ` PSHParent=1`

So please ask dev team to check and fix such conditions, and also not for `PSHParent` only but for `ESTParent` and `RRHParent` as well.

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
I think the issue here is that the column name in LSAPerson isn't **PSHParent**"but **HHParentPSH**.

**Comment by kiadso** [comment]
Molly thank you so much for figuring this out and Natalie for documenting- This has been fixed. I'm not seeing flag 645 in Natalie's most recent upload.
