### ISSUE TITLE
Unexpected EST/RRH/PSHFleeingDV values in Flags

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#877]
Hi @kiadso ,

According to the Spec, EST/RRH/PSHFleeingDV must be either 0 or 1:
![image](https://user-images.githubusercontent.com/28144855/145245344-6e1a3ec8-2660-4d84-9c4a-df4e9b7ba5e2.png)

There are flags that use i.e. `ESTFleeingDV in (1,12,13,19,123,129,139,1239)` condition where unexpected values are checked, i.e. Flag 635-1:
![image](https://user-images.githubusercontent.com/28144855/145245565-70b85807-1358-4488-956b-cef39a59f828.png)

There may be other flags as well. Please ask dev team to review and fix EST/RRH/PSHFleeingDV conditions.

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
(NEVER MIND THIS COMMENT -- THE ISSUE ISN'T THE LOGIC BUT THE COLUMN NAMES.)

LSAHousehold.**HHType** = 1 and **ESTFleeingDV** = 1 is the equivalent of LSAPerson.**ESTFleeingDV** in (1,12,13,19,129,139, 1239).

**Comment by MollyMcEvilley** [comment]
Oh wait, I get it -- the column name in LSAPerson is **HHFleeingDVEST**, not **ESTFleeingDV**.

**Comment by kiadso** [comment]
Molly thank you so much for figuring this out and Natalie for documenting- This has been fixed. I'm not seeing flag 645 in Natalie's most recent upload.
