### ISSUE TITLE
Flag Descriptions Missing

### ISSUE THREAD

**Issue by jbloescw** [MollyMcEvilley/LSASampleCode#880]
When downloading the flag error export to view all the flags that threw the particular flag, the Flag Data Field Description 1/2/3/etc.. are all blank which makes the Flag Data Field Value 1/2/3 practically useless.
Is this happening to others or just me?  
I'd love to get this working so I can dig into some of these flags better.

**Comment by kiadso** [comment]
Hi Jeff, 
What dataset are you looking at? Whenever I use the sample data, I am seeing data in the "Flag Data Field Description x" columns in the Export Flags document. Most flags will only have data in Variables 1 and 2, definitely the lower numbers and the other columns will be left intentionally blank, depending on the flag.

**Comment by jbloescw** [comment]
CW Test_SC_1

**Comment by kiadso** [comment]
Escalating, thanks Jeff!

**Comment by kiadso** [comment]
This has been fixed. Thank you for documenting this, Jeff!
