### ISSUE TITLE
Flag 701-1 (accounting for aging across HHTypes)

### ISSUE THREAD

**Issue by jbloescw** [MollyMcEvilley/LSASampleCode#882]
Dataset: CW Test_SC_1
Flag Description: LSACalculated: People < Households (Project level)

People (Row 53) are counted by distinct PersonalID
Households (Row 54) are counted by the distinct combination of HoHID + ActiveHHType

I have 3 PersonalIDs that had multiple legit enrollments throughout the report year.  They just so happened to have a birthday in there that changed the way their HHType was calculated for one of the enrollments.  

So that means that they now have 2 distinct households (HoHID + HHType) but yet only 1 distinct personalID.

My assumption is that the flag is trying to make sure there is at least 1 person per household by comparing the value field for that Row 53 to Row 54 by hhtype/population/cohort/etc...  If that's the case, I'm wondering if we are seeing a flag or code issue because the source data reads correctly.  If anyone wants further details, please let me know.

**Comment by nataliesus** [comment]
Hi @kiadso ,

I think the issue is the same for other flags we received:
- 701-3
- 701-4

Do you have any idea when they can be resolved?

Best regards,
Natalie

**Comment by kiadso** [comment]
Hi, this was demoted to a Warning, thanks for your patience!
