### ISSUE TITLE
Flag 1246-983 ( potential issue in the sample code )

### ISSUE THREAD

**Issue by OksanaSukhorukova** [MollyMcEvilley/LSASampleCode#883]
Hi @MollyMcEvilley , @kiadso ,
Submission: https://testing.hudhdx2.info/dataset/1357/warning
![image](https://user-images.githubusercontent.com/71442061/145594539-9586a06e-6eb5-424c-9e24-0fbe830be3db.png)
@MollyMcEvilley I've investigated the flag 1246-983 and looks like that we have a potential issue in the LSASampleCode
Scenario:
Client A has three different enrollments to the projects with LSAProjectTypes IN ( 2, 0 ), Client DOB = 08/15/2003
![image](https://user-images.githubusercontent.com/71442061/145595198-77ebb807-9c81-42a2-8940-fed64e8620bb.png)
Client PersonalID is reported to the tlsa_countPops with PopID = 76(18 to 21 years). and it is correct because the client has Enrollment that matches all criteria
![image](https://user-images.githubusercontent.com/71442061/145595312-8d6d0b4e-cf5e-42b6-bacb-9023cfccfa08.png)

According to the Sample Code(Step 9.4), we can report this client to the Values with the next parameters
- Report Row = 55 
- Population = 76 (people who are 18 to 21 years old)
- Universe = 13 (TH Project Type)
- Cohort = 13 (Active on July 31st)
- HHType = 0

Population 76 reports clients where Maximum ActiveAge = 21. Possible HHtypes for Population 76  - 0,1,2,99
Universe 13 reports the clients enrolled in the TH programs.
ActiveHHType during TH enrollment for Client A is 3 (CO), so **I think we can't report client A, where HHType = 0 to the Universe =13 and Population = 76, because HHType = 3 is excluded from this population**
![image](https://user-images.githubusercontent.com/71442061/145597354-e07725b3-9767-41ff-b2c5-f9829ac2347b.png)

So according to the LSaSampleCode 
- we should report this client with characteristic (ReportRow=55) where Cohort=13 (Active on July 31st) & Universe=13 (TH Project Type) & **HHType=0 (All)** & Population=76 (people who are 18 to 21 years old)
- AND shouldn't report this client with characteristic (ReportRow=55) where Cohort=13 (Active on July 31st) & Universe=13 (TH Project Type) & **HHType IN (1,2,99)** (All) & Population=76 (people who are 18 to 21 years old)

Looks like all flags like this should be removed or LSASAmpleCode should be updated

Could you please take a look?

**Comment by kiadso** [comment]
@MollyMcEvilley let me know if you feel this should be addressed by the flag team instead!

**Comment by MollyMcEvilley** [comment]
The code here is consistent with the specs.  The discrepancy is an artifact of trying to produce an unduplicated count of people by age when they have been assigned multiple ages during a single year, and it will occur in situations like this -- for people served who age into adulthood between two EntryDates with a resultant change in HHType.  The alternative -- counting people in multiple age categories -- would result in a larger discrepancy, because it would apply to every age category transition (e.g., 34 to 35 or 44 to 45) and not just the one that results in a change of household type.  I think that the flag needs to take this into account.

![image](https://user-images.githubusercontent.com/6156815/146401780-1500a585-e22c-4bc0-bb9c-5863f8fdf250.png)

**Comment by MollyMcEvilley** [comment]
Proposed change for next year:  Add PIT1, PIT2, PIT2, PIT4 columns to LSAPerson and LSAHousehold and remove the counts from LSACalculated.  This would eliminate situations where the flags are trying to compare things that aren't always going to be the same.

**Comment by kiadso** [comment]
Escalated, grouped with the Issues about Flags 1230, -32, -41, and 701
Thank you both for documenting this!

**Comment by kiadso** [comment]
This has been reclassified as a Warning

**Comment by OksanaSukhorukova** [comment]
Hi @kiadso we have a very similar flag but not about quarterly PIT dates but about the full report period
![image](https://user-images.githubusercontent.com/71442061/148064796-cbe77730-b1f9-4ed8-af8b-bcd020daea56.png)
Could you please take look? I think it should be reclassified as a Warning too.
