### ISSUE TITLE
Flag 779-1 NoCoC (and NotOneHoH1 and NotOneHoH3) issues

### ISSUE THREAD

**Issue by TanyaPieterse** [MollyMcEvilley/LSASampleCode#885]
Hi Molly,

In Flag 779-1:
You reported more cases of missing client locations in the one-year report period (in your LSACalculated data for ReportRow 62) 
than in the three-year period including the report year and the prior two years (in the NoCoC field of your LSAReport data). 
This difference was significant (greater than five cases).

Background Info:
Our main issue is that the CoC has some HouseholdID's for which they did not enter a RelationshipToHoH=1 record...  this means no record in the hmis_EnrollmentCoC for the HouseholdID, and no record in hmis_Enrollment where RelationshipToHoH=1.  

**Here is how it plays out in the 3 DQ Fields, and the above Flag:**

In LSA Step 11.2, **NoCoC** is calculated by selecting the HouseholdID's from hmis_Enrollment where RelationshipToHoH=1 and the hmis_EnrollmentCoC Client Location is missing; but the Client Location element is only captured on the HOH record - which means this will just check if the Client Location field was captured IF the HOH was captured.  It does not cater for the situations where the HOH record is missing, and therefore the Client Location is missing.  Should the NoCoC calculation be adjusted to look more like Step 10.4 (this one calculates ReportRow 62) where there is a left outer join to hmis_Enrollment hoh where RelationshipToHoH=1 (or hmis_EnrollmentCoC), and if the record (and therefore Client Location) is missing, then they get counted and included in the total?

There are 2 more DQ fields that relate to the above, **NotOneHoH1** and **NotOneHoH3**.  The calculations count HouseholdID's from dq_Enrollment where there is no record for the HOH in the left outer join hmis_Enrollment where RelationshipToHoH=1.  BUT in LSA Step 11.1, with the insert into dq_Enrollment, we inner join to hmis_EnrollmentCoC (this file only includes the records where RelationshipToHoH=1).  So logically it is HOH records checking to see if there is a missing HOH records, so this will always be 0.

I feel like I am talking in circles :) please let me know if I have to explain a bit better.

Thanks!

**Comment by kiadso** [comment]
Hi Tanya,

We looked at this and we are thinking it is ok that it will flag only when there is a valid HoH. Any household with one or both of these data quality issues (NotOneHoH & NoCoC) will be excluded from LSA reporting. If they see the NotOneHoH flag and correct that, and that household also had a NoCoC issue (or any number of other issues), then they will get that Error flag at that point, and that is ok. It's possible that correcting household issues will generate other data quality issues; the LSA data cleaning process is definitely iterative.

Let me know if you have further concerns and thanks for submitting your question!

Genelle
