### ISSUE TITLE
Server Processing Error: Upload error flag processor

### ISSUE THREAD

**Issue by jbloescw** [MollyMcEvilley/LSASampleCode#887]
I have a CoC getting this error message upon uploading a file.
The only wording present in this error is what was contained in the title and nothing else.
If this is something on the customer's end, can you let us know what the issue with the file is?

**Comment by kiadso** [comment]
Hi Jeff,

Thank you for reporting this. What CoC is it?

**Comment by KAdlerCW** [comment]
Replying on Jeff's behalf - this is for San Antonio/Bexar County CoC (TX-500).

**Comment by jbloescw** [comment]
Another one just rolled in for CT-505

**Comment by kiadso** [comment]
This has been determined to be because there are multiple ProjectID records with the same ProjectID. TX-500 has an AAQ in about it, though we have not heard from CT-505 in the AAQs. Please work with your CoC to eliminate any duplicate ProjectIDs. Thanks!
