### ISSUE TITLE
Follow-up for Flag 783 (0 beds in flag but there are beds)

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#888]
Hi @kiadso ,

It is follow-up for #859 that was closed 2 days ago because the issue was reported as resolved on Test and Prod.

Unfortunately, it is still actual for us. Upload made on 12/14/2021: https://testing.hudhdx2.info/dataset/1378/warning

![image](https://user-images.githubusercontent.com/28144855/146194451-fa798730-4401-405f-ae79-cc07706b51d3.png)

Inventory.csv does have 2 inventory records for [HMIS Project ID] = 785
![image](https://user-images.githubusercontent.com/28144855/146194735-c3c9585e-d12a-4937-9bd8-4fde01d22773.png)

Please advise.

Thank you!
Natalie

**Comment by eanders** [comment]
We are also seeing this flag where there are valid inventory records for the projects in the report range.  Is it possible the issue is having multiple valid inventory records for the same date range?  Ours look very similar to @nataliesus's in that there are two records for each time period.

**Comment by nataliesus** [comment]
Just in case, there are 2 inventory records on the same period, but with **different HouseholdType**s  (which is quite important, I think).

**Comment by eanders** [comment]
Same here, 1 and 3, same as yours.

**Comment by cywiseman** [comment]
We continue to see this cropping up where there are valid BUI records.  Is there any update on the status of this one?

**Comment by kiadso** [comment]
Hi Candice- this one and the other ones that are not closed yet are coded but not pushed to production. Once I have confirmation the fixes have been pushed to production, I will close this (and the other) issues. We're working to get those pushed as soon as possible. It will be no later than tomorrow. Thanks!

**Comment by kiadso** [comment]
This fix has been pushed to production. Please re-open if you are still seeing these. Thanks everyone!

**Comment by eanders** [comment]
As a note for future folks with this issue.  If your BedInventory count looks correct in your exported CSV, but the lsa_Inventory file contains zero in the BedInventory column, it may be because that is a calculated column based on the sum of the bed types.
```
CHVetBedInventory + YouthVetBedInventory + VetBedInventory
  + CHYouthBedInventory + YouthBedInventory + CHBedInventory
  + OtherBedInventory
```

There's a note in the code describing this.  
https://github.com/HMIS/LSASampleCode/blob/93b94cd9feb0fd6d3e4d224b5908450e8167a642/02%20LSA%20Output%20Tables.sql#L133-L147
