### ISSUE TITLE
5.8.4 Possible Performance Increase

### ISSUE THREAD

**Issue by jbloescw** [MollyMcEvilley/LSASampleCode#889]
Some of our clients have very large shelters which results in vast numbers of bed nights.  5.8.4 was choking on the amount of records so I broke the derived select statement that created the gap table into two parts.
First just limited the amount of records it really had to deal with.  The 2nd part created the gap table for the query to use to join on for the insert into ch_Include

--Limit the amount of records we will be dealing with in the next step
Select DISTINCT
	s.PersonalID
	, s.ESSHStreetDate
INTO #a584
From #ch_Include s
WHERE s.PersonalID NOT IN (SELECT PersonalID FROM #ch_Include WHERE ESSHStreetDate = DATEADD(dd, 1, s.ESSHStreetDate))

--Create the gap table to be used for the next step
SELECT DISTINCT 
		  s.PersonalID
		, s.ESSHStreetDate AS StartDate
		, MIN(e.ESSHStreetDate) AS EndDate
INTO #gap	--Drop Table #gap
FROM #a584 s
	INNER JOIN #ch_Include e 
		ON e.PersonalID = s.PersonalID 
		AND e.ESSHStreetDate > s.ESSHStreetDate 
		AND DATEADD(dd, -7, e.ESSHStreetDate) <= s.ESSHStreetDate
GROUP BY s.PersonalID, s.ESSHStreetDate

INSERT INTO #ch_Include (PersonalID, ESSHStreetDate, Step)
SELECT gap.PersonalID, cal.theDate, '5.8.4'
FROM #gap AS gap
	INNER JOIN #ref_Calendar cal
		ON cal.theDate BETWEEN gap.StartDate AND gap.EndDate
	LEFT OUTER JOIN #ch_Include chi 
		ON chi.PersonalID = gap.PersonalID 
		AND chi.ESSHStreetDate = cal.theDate
WHERE chi.ESSHStreetDate is null

For testing I'm seeing the same number of records here as I do when testing against the original select statement; which is 0.  
@MollyMcEvilley can you see if this new method lines up with your original code?  Output should be the same but for us yields a massive cut in processing time.  (Not seen in code above is my handling of dropping those temp tables if they exist)

**Comment by jbloescw** [comment]
I was able to do this for a couple other sections.  Molly if you want to get together to review we can.

**Comment by MollyMcEvilley** [comment]
Closing out issues from previous years BUT I did create an issue for this year that references this issue.
