### ISSUE TITLE
Flag 26-1 & 28 (invalid Geocode & ZIP, false positives)

### ISSUE THREAD

**Issue by OksanaSukhorukova** [MollyMcEvilley/LSASampleCode#890]
Hi @kiadso 
![image](https://user-images.githubusercontent.com/71442061/146356197-08ebb950-e68f-4e82-bcfc-55db55ca6ba4.png)
But all geocodes in ProjectCoC.csv are correct
![image](https://user-images.githubusercontent.com/71442061/146368845-e7702eba-0e6c-44ca-a1d8-f8fbbdad7ca9.png)
The “0” at the beginning of each geocode for Alameda appears to be dropped off in the validation system
Could you please take a look?

**Comment by nataliesus** [comment]
Hi @kiadso ,

I just wonder if this flag was disabled for some reason until yesterday? Last year it worked perfectly fine without trimming leading zeros.

Best regards,
Natalie

**Comment by kiadso** [comment]
Vendor meeting: from Candice Wiseman to everyone:    12:28 PM
I saw this issue this morning for leading zero on Geocode - could there be a similar issue for leading zero on zip code?  

(We'll include this in our triaging, thanks Candice!)

**Comment by vlopez0603** [comment]
Hey, @OksanaSukhorukova @nataliesus , just wanted to check in on this to see if it was still cropping up as an issue on your end. Thanks!

**Comment by OksanaSukhorukova** [comment]
Hi @vlopez0603, this flag isn't received in our last upload https://testing.hudhdx2.info/dataset/1436/warning
