### ISSUE TITLE
Flag 691-2 (Chronic 17 y.o.)

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#891]
Hi @MollyMcEvilley , @kiadso ,

We have Household where hhid.HHChronic = 2 (because of HoH's data, there are no more HH members with ActiveAge between 18 and 65)
![image](https://user-images.githubusercontent.com/28144855/146397225-364911b5-6a27-483e-a6b9-053cc3fcb968.png)
![image](https://user-images.githubusercontent.com/28144855/146397457-4eef5148-ac0f-4195-adb4-9b09311d555f.png)

As a result, Household **cannot** be counted for Population = 15 (it requires `hhid.HHChronic = 1`)

Other, non-HoH client in the Household who has **ActiveAge = 17** has tlsa_Person values that allow this person be counted for **Population = 53**
![image](https://user-images.githubusercontent.com/28144855/146397888-7c865909-b68a-47ff-b652-2f8606b087d3.png)

As a result, the same Household is not counted for Population = 15 but is counted for Population = 53.

I wonder if for Population = 53 calculation we also should apply HoH or adult restriction (`and (n.RelationshipToHoH = 1 or n.ActiveAge between 18 and 65)`)? Because if we have it, the values will be the same and the flag will be resolved.

Also, in the flag description it is said that Population = 53 is for HoH or adults, but as we just said, there is no HoH or adult restriction doing calculations for Population = 53: 
![image](https://user-images.githubusercontent.com/28144855/146399462-cb9650c2-b4f2-4bc3-be40-d53fc444f44e.png)

Could you please take a look?

Thank you,
Natalie

P.S. if it requires changes in Sample Code, please be sure to update Spec as well.

**Comment by nataliesus** [comment]
I feel like we do need to update Sample Code and Spec and not only for Population = 53 but also for Population = 54

![image](https://user-images.githubusercontent.com/28144855/146401052-f52050e0-20f5-46e3-97e9-6bb4aa1051a5.png)

![image](https://user-images.githubusercontent.com/28144855/146401823-f1090b3d-2701-4734-8ff1-fb394a1a56cb.png)

**Comment by MollyMcEvilley** [comment]
Was the 17 year old served later in the report period at 18 and/or as the HoH in a CO household?

Assuming that one of these is the case, the counts accurately reflect the specs (CH is a personal characteristic like disability/gender/race/DV status) and the flags will need to take into account that this will occur for minors served as household members and also as HoH (or who age into adulthood).

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley , @kiadso ,

>Was the 17 year old served later in the report period at 18 and/or as the HoH in a CO household?

Yes, client 130110 was also served as an adult in his other project stay in LSA universe. Both his enrollments have `Active = 1`
![image](https://user-images.githubusercontent.com/28144855/146569632-6ac5134b-5ded-4a3c-87ca-50fcd2119389.png)

That is why on step 5.3/5.4 client is inserted into `tlsa_Person` table with non-null field that are used for Populations 53 and 54
![image](https://user-images.githubusercontent.com/28144855/146570437-22bd5b28-1e71-464a-85b2-86b47464201d.png)

Hope this can help to resolve the issue.

Best regards,
Natalie

**Comment by nataliesus** [comment]
I think the flag will be fixed if we update Sample Code adding Adult or HoH restriction (`(n.RelationshipToHoH = 1 or n.ActiveAge between 18 and 65)`) for populations 53 and 54 similar as it was done with "5.12 Set Population Identifiers for Active HouseholdIDs":
![image](https://user-images.githubusercontent.com/28144855/146574879-d79eb0ea-2c69-4c03-8c18-72ae25fddcd5.png)

NOTE; it requires update in Sample Code and Spec

**Comment by kiadso** [comment]
This fix has been pushed to production. Please re-open if you are still seeing these. Thanks everyone!
