### ISSUE TITLE
Flags 1230-xx, 1232-xx, and 1241-xxx

### ISSUE THREAD

**Issue by eanders** [MollyMcEvilley/LSASampleCode#892]
We have one CoC generating about a hundred flags in the above categories.  These appear to be related to the same root cause, which may be related to clients being included in multiple household types during the reporting range.  Would it make sense that clients who had multiple enrollments with different household types would be counted on one side if this equation but no the other? (project vs. CoC?)

I'm imagining a situation where a client stays at an emergency shelter as an individual youth and then also an emergency shelter later in the year as an adult and child household.  That said, it seems odd that all of the CoC counts are zero (if I'm reading the flag file correctly.)  

Any assistance or insight would be very welcome.  Relevant flags are attached.
[uploadFlagsExport.csv](https://github.com/HMIS/LSASampleCode/files/7729380/uploadFlagsExport.csv)

**Comment by kiadso** [comment]
@MollyMcEvilley I know in the meeting you said you'd look at this on your side, I'm also going to submit it to Dev. Please assign it back to me once you're done reviewing!

**Comment by kiadso** [comment]
This has been reclassified as a Warning
