### ISSUE TITLE
Flag 813-1 (valid Geocodes categorized as invalid)

### ISSUE THREAD

**Issue by OksanaSukhorukova** [MollyMcEvilley/LSASampleCode#893]
Hi @kiadso, @vlopez0603,
My upload https://testing.hudhdx2.info/dataset/1440/warning 
![image](https://user-images.githubusercontent.com/71442061/147093377-417301ed-e140-43c3-9dba-efd6383a91dd.png)
But Geocode = 063228 is valid geocode. Could you please take a look?

**Comment by jbloescw** [comment]
Adding to this issue as we are seeing valid geocodes getting flagged.

**Comment by kiadso** [comment]
This has been fixed and pushed to production. Please respond here if you are still seeing issues.
