### ISSUE TITLE
800-1 Project vs. Inventory

### ISSUE THREAD

**Issue by jbloescw** [MollyMcEvilley/LSASampleCode#896]
We have a couple flags showing up for this and are questioning the validity of said flag ID.
It's being flagged because there is no inventory record for the project but the project exists in the LSA Project file.

![image](https://user-images.githubusercontent.com/44415627/148595608-f2d7161c-a7cd-474f-8a1c-1a80636c7822.png)

You can see both projects have ended before report start and the inventory specs say to not include anything where inventory end date is less than report start.

My guess is that this flag rule was not updated when the change to LSA Project was made to allow in projects that have stopped operating before the report start.

Please advise.

**Comment by kiadso** [comment]
Thank you Jeff! Escalating now

**Comment by kiadso** [comment]
This fix has been pushed to production. Thanks Jeff!
