### ISSUE TITLE
Flag 702-61

### ISSUE THREAD

**Issue by MichelleNevius** [MollyMcEvilley/LSASampleCode#898]
Hello
In one of our customers' LSA output, we did encounter a situation that is triggering the flag 702-61 - more households than clients. The investigation revealed that the difference in counts is caused by one specific client. This particular client have 4 episodes in 2 programs (2 each). It just so happens that he turned 18 between those, and during the reporting period. Because of that, two enrollments have ActiveHHType = 3 (child only) while the other two are 1's (adult only) In the final query, calculating values for the LSA_Calculated file, the distinction is being made by “HoH ID + ActiveHHType” - since this particular person have two HH types (and both valid), he’s counted as two households; however the “person count” line counts him once (obviously).
Some details about the client:
Program episodes:
 admission  | discharge  |  prgmid  | hmisptype
------------+------------+----------+-----------
 2020-01-13 | 2020-02-21 | 70547034 | 1
 2020-02-21 | 2021-03-09 | 41358434 | 2
 2021-04-21 | 2021-04-30 | 70547034 | 1
 2021-04-30 | 2021-09-13 | 41358434 | 2
DoB: 2003-01-05, and he’s always in one person household (alone as HoH).
 I’m pretty much stuck on this one. I couldn't find any clear instruction or explanation about a person in this situation. Any help will be highly appreciated.
Best Regards

**Comment by MichelleNevius** [comment]
Credit where credit is due--it was our developer who figured out and wrote out  the above. Anyone know how to handle this? (Note: we can submit an AAQ if that's best plan of action.)

**Comment by kiadso** [comment]
Escalated. Thank you Michelle and developer!

**Comment by MichelleNevius** [comment]
Hi, just checking the status since this has been open a while.

**Comment by kiadso** [comment]
This fix was pushed to production this morning. Thanks for your patience!
