### ISSUE TITLE
NotOneHoH1/3 Calculation - Counting EnrollmentID vs PersonalID - Flag ID 615-1

### ISSUE THREAD

**Issue by evaripatis** [MollyMcEvilley/LSASampleCode#899]
Shouldn't NotOneHoH1 and NotOneHoH3 be basing the calculation on the count of distinct _PersonalID_?  The specs and sample SQL both have it based on the count of distinct _EnrollmentID_, but this seems incorrect.  Couldn't you have the same individual exit their first enrollment during the reporting period and then also begin a second enrollment within the same reporting period?  This would give them two distinct enrollments, resulting in the _same_ HoH being counted twice, thereby having them counted in NotOneHoH1 and NotOneHoH3.

**Comment by OksanaSukhorukova** [comment]
Hi @evaripatis 
Looks like we had a similar question before https://github.com/HMIS/LSASampleCode/issues/875

**Comment by MollyMcEvilley** [comment]
No, EnrollmentID is correct -- we're looking for the total number of enrollments excluded from LSA reporting due to bad data for RelationshipToHoH.

**Comment by evaripatis** [comment]
Molly's 12/9/21 explanation, on that other ticket, helps to clarify the situation.  Thank you.
