### ISSUE TITLE
Content Feedback for Future FY22 Reporting Period

### ISSUE THREAD

**Issue by jessefjorstad** [MollyMcEvilley/LSASampleCode#905]
We will be starting to update specifications and sample code for FY22 reporting in the coming weeks and are gathering input from several sources, including from the vendor community. 

Once data collection closes we will hold a feedback session to discuss process. At this time we are looking for feedback on content. Please note that we are tracking the issues that have been reported in GitHub and there is **no need to resubmit any issue that has previously been submitted**. Please submit your feedback prior to the end of the day on 2/7/22

In this thread please respond with any additional feedback you have regarding changes to the specs, including but not limited to:

> new populations

> new calculations

> changes to measures to more accurately capture a concept

**Comment by TanyaPieterse** [comment]
Hi,
Just an idea, but it will be amazing if HUD could address the HIC/HMIS Inventory records and how it impacts the LSA in one of their monthly HMIS Admin training sessions.  Or even just a quick training on HMIS Inventory.  It seems for almost all of our Communities, the HIC/Inventory/Utilization/Prior LSA comparisons are the most challenging.

All in all this year's LSA seemed a lot smoother, and less flags.

Thank you to everyone for all the hard work on this Report, and a huge shoutout to Molly for the Sample Code, without it I would be lost!

Thanks

**Comment by jessefjorstad** [comment]
@TanyaPieterse thank you for this comment. I agree that communities could benefit from additional guidance on inventory. We did go over some inventory tips in the September System Admin Call. It may help communities to refer back to it.
Here are the slides for that call: https://files.hudexchange.info/resources/documents/HMIS-Lead-System-Administrator-Monthly-Webinar-Slides-September-15-2021.pdf
Here is the recording: https://www.youtube.com/watch?v=AmU_-jUzhU8&feature=youtu.be

**Comment by eanders** [comment]
We've heard from communities that they would appreciate if the LSA could include a street outreach component.  Some communities we work with have a significant percentage of their populations living exclusively on the street and the LSA currently ignores those populations entirely.

**Comment by eanders** [comment]
It would be amazing if the flag calculations could be included in the sample code in such a way as to generate tables, [similar to the data quality tool](https://www.hudexchange.info/news/version-1-of-the-hmis-csv-data-quality-tool-now-available-for-local-use/), that could be used for tracking down why a particular flag is being triggered.  

Alternatively, or in addition, perhaps the data quality tool calculations could be integrated into the DQ report already embedded in the glossary.  We are seeing a surging interest in being able to identify the data quality issues that come up when submitting a report to HUD.  Having a coding spec specifically designed to catch the issues flags are looking for would enable us to expose those to communities continuously so they aren't surprised and frustrated as the deadlines approach.  (Obviously, a huge burden of this should fall on vendors as well, but having clear direction about where to focus the effort would be extremely helpful.)

**Comment by MollyMcEvilley** [comment]
Closing out issues from previous years...
