### ISSUE TITLE
1063-1 Assistance

### ISSUE THREAD

**Issue by jbloescw** [MollyMcEvilley/LSASampleCode#907]
I may need additional information to troubleshoot this one since the flag file doesn't explain how it gathered the numbers.
**CoC**: MO-503
**ProjectID**: 245

**Flag Description**: Adult-Only households: None of this project's clients in this household type were people in youth-only households, yet you reported that all of these beds are dedicated to youth households. Please confirm.

**The flag data fields are saying**:
AO HHs: Total people in youth-only households where the oldest adult is 18-21	= 0	
AO HHs: Total people in youth-only households where the oldest adult is 22-24	= 0	
AO HHs: Total people = 27

**Troubleshooting**:
I've looked at LSA Calculated and I see that projectID on report row 54 for HHType = 1 and Population = 0 and Cohort = 1.  That value there is 27.
I also see the same value of 27 on another row by changing the population from 0 to 10 (Youth Households 18-21).  

I believe I also hunted these folks down in tlsa_Household and all 27 records show HHAdultAge = 18

Is this flag not counting something or am I looking in the wrong areas?  
Or is this customer working off an older flag and I'm seeing good data that would quell this flag?

Thank you.

**Comment by LaurenBianchi** [comment]
We have a community that is experiencing this same issue.

**Comment by kiadso** [comment]
Hi, we have looked at this and the current suggestion on it is to ask communities to check their households' DOBs, the projects' bed dedication, like if the beds are set as youth beds, and to reach out to their liaisons if they have any questions about this flag.

Thanks for your patience-

**Comment by jbloescw** [comment]
I'm still not convinced on this one.  Can the flag fields be updated to better reflect how they are arriving at the numbers.  It makes it so that we can track down the section and code that is generating the numbers so we can help the customer.  Otherwise it's just a bunch of guesses which is not good.


Since the flag description from HUD provides no reference to how they are arriving at their numbers, we have to do some assumptions.

**First is the 27 households**:  In LSA Calculated, I'm seeing report row 54 for this population/cohort/ProjectID/Universe.  This population is for those who are in a youth household ages 18-21.

Unless the flag is looking at other fields to arrive at their number of 27, things look good here.  The enrollment members of these 27 households have an entry age and active age of 21 which again backs up the legitimacy of this data.

Conclusion: This project has 27 youth households ages 18 to 21.

**Inventory**:  There are 6 rows in LSA Inventory for this ProjectID and all of them with Youth Bed Inventory numbers and household types of Households without children and Households with only children.

Conclusion: The way these are setup look fine to us.

**Final Thought:**  These 27 should meet the criteria of being in a youth household according to what we see as described above but are not showing up in the flag fields:

AO HHs: Percentage of total people served that were in youth-only households where the oldest adult was 18-21
AO HHs: Total people in youth-only households where the oldest adult is 18-21
