### ISSUE TITLE
Flag 684 re Ethnicity != 0

### ISSUE THREAD

**Issue by kcourtneywellsky** [MollyMcEvilley/LSASampleCode#909]
We are currently experiencing a high volume of clients with Flag 684 related to Ethnicity.

The Flag description states "There is a discrepancy between your LSAPerson and LSACalculated data. You reported different numbers of people active in residence for the following population. These two numbers must be equivalent."

Here is an example of one variation of Flag 684 from one of our clients' flag files, 

"ALL households in ES/SH/TH:non-Hispanic/non-Latino people"

The flag SAS logic for LSAPerson says: 
"LSAPerson version of this field computed as the sum of RowTotal where HHTypeEST>-1 and AHAREST>-1 and **Ethnicity!=1**". 

The flag logic for LSACalculated says:
"LSACalculated version of this field computed as the number in the Value field where Cohort=1, Universe=16 & HHType=0 & **Population=65** & ReportRow=55".

After closely reading through the history of Github issue #868 , I see where the original post says they were experiencing this flag because the flag logic at the time was using "Ethnicity = 0" to mean "non-Hispanic/Latin(a)(o)(x)", and that this was in contrast to the LSA specifications on page 141, which has criteria for Pop ID 56 "White, non-Hispanic/Latin(a)(o)(x)" defined as "Race = 5 and Ethnicity <> 1". So the OP requested that the flag logic be changed to "Ethnicity !=1" to match the specs. The flag logic was changed on or around Dec. 14th. Then other vendors comment that they are having problems with the new flag logic because Ethnicity = 0 does not mean Ethnicity !=1. 

Then according to the last comment on Jan. 11, another change was made to the flag logic. However, based on the recent flag files from our clients, it appears the flag logic currently says "Ethnicity != 1". While this does match the specifications, we are experiencing the same problem as the vendors who commented on Dec. 15th and Dec. 17th. 

The HUD value for "Non-Hispanic/Non-Latin(a)(o)(x)" is 0 in the FY2022 HMIS Data Dictionary. The criteria for Population 65, listed as "Non-Hispanic/Latin(a)(o)(x)", is "Ethnicity = 0". However, when the flag logic attempts to equate Population 65 to "Ethnicity != 1", it is essentially trying to say that "Ethnicity = 0" is the same as "Ethnicity IN (0,8,9,99)", and this is not the case.

The Ethnicity criteria for Populations in the LSA specifications appear to be incorrect for multiple Populations. Populations 61 and 62 use the opposite values for Ethnicity than their descriptions list. Populations 56 and 58 include "non-Hispanic/Latin(a)(o)(x)", but their criteria reads "... Ethnicity<>1", which is incorrect due to the same reasons listed above.

We would like for the Flag 684 SAS logic for LSAPerson to either be changed to "... AND Ethnicity=0", or, if that's not possible, for the Flag to be turned off for now.

**Comment by kiadso** [comment]
Hi Kern, What CoC are you seeing this on?

Thanks
Genelle

**Comment by kcourtneywellsky** [comment]
We have 40 CoCs with the 684 flag, but the most recent one is OK-501.

**Comment by kiadso** [comment]
Hi Kern,
I checked out OK-501 and they are not showing this error anymore since their upload on 2/9/2022. The last time 684 flagged (according to the data coming out of the vendor flag files) was January 9th, which is prior to the previous fix, which was pushed to production on January 11. To understand this more fully, we would like to see this happening on a CoC that uploaded after the original fix. Please re-open this if you think we should review this for FY2022!
Thank you, Kern!
Genelle
