### ISSUE TITLE
Inventory End date question may relate with 781

### ISSUE THREAD

**Issue by 2008zjqc** [MollyMcEvilley/LSASampleCode#910]
Good morning,
I have a question regarding inventory end date, which may relate with flag 781.
In section 4.5 while preparing the lsa_inventory record, the following is the condition been used.

and (hi.InventoryEndDate is null 
			or (hi.InventoryEndDate >= rpt.ReportStart
				and hi.InventoryEndDate > hi.InventoryStartDate)

With such condition, those projects with inventory end date prior to report start date will be gone from lsa_inventory table.
However those projects also involved in LSA calculation table. 
Therefore it will trigger 781, that is project showing up under LSACalcucated, but not inventory.
My general question is how to report inactive inventories in LSA without trigger flags?

Best,
Chen

**Comment by kiadso** [comment]
Hi Chen, thank you- given where we are in the development cycle, we will be reviewing this one for FY2022 LSA.

**Comment by MollyMcEvilley** [comment]
If there are counts in LSACalculated for the active and/or point-in-time cohorts, there has to be at least one Inventory record where InventoryEndDate is NULL or greater than ReportStart. If there's no active inventory, there shouldn't be any active clients... so in this case the flag would be correct and either the enrollment or PDDE data will need to be corrected.
