### ISSUE TITLE
Suggestion to use "Lookback" instead of "LookBack" in LookBackDate columns

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#912]
Hi @MollyMcEvilley ,

Not an issue, just wonder if we can use "Lookback" word in the same register through all sample code? It is "Look*B*ack" in some places.

![image](https://user-images.githubusercontent.com/28144855/183265507-47379930-37b5-4ce0-8e81-a70e4f8f051a.png)

Note: there are several places to update through sample code files

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
I did a find and replace on all of the SQL files and this (in 03_01 LSA Parameters and Metadata.sql) is the only one that GitHub picked up as a change after I saved.  Commit forthcoming...
