### ISSUE TITLE
06 LSAHousehold.sql: why prev changes were reverted?

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#913]
Hi @MollyMcEvilley ,

There was a commit on Jan 27, 2022:
![image](https://user-images.githubusercontent.com/28144855/183265769-e6196a44-9a24-4bf5-b9dd-76d9837d45a1.png)

With the commit from July 29, 2022 the changes were reversed but in the annotation it is said that nothing was changed:
![image](https://user-images.githubusercontent.com/28144855/183266092-5eba160e-d32c-4737-b2ab-35aeeccf8cb6.png)

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Ah... because I foolishly started with the versions of the sample code files from the Jan 12 release, which didn't include the fix on Jan 27.  Commit forthcoming to re-instate that.

ETA:  Details of the original issue addressed by the change I'm re-instating are in issue #902
