### ISSUE TITLE
07 LSAExit.sql: LastInactive calculation issue

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#914]
Hi @MollyMcEvilley ,

"hhid.EntryDate < cd.LookbackDate" is not the same as "dateadd(dd, -1, hhid.EntryDate) < '9/30/2012'". Could you please take a look?
![image](https://user-images.githubusercontent.com/28144855/183266239-13de52b6-ff82-41a9-aff0-7958e318db76.png)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
With a fixed **LookbackDate** of 10/1/2012, 9/30/2012 was the equivalent of [**LookbackDate** - 1 day], so the goal is to identify instances when we should use [**LookbackDate** - 1 day] as **LastInactive**.

FY21 code does this when [**EntryDate** - 1 day] < [**LookbackDate** - 1 day].

FY22 code does this when **EntryDate** < **LookbackDate**.  

I _think_ that these will always evaluate identically.  Am I missing something?

**Comment by eanders** [comment]
Those look identical to me.
old: if day before the entry date < day before original look-back date then use the day before the look-back date
new: if the entry date is < look-back date, then use the day before the look-back date.
