### ISSUE TITLE
lsa_Project table may need additional restrictions

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#918]
Hi @MollyMcEvilley ,

It was announced that this year non-HMIS participating programs and VSP enrollments should be excluded.

[NoCoC] and [NotOneHoH] and step 3.3.1 use next restrictions:
- HMISParticipatingProject = 1
- VictimServiceProvider = 0

I wonder if we should also use the same limits to insert data into **lsa_Project** table? if yes, then we can remove [HMISParticipatingProject = 1] and [VictimServiceProvider = 0] from [NoCoC] and from [NotOneHoH] because these conditions will be in lsa_Project table.

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
No, the logic for the list of projects included in Project.csv remains the same.
