### ISSUE TITLE
Spec: Project-focused definition question

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#919]
Hi @MollyMcEvilley,

It was announced that this year non-HMIS participating programs and VSP enrollments should be excluded.

I wonder if we should add next rules to the spec:
- HMISParticipatingProject = 1
- VictimServiceProvider = 0

![image](https://user-images.githubusercontent.com/28144855/183312679-71fd19db-bf19-4266-b068-6b87430606db.png)

Please disregard if it doesn't make sense.

Best regards,
Natalie

**Comment by nataliesus** [comment]
btw, do we need one more closing parenthesis?
![image](https://user-images.githubusercontent.com/28144855/183312830-84df4653-f2e5-4c86-bc68-c2499ab19eff.png)

**Comment by MollyMcEvilley** [comment]
It is not necessary to limit the projects available to select for a project-focused LSA by _VictimServiceProvider_ and/or _HMISParticipatingProvider._   

(Thank you for the note about the missing parenthesis -- commit with a correction is forthcoming, but I am closing out this issue as it is principally related to the question about the parameters for including projects in the upload.)
