### ISSUE TITLE
Spec: Cohort = 20 should be removed

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#920]
Hi @MollyMcEvilley ,

Could you please take a look if cohort = 20 should be kept in the spec? It was removed from the Sample Code.

![image](https://user-images.githubusercontent.com/28144855/183313055-23ebf06a-beef-4a21-b484-441e40ef8364.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Yes, thank you!  Commit forthcoming.
