### ISSUE TITLE
Spec: NotOneHoH1 and NotOneHoH3 should be removed

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#921]
Hi @MollyMcEvilley ,

NotOneHoH1 and NotOneHoH3 fields were removed from Sample Code. Should they be removed from Spec?

![image](https://user-images.githubusercontent.com/28144855/183313915-c2c38876-b8f0-4bbf-a026-c0ac374dcf78.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Yes, thank you!  Commit forthcoming.

![image](https://user-images.githubusercontent.com/6156815/185407505-0d6ffdcc-fbc3-4be7-a50e-0cd61dad33e3.png)
