### ISSUE TITLE
Spec: Section 3.3: add HMISParticipatingProject to Source Table

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#922]
Hi @MollyMcEvilley ,

Could you please take a look if HMISParticipatingProject should be added to Relevant Data -> Source table?

![image](https://user-images.githubusercontent.com/28144855/183314313-2fe3d051-45a8-41d2-8eb7-b1e07587f365.png)

This field is used in the programming instructions:
![image](https://user-images.githubusercontent.com/28144855/183314318-2ae837db-be2b-4883-a2ab-7d7e21d4ab08.png)

Also, maybe new hmis_Organization table should be added to the Source Table as `VictimServiceProvider = 0` restriction was added to programming instructions?

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Yes, thank you! Commit forthcoming.

![image](https://user-images.githubusercontent.com/6156815/185406860-3ad2af65-7080-4ee3-91e8-964ccea982ee.png)
