### ISSUE TITLE
Spec: Section 4.1 - some restrictions are missing(?)

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#923]
Hi @MollyMcEvilley ,

This ticket relates to #918.

I wonder if both <Systemwide LSA> and <Project-Focused LSA> should have next condittions:
- hmis_Project.HMISParticipatingProject = 1
- hmis_Organization.VictimServiceProvider = 0

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
No, PDDE data for these organizations and projects should be included in the upload -- it's just the enrollment data that should be excluded.  I revised the description of the change in section 1.4 to clarify.

![image](https://user-images.githubusercontent.com/6156815/185406188-efe6dd00-01b3-4593-8d16-d5ab66d9d97b.png)
