### ISSUE TITLE
Spec: Section 4.1 - should organizations be limited to VictimServiceProvider = 0?

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#924]
Hi @MollyMcEvilley,

In case organizations should be limited to VictimServiceProvider = 0, maybe `Must be in (0,1) – there must be a valid response in this column` text should be updated?

![image](https://user-images.githubusercontent.com/28144855/183314725-ccc09d6f-06d7-43c7-9350-4b7042d97de8.png)

Please advise.

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Hi Natalie!  No, organizations shouldn't be limited to those where _VictimServiceProvider_ = 0 -- PDDE data for the victim service providers should be included.
