### ISSUE TITLE
Spec: Section 3.2 - should 3 year period be removed?

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#925]
Hi @MollyMcEvilley ,

Could you please take a look if 3 year period should be removed from the spec?

![image](https://user-images.githubusercontent.com/28144855/183315003-cade649f-a327-43fe-93b8-1a1fb77aa0d6.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Yes, thank you!  Commit forthcoming.
