### ISSUE TITLE
Section 8.1: cohort = 20 should be reworked

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#926]
Hi @MollyMcEvilley ,

I have doubts about using cohort = 20 for rows 58-61. Could you please take a look?

![image](https://user-images.githubusercontent.com/28144855/183315304-3bbc522e-6614-4841-9cbc-f3c7764396ce.png)

Thank you,
Natalie

**Comment by MollyMcEvilley** [comment]
Your doubts are warranted!  Thank you. Commit forthcoming.
