### ISSUE TITLE
Spec: Sections 10.2 and 10.3 - cohort = 20 should be reworked

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#927]
Hi @MollyMcEvilley ,

Could you please take a look at Sections 10.2 and 10.3? It looks like cohort = 20 should be reworked.

![image](https://user-images.githubusercontent.com/28144855/183316042-69f9db61-ed7c-48a8-b74c-b5117bf24541.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Yes -- thank you!  Commit forthcoming.
