### ISSUE TITLE
Section 11.1: [NoCoC] difference between Sample Code and Spec Programming Instructions

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#929]
Hi @MollyMcEvilley ,

![image](https://user-images.githubusercontent.com/28144855/183397759-01ddada9-ca0c-4e37-b958-0e891d04f3ac.png)

1. Sample lsa_Project table already has a restriction by ContinuumProject.  if ticket #923 makes sense, then restriction by HMISParticipatingProject can be removed and also lsa_Organization table usage can be removed.
2. `RelationshipToHoH = 1` restriction is missing in the spec.
3. missing parenthesis in the sample code.
4. to follow formula code style in the spec, i would recommend adding "and"

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Thank you!  Spec commit forthcoming.
