### ISSUE TITLE
Section 11.3: [RelationshipToHoH] discrepancy between Sample Code and Spec

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#931]

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

![image](https://user-images.githubusercontent.com/28144855/183406096-5fb4e9f6-7ef9-47e2-9053-0944b4089281.png)

1. `and (x.ExitDate is null or x.ExitDate >= rpt.ReportStart)` restriction exists in Sample Code but not in the Spec.
2. `Active = 1` restriction is used in the Spec but is missing in the Sample Code.
3. hmis_Enrollment already has unique [EnrollmentID], not sure why `distinct` is used in both Sample Code and Spec.
4. Could you please remove `hmis_EnrollmentCoC ` table section from Relevant Data -> Source table as this table is not used in query for [RelationshipToHoH]?
![image](https://user-images.githubusercontent.com/28144855/183407557-00db902e-fe3c-4c8e-9aa2-59621451669f.png)


Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Thank you!

I am updating both the specs and the sample code for this... 

![image](https://user-images.githubusercontent.com/6156815/185398482-630503c2-318a-46f1-b895-3adcd0ec74fd.png)
