### ISSUE TITLE
Section 11.4: [MoveInDate] discrepancy between Sample Code and Spec

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#932]
Hi @MollyMcEvilley ,

![image](https://user-images.githubusercontent.com/28144855/183408814-dd917515-30b4-40dd-a1d8-d0431de3c2f6.png)

1. not an issue, but for consistency, could you please use the same either [HouseholdID] or [EnrollmentID] in both Sample Code and Spec for select statement, also, is there any benefit of using distinct in the select statement?
2. [RelationshipToHoH] is not used in sample code, maybe you can remove it from spec (both programming instructions and Relevant Data -> Source table)?

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Yes!  Also removing lsa_Project from the data sources table and adding LSAProjectType to the list of columns under tlsa_HHID. Commit forthcoming.
