### ISSUE TITLE
Spec: section 11.5 - question about "distinct" usage

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#933]
Hi @MollyMcEvilley ,

I wonder why do we need to use distinct if tables already have unique parameters that are used in the select statement?

![image](https://user-images.githubusercontent.com/28144855/183521330-f2e7f67a-6277-4b00-ab24-cb8889fc9901.png)

Could you please advise?

Thank you,
Natalie

**Comment by MollyMcEvilley** [comment]
For the moment, I'm consolidating all conversation related to DISTINCT in the sample code under issue #937... Depending on the outcome, I'll re-open this if necessary.
