### ISSUE TITLE
Spec: Section 11.5: [ClientExit] difference between Spec and Sample Code

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#934]
Hi @MollyMcEvilley ,

Both spec and sample code will return the same result, but maybe it is possible to have the same set of conditions in both sample code and spec?

![image](https://user-images.githubusercontent.com/28144855/183522188-8e4f3fd5-d1c6-472e-8954-7635cf7eff92.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Definitely possible... I'm updating the specs consistent with the sample code.  Commit forthcoming.
