### ISSUE TITLE
Spec: Section 11.6

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#935]
Hi @MollyMcEvilley,

Could you please take a look if hmis_EnrollmentCoC table should be removed from Relevant Data -> Source table?

![image](https://user-images.githubusercontent.com/28144855/183522613-be1fa3e7-80ed-4fae-86f8-891b848c3bf5.png)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
It definitely should -- thanks!  Commit forthcoming.
