### ISSUE TITLE
Section 11.7: [DisablingCond] discrepancy between Sample Code and Spec

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#940]
Hi @MollyMcEvilley ,
![image](https://user-images.githubusercontent.com/28144855/183528125-372bb148-3d2c-4ce7-afea-3e2d1c2906f2.png)

1. could you please remove distinct to not make sql server work on unnecessary calculations?
2. Spec requires using [DisabilityStat] value, but sample code uses [hn.DisablingCondition]. Could you please update so both Sample Code and Spec use the same conditions?

Thank you!
Natalie

**Comment by nataliesus** [comment]
Also, do you really need "distinct" for:
- LivingSituation
- LengthOfStay
- HomelessDate
- TimesHomeless
- MonthsHomeless
- Destination

if not, could you please update both sample code and spec?

**Comment by MollyMcEvilley** [comment]
1.  I'm going to consolidate conversation / questions / issues related to DISTINCT as it is used anywhere in the sample code under issue #937 -- so the commit referenced in 2 below will close out this issue...

2.   I am going to update the sample code to use the specs logic -- it doesn't make any sense to reproduce the DQ check that was essentially already done when populating tlsa_Enrollment... commit forthcoming.
