### ISSUE TITLE
Section 11.4: [MoveInDate] logic should be corrected

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#943]
Hi @MollyMcEvilley ,

What entities should be counted for MoveInDate? Enrollments or Households? Maybe the spec should be updated?
![image](https://user-images.githubusercontent.com/28144855/184262946-8512e319-86db-4381-bc2f-7c61b2ce6fdc.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
In theory, the count of distinct **HouseholdID**s in tlsa_HHID should be identical to the count of distinct **EnrollmentID**s in tlsa_HHID... but the specs shouldn't be confusing on this issue, so I'm updating the specs as shown below.  Commit forthcoming.

![image](https://user-images.githubusercontent.com/6156815/185191879-603056db-655c-4fad-b239-7976438c063f.png)
