### ISSUE TITLE
lsa_Person: [SSNValid] question

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#944]
Hi @MollyMcEvilley ,

[SSNValid] column was added to `tlsa_Person` table. I wonder if we also need [SSNValid] column for the output `lsa_Person` table? If yes, both spec and sample code should be updated.

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
No, we're good. I put it in tlsa_Person so we could use it for DQ reporting now that we no longer need dq_Enrollment (which is where **SSNValid** was last year), but we don't need it in LSAPerson.
