### ISSUE TITLE
Section 11.7: [Destination] question

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#946]
Hi @MollyMcEvilley ,

1. Could you please take a look if we need additional `hmis_Exit.ExitDate <= ReportEnd` restriction as a part of `left outer join` condition so enrollments exited *after* ReportEnd will be included by `x.Destination is null` condition?
![image](https://user-images.githubusercontent.com/28144855/184459723-39ce46b1-8793-4b48-907c-6a029efee321.png)

3. [Destination] =27 was not in the list for FY2021. Just want to confirm it was intentionally added for FY2022.

![image](https://user-images.githubusercontent.com/28144855/184459300-031ca448-64ce-43e1-8474-839ec6ebdb35.png)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
1.  We're okay here. As long as there IS a valid _Destination_, we don't need to count an issue here, even if it's dated after ReportEnd. (The date discrepancy between tlsa_Enrollment and hmis_Exit will get counted in ExitDate.)

2. Yes! It's not a valid value for an exit in FY22.
