### ISSUE TITLE
lsa_Calculated.ReportRow = 62: question about enrollments

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#947]
Hi @MollyMcEvilley ,

You wrote that only enrollments should be limited by:
- hmis_Project.HMISParticipatingProject = 1
- hmis_Organization.VictimServiceProvider = 0

I wonder should these restrictions be also applied to `lsa_Calculated.ReportRow = 62` that uses `hmis_Enrollment` for calculations? If it makes sense, then both spec and sample code should be updated.

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
No, we're okay here.  If the issue of why there is current data in HMIS for a victim service provider and/or a project not participating in HMIS comes up, that's reasonable and possibly beneficial.
