### ISSUE TITLE
Sample Code: [NoCoC] issue

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#948]
Hi @MollyMcEvilley ,

I think there is an issue with `any hmis_ProjectCoC.CoCCode` in the Sample Code:
![image](https://user-images.githubusercontent.com/28144855/185505981-9f2e0e01-d889-4aa1-ba29-a2079faf9411.png)

I.e. Program A has 2 ProgramCoCs: XX-500 and XX-600. There is Enrollment A into Program A with Client Location = XX-500. So everything looks valid. But because of ProgramCoC = XX-600, Enrollment A is counted for [NoCoC] as there is no Client Location = ProgramCoC = XX-600.

Could you please take a look?

Thank you,
Natalie

**Comment by MollyMcEvilley** [comment]
The sample code uses hmis_ProjectCoC and not lsa_ProjectCoC, and there isn't any join to **ReportCoC**.  As long as there is an EnrollmentCoC record for ANY CoC the project is associated with in ProjectCoC, the enrollment won't be counted.
