### ISSUE TITLE
When https://testing.hudhdx2.info/ will be updated to test LSA FY2022?

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#951]
Hi @MollyMcEvilley ,

I know it is another team who works on LSA upload side. But maybe you know when https://testing.hudhdx2.info/module/lsa/uploads/create will be updated to test new LSA FY 2022?

Best regards,
Natalie

**Comment by JulesABrown** [comment]
Thank you for the question. We will keep bringing updated information to the LSA Office Hours call. At this time, we are still anticipating opening the HDX for vendor testing in October.

**Comment by JulesABrown** [comment]
Testing has opened.

**Comment by nataliesus** [comment]
Just in case, new URL for the testing site is: https://hdxdev2.abtsites.com
