### ISSUE TITLE
LSA HMIS CSV Export: a few issues with Disabilities.csv

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#965]
Hi @MollyMcEvilley ,

Our system detected some issues with Disabilities.csv:

**Issue 1:** duplicate disability records for EnrollmentID = 192966.
![image](https://user-images.githubusercontent.com/28144855/193432033-8fc8e3e3-4327-4b5c-9a22-0f3939787eed.png)
Maybe fixing DataCollectionStage will help?

**Issue 2:**
There are very strange rows with empty EnrollmentID, PersonalID, InformationDate at the end of the file:
![image](https://user-images.githubusercontent.com/28144855/193432133-a18a5221-f7ab-464f-a7be-1b83ccde29d2.png)

Could you please take a look?

Perhaps, when these issues are fixed, LSA report should be re-generated again to take into account fixed records.

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
The LSA doesn't use Disabilities data at all.  In fact, I don't even have a table for it in the database I use to generate the LSA output -- it's just a static CSV file.   I am making some updates to the records in case this causes fatal errors at import, but there is no impact on the LSA.

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

Yes, test kit is rejected because of issues in this file. If possible, please fix.

Thank you!
Natalie

**Comment by nataliesus** [comment]
Disabilities.csv was updated. Closing this ticket.
