### ISSUE TITLE
Project.csv: discrepancy between LSA output and HMIS LSA testkit

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#966]
Hi @MollyMcEvilley ,

There are 2 discrepancies:
**1** - Somewhy ProjectCommonName in LSA CSV Export.zip is empty. At the same time, it is not empty and equal ProjectName in LSA HMIS CSV Export.zip.

**2** - both DateCreated and DateUpdated have hour = 0 in LSA HMIS CSV Export.zip and hour = 12 in LSA CSV Export.zip. Could you please take a look? 
NOTE: I highlighted first row only, but it is in each Project row:
![image](https://user-images.githubusercontent.com/28144855/193478613-7381d651-9905-4a62-b39a-afae8589be89.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
1.  ProjectCommonName isn't required for the LSA upload, regardless of whether or not it's populated in the HMIS, so the sample code doesn't export it.  
2.  Commit forthcoming.
