### ISSUE TITLE
LSA CSV Export Temp Tables.zip: tlsa_Person.csv: SSNMissingOrInvalid: 552 vs 96

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#968]
Hi @MollyMcEvilley ,

LSA CSV Export.zip has SSNMissingOrInvalid = 552. But in our system it is 96.

Can it be a programmed issue with "SSN contains any character other than 0-9;"?
![image](https://user-images.githubusercontent.com/28144855/193711636-9bd1ace2-3678-46ec-8669-9593cc087866.png)

Please advise.

Thank you!
Natalie

**Comment by evaripatis** [comment]
I raised a similar question in the following ticket: https://github.com/HMIS/LSASampleCode/issues/959.  That ticket was closed without any correction or explanation, so I would very much be interested in seeing what comes from this ticket.

**Comment by nataliesus** [comment]
This issue was fixed under https://github.com/HMIS/LSASampleCode/issues/979/
