### ISSUE TITLE
LSA CSV Export.zip: NoCoC = 1 question

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#969]
Hi @MollyMcEvilley ,

Could you please tell me the [EnrollmentID] which is reported as NoCoC in LSA CSV Export.zip? It will help a lot.

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
It's EnrollmentID 190635.  The CoCCode in EnrollmentCoC for the enrollment is XX-501 and there are no ProjectCoC records for the Project (1547) where CoCCode = XX-501.
