### ISSUE TITLE
Step 01  / Step 03_01 / Step 4

### ISSUE THREAD

**Issue by TanyaPieterse** [MollyMcEvilley/LSASampleCode#970]
Hi Molly,

This is minor, but I thought I will ask if the below was done on purpose?

**01 Temp Reporting and Reference Tables.sql**
The comments indicate: ref_Calendar - table of dates between 10/1/2012 and 9/30/2023  
But lower down it indicates:
	--Populate ref_Calendar
	declare @start date = '2012-10-01'
	declare @end date = '2022-09-30'
Should we change the @start date to also indicate ReportStart - 7 years?

**03_01 LSA Parameters and Metadata.sql**
It seems ReportDate was excluded from the insert statement.

**04_01 Get Project Records.sql**
This line has not been included: and hp.OperatingStartDate <= rpt.ReportEnd
Should we add it so that it only includes Projects that have started before the Report End Date?

I also noticed the insert of the UserID field has been excluded from being inserted in steps 4.1 through 4.5 - but according to the table design it is a non-null field.

Thanks

**Comment by MollyMcEvilley** [comment]
1. The update to 01 Temp Reporting and Reference Tables.sql was done in this commit:  https://github.com/HMIS/LSASampleCode/commit/1dcff8ec6fcc4df4a8c00773933ecdd14eec92af
2. **ReportDate** is set as the last step in 11 LSAReport DQ and ReportDate.sql.  
3. OperatingStartDate <= ReportEnd is not a bad idea at all, but it hasn't been required by the specs thus far and I don't believe it has caused any issues.  @JulesABrown, is there an HDX flag that checks for OperatingStartDate as compared to ReportEnd?  
4. UserID isn't imported into the HDX and isn't required for the LSA upload.  There's no problem with including it, but it's not necessary.  (The screenshot below is from the specs.)
![image](https://user-images.githubusercontent.com/6156815/197002777-e5f5051c-9ef9-4b6c-bfcb-063d7c62222d.png)

**Comment by TanyaPieterse** [comment]
Thank you!

**Comment by MollyMcEvilley** [comment]
Jules has confirmed that there is no HDX check to compare OperatingStartDate and ReportEnd, so I am closing out this ticket... Thank you!
