### ISSUE TITLE
LSA CSV Export Temp Tables.zip: tlsa_Enrollment.csv - PIT columns use null instead of 0

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#973]
Hi @MollyMcEvilley ,

tlsa_Enrollment.csv has next PIT columns:
- PITOctober
- PITJanuary
- PITApril
- PITJuly

What are allowed values for them? I thought either 0 or 1. And 0 by default.
![image](https://user-images.githubusercontent.com/28144855/194784828-8bc18aa9-016e-435b-b143-6bf9ec4290be.png)

But in the generated csv they are either 1 or null:
![image](https://user-images.githubusercontent.com/28144855/194784898-5915c50e-5e51-4e35-ba1b-49d06e5dc05b.png)

Is it possible to use 0 instead of null? Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Unfortunately, I don't have an HMIS application -- this is an artifact of using Excel VBA to create and package the CSV files.  Fortunately, the values don't make any difference to the end result.
