### ISSUE TITLE
LSA CSV Export Temp Tables.zip: tlsa_Household.csv - LastInactive in 2012 year

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#974]
Hi @MollyMcEvilley ,

I wonder why there are several households with LastInactive in 2012 year if hardcoded 2012-09-30 was replaced with dynamic LookbackDate through all LSA sample code.

![image](https://user-images.githubusercontent.com/28144855/194787833-541dc16d-049d-4b71-8914-c31733b819c5.png)

Could you please take a look and provide the most recent tlsa_Household.csv?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Issue was addressed by this commit/change to code in 06 LSAHousehold.sql:  https://github.com/HMIS/LSASampleCode/commit/307f03a3b6d0662c752dc04b79fedf7450be9e62
