### ISSUE TITLE
Question regarding LSA HMIS CSV Export CoC code

### ISSUE THREAD

**Issue by 2008zjqc** [MollyMcEvilley/LSASampleCode#976]
To whom it may concern:

We have a question regarding LSA HMIS CSV Export.zip. We noticed that in the EnrollmentCoC.CSV file, there are 4 records associated with XX-501 CoC Code; however in the ProjectCoC.CSV there are no projects with XX-501, they are all associated with XX-500. Hope someone can help provide an explanation or fix on this one. 

Thanks very much.

Best,
Chen

**Comment by MollyMcEvilley** [comment]
This isn't great data quality, but it doesn't ultimately impact the output of the LSA as long as the enrollments are appropriately excluded.  

Unless this causes anyone a fatal error in importing the data, I'm not going to address this for this sample data set.
