### ISSUE TITLE
LSA HMIS CSV Export: HealthAndDV.csv - possible issue with [InformationDate] for [DataCollectionStage] = 3

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#977]
Hi @MollyMcEvilley ,

There are many records in HealthAndDV.csv where [InformationDate] for [DataCollectionStage] = 3 is not equal to [ExitDate] in Exit.csv. I.e. EnrollmentID = 181636.

![image](https://user-images.githubusercontent.com/28144855/195220840-29b670c6-fe7b-4626-aaab-99ff5acec50c.png)

Could you please confirm it is OK? I just expected them to be the same date.

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
This is fine.  Not good data quality, but not something that impacts the LSA one way or the other.
