### ISSUE TITLE
LSA CSV Export Temp Tables.zip: sys_TimePadded.csv - date columns format

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#978]
Hi @MollyMcEvilley ,

Is it possible to use 'yyyy-MM-dd' format for columns:
- StartDate
- EndDate
to be consistent with the rest of data columns in other files?

![image](https://user-images.githubusercontent.com/28144855/195222592-7690a718-0b7e-478a-9ac5-f73e6eb0070e.png)

Thank you!

**Comment by MollyMcEvilley** [comment]
This  has been updated in the current version of the sample data set.

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

The date format is still MM/dd/yyyy. Maybe the fix wasn't commited? Could you please take a look?

Thank you!
Natalie
