### ISSUE TITLE
tlsa_Person SSNValid issue

### ISSUE THREAD

**Issue by 2008zjqc** [MollyMcEvilley/LSASampleCode#979]
To whom it may concern,

We encountered exactly the same question as #959. For instance: Person ID 90387 with valid SSN and SSN data quality. But in the tlsa_Person the SSNValid=0. I didn't find detailed explanation regarding this issue. Thus, we submit again regarding it. 

Thanks.
Best,
Chen

**Comment by MollyMcEvilley** [comment]
Thanks so much for the PersonalID!! It helped me figure out that the SSN values in my database were not the same as in the Client.csv from the test kit.
