### ISSUE TITLE
Test kit contains DV data at Data Collection Stage 3 - HMIS Dictionary only required at Data Collection Stage 1 & 2

### ISSUE THREAD

**Issue by KAdlerCW** [MollyMcEvilley/LSASampleCode#980]
Hello, 
There are a lot of testkit HealthAndDV records that have DV data recorded at Data Collection Stage 3. The HMIS Data Dictionary only requires the 4.11 Domestic Violence data element to be collected at Project Start (DataCollectionStage 1) and Update (DataCollectionStage 2). Should we include the DV data recorded at Data CollectionStage 3 in our LSA selection for DVStatus? 

Thanks.

**Comment by MollyMcEvilley** [comment]
Yes -- we don't care about DataCollectionStage as long as the InformationDate falls within the date range of the enrollment (see #981).

There are also some records with a DataCollectionStage of 5 (annual assessment).  Does the presence of these records cause any issues with importing the data?  We could change the DataCollectionStage to 2 for the annual assessment and exit records.

**Comment by KAdlerCW** [comment]
@MollyMcEvilley This does not cause import issues for us, we just wanted to check if those records were valid for inclusion, as excluding them would cause some differences in the DVStatus calculation from what is in the sample output. 

Thank you!
