### ISSUE TITLE
HealthAndDV Information Date Outside of Enrollment Entry and Exit Date

### ISSUE THREAD

**Issue by KAdlerCW** [MollyMcEvilley/LSASampleCode#981]
Hello, 
The TestKit contains at least one record where the HealthAndDV Information Date is outside the associated Enrollment's EntryDate and ExitDate. 

Specifically, PersonalID 92248/EnrollmentID 190265 has a HealthAndDV record with Information Date 10/1/2020 with an EntryDate of 7/8/2021 and ExitDate of 10/1/2021. If this record is included in the calculation of DVStatus, the DVStatus is 10 but if it is excluded due to be outside the enrollment period, the DV status is NULL. 

The LSA Sample temp tables currently includes this record and assigns a DV Status of 10, but we wanted to check if this is correct.

Should we include a record where the information Date is outside the enrollment period when calculating the DVStatus? 

Thanks.

**Comment by nataliesus** [comment]
hI @MollyMcEvilley ,

In addition, maybe we do need to add `dv.InformationDate >= n.EntryDate` restriction for [DVStatus] calculation (restriction not greater than ExitDate already exists)? What do you think?
![image](https://user-images.githubusercontent.com/28144855/196309919-fa50774d-cea1-4a0b-bf40-102b0564702f.png)

it impacts on:
- tlsa_HHID.HHFleeingDV
- tlsa_Exit.HHFleeingDV

that are also used in other calculations. It brings differences in report results.

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
These are both very good points.  

1. We didn't bump the InformationDate values in the HealthAndDV sample data forward by a year as we did with other files.
2. LSA reporting should ignore information dated outside the date range of an enrollment.  (This will require small updates to the specs and sample code for section 3.4.)

Commits forthcoming.
