### ISSUE TITLE
LSA Upload Error

### ISSUE THREAD

**Issue by TanyaPieterse** [MollyMcEvilley/LSASampleCode#985]
Hi Molly,

I am using the latest code that you have made available to us verbatim - thank  you so VERY MUCH!  Just tried an upload to the HDX and received these 2 errors ID 1300 and ID 1301.  I am not really sure where to go from here or how to 'fix' it.  Any ideas?

The report was not run on sample data, but live customer data.

Thanks,

![image](https://user-images.githubusercontent.com/44713006/196543024-7efa9d5c-2e6f-4f1a-ba2f-22557f4fb9b1.png)

[LSACalculated.csv](https://github.com/HMIS/LSASampleCode/files/9815137/LSACalculated.csv)

**Comment by JulesABrown** [comment]
1301 isn't logical and I will look into it.

**Comment by JulesABrown** [comment]
1301 has a typo in it (which we are working on correcting), but it is triggering accurately. It should read, "Since your LSACalculated file has a row with a value **35** in it, you must also have at least one row where the value of Population is 52." In other words, the file is showing at least one Parenting Child Household, therefore there should also be at least one Parenting Child.

@MollyMcEvilley, note that in terms of providing feedback to Tanya, these issues aren't present in the sample dataset - ReportRow 56 is getting created as expected; there are no parenting children in the dataset.

**Comment by TanyaPieterse** [comment]
Hi Jules and Molly,
Is this something that I should try and find in the data that needs to be corrected before the LSA files are created?  Or is something omitted in the code that creates LSACalculated?
Thanks!

**Comment by JulesABrown** [comment]
@MollyMcEvilley I think this would require some investigation into the sample code if Tanya is using it verbatim, right?

**Comment by TanyaPieterse** [comment]
Hi Molly,
I've tested the latest LSA code on a different set of live data and received this upload error again (ID 1301)

![image](https://user-images.githubusercontent.com/44713006/198034966-493830af-061e-4197-b3e9-87eaae27ffe8.png)

The Data Dictionary for the Population List seems to have a mismatch where Value=17 is not relating to Parenting Child Households.  Could this be the cause if these values are used to generate the LSACalculated file?

![image](https://user-images.githubusercontent.com/44713006/198035491-fe84c68a-1e5d-4f80-ae40-cb075f45816d.png)

Thanks,
Tanya

**Comment by JulesABrown** [comment]
@TanyaPieterse can you attach the LSACalculated that's giving you the error this time? The issue is apparently not with that value, but with the value 35. Most likely in the file you're trying to upload, you're having the same problem where there should be a row with the value 52 because you have a value of 35. The flag is *displaying* inaccurately by showing the number 17 there, but it is *triggering* accurately when there is a value of 35, but no corresponding value of 52.

**Comment by TanyaPieterse** [comment]
Hi Jules and Molly,
I've just tried to upload an LSA File using the latest code that I ran on a different set of live data and received the Rejection Code 1301 again.  Here is the LSACalculated file. 
[LSACalculated.csv](https://github.com/HMIS/LSASampleCode/files/9870296/LSACalculated.csv)

I've confirmed the LSACalculated file only contains records where Population=35, and no records where Population=52.  It seems the rows generated for Population=35 happens in Steps 8.4-8.7; but this step inner joins to tlsa_AveragePops; and when this table is filled with data in Step 8.3 only records for Population=35 are included which is why we have nothing in LSACalculated where Population=52.  

Thanks,
Tanya

**Comment by JulesABrown** [comment]
Thanks Tanya-

A note, we have implemented a fix to the typo, so now when you upload this file, you should at least get the correct description of this issue.

Thanks!
Jules

My work day may look different than your work day. Please do not feel obligated to respond out of your normal working hours.

Jules Brown | HMIS SME | he/him | Abt Associates
O: 301.347.5352 | Cell: 773.750.7886

**Comment by MollyMcEvilley** [comment]
The LSACalculated file that Tanya attached is fine -- this is an HDX issue.

There are records for Report Rows 4,5,6,7,and 9 where Population = 35.  These are averages.  They are not reported for Population 52.

For the AHAR counts in LSACalculated, the criteria for population 35 are DIFFERENT from the averages:  tlsa_HHID HHParent = 1, ActiveHHType = 3, and **AHAR = 1**.  So there may be LSACalculated records where Population = 35 for ReportRows 1-52 and no records for Population = 35 for ReportRows 53-57 -- much less for Population = 52.

If there are records in LSACalculated where ReportRow in (53,54) and Population = 35, we would probably also expect to see records for ReportRow 55 where Population = 52.

**Comment by JulesABrown** [comment]
@MollyMcEvilley Ah yes, totally agree re the population, and actually this set was already on our list to be removed as a result of another ticket. 

On the ReportRow flag, though, there should be at least one ReportRow = 56 in the uploaded file, correct?

**Comment by MollyMcEvilley** [comment]
There are a bunch of Row 56 records in the most recent LSACalculated attached above, but in the general sense: 

Row 1 is average days in ES/SH from LSAHousehold where the number of days > 0.  It includes dates prior to the report period.
Row 56 is a count of bednights during the report period.  

It is highly unlikely but theoretically possible to run an LSA where there are records in LSAHousehold where ESDays > 0 but there are no bednights during the report period).

**Comment by JulesABrown** [comment]
@MollyMcEvilley I'm looking at Tanya's original LSACalculated file she attached to the ticket. @TanyaPieterse, do you know if you were to run your most current code for that CoC if you would still be getting results with no ReportRow 56?

**Comment by TanyaPieterse** [comment]
Hi Molly and Jules,

I just ran a new LSA file with the latest code up to the previous commits; it does not include the changes Molly made to the Sample Code today.  When trying to upload, I received a different error however, see screenshot:

![image](https://user-images.githubusercontent.com/44713006/199581878-1c9a8825-4496-47d5-b60f-74757e4f2967.png)

Here is the latest LSACalculated file attached from the upload:
[LSACalculated.csv](https://github.com/HMIS/LSASampleCode/files/9923521/LSACalculated.csv)

Looking at the file, there are records where Population=35, and no records where Population=52.

Hope this helps!
Thanks,

**Comment by JulesABrown** [comment]
That's a different issue we're working right now. It looks like you are getting reportrow 56s, though, so I think we can close this out with the understanding that the Population flag will be corrected and that the missing reportrow 56 in the original upload either wasn't a sample code issue or has since been resolved! Thanks!

**Comment by TanyaPieterse** [comment]
Hi Jules,
Thanks!  I will tray again after the HDX is fixed and see if it resolved :)
