### ISSUE TITLE
Step 6.10: [RRHPreMoveInDays] - null vs 0

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#986]
Hi @MollyMcEvilley ,

What value should be for [RRHPreMoveInDays] column if client is not in ProjectType = 13? Should it be null or 0?

We have it null, but Sample Code calculates it as 0.

![image](https://user-images.githubusercontent.com/28144855/196567856-b7c27a9b-49fd-41ce-b8e7-c119d192d3a5.png)

![image](https://user-images.githubusercontent.com/28144855/196568274-0f9f825b-6383-4613-9c64-2506c7ed67d9.png)

Just in case, according to tlsa_Household table declaration, [RRHPreMoveInDays] column allows  null value.

Please advise if we should update our system to count it as 0. Because it is one of the reasons we have differences comparing with LSA sample output.

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
In the grand scheme of things, it doesn't really matter whether it's set to 0 or null in tlsa_Household... as long as the LSAHousehold.csv column is set to 0.
