### ISSUE TITLE
Sample Code: tlsa_ExitHoHAdult.CHTimeStatus issue (follow-up for #794; step 7.8.2)

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#993]
Hi @MollyMcEvilley ,

`LSA CSV Export Temp Tables.zip` has rows for impossible (according to Spec) CHTime and CHTimeStatus combinations:

1) where **CHTime = null and CHTimeStatus = 3**:
![image](https://user-images.githubusercontent.com/28144855/197305892-8566bf8f-762f-454d-aac7-99c2b82758b1.png)

2) where **CHTime = 270 and CHTimeStatus = 2**:
![image](https://user-images.githubusercontent.com/28144855/197306536-d70aea4f-c125-4890-9edd-37efb4ee08ea.png)

tlsa_ExitHoHAdult.CHTimeStatus was changed under #794.

Here is the most recent sample code and spec parts for step 7.8.2:
![image](https://user-images.githubusercontent.com/28144855/197305578-10e93a95-d428-48a9-93e6-2874cfbf649b.png)

Questions:

1. According to Spec, `[COUNT of ch_Include.ESSHStreetDates] between CHStart and LastActive for those episodes >= 365` condition should be used for CHTimeStatus = [2, 3]. But there is no `time_sum.count_days >= 365` condition for CHTimeStatus = [2, 3] in Sample Code. Could you please take a look?

2. According to Spec, for CHTimeStatus = 3 we should use `There are between 1 and 3 episodes ([COUNT of ch_Episodes])` condition. But there is `time_sum.count_eps < 4` (instead of `time_sum.count_eps between 1 and 3`) in Sample Code. Could you please take a look?

Maybe we should replace
```
ha.CHTimeStatus = case when time_sum.count_eps >= 4 then 2
			when time_sum.count_eps < 4 then 3
			else NULL end
````
with
```
ha.CHTimeStatus = case
                        when time_sum.count_days < 365 then null
			when time_sum.count_eps >= 4 then 2
			else 3 end
```

**Comment by MollyMcEvilley** [comment]
These combinations aren't valid in LSAPerson.csv.  They're fine in the interim tables.
