### ISSUE TITLE
LSA CSV Export Temp Tables.zip: sys_Time.csv - dates in 2012 year

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#994]
Hi @MollyMcEvilley ,

Comparing sys_Time.csv files, there is a difference that LSA CSV Export Temp Tables.zip: sys_Time.csv has sysDate in 2012 year for [sysStatus] = 7 (step 6.14.2) i.e. [HoHID] = 90426. In our system for the same HoHID it starts from 2014-10-01

![image](https://user-images.githubusercontent.com/28144855/197419536-3c92162a-2718-4138-8b1e-9286ad589c73.png)

sys_Time records with [sysStatus] = 7 impact on [Other3917Days] and [TotalHomelessDays] calculation.

Could you please take a look?

Thank you!
Natalie

**Comment by nataliesus** [comment]
Just in case you want to compare:

- our sys_Time.csv:
[sys_Time.csv](https://github.com/HMIS/LSASampleCode/files/9847637/sys_Time.csv)

**Comment by MollyMcEvilley** [comment]
6.14.2 should only be counting dates AFTER LastInactive, but it was also counting dates before LastInactive.  I am pushing out the code correction to close out this issue -- will upload a new test kit shortly.

**Comment by MollyMcEvilley** [comment]
Here is the updated code:  https://github.com/HMIS/LSASampleCode/commit/6cbf7f4871ca2fcf7bd6bc56d9f4325dae27b029
