### ISSUE TITLE
LSA CSV Export Temp.zip tlsa_Exit Return Time question

### ISSUE THREAD

**Issue by 2008zjqc** [MollyMcEvilley/LSASampleCode#997]
Good afternoon Molly,
We have a question regarding LSA CSV Export Temp.zip tlsa_Exit Return Time. 
For HoHID 91500, HHtype=1 in the tlsa_Exit return time=-1 indicates that no sequential return enrollment found (from query section 7.3). However for HOHID 91500, there are two enrollments (enrollment ID 190199 with Entry date 07/28/2022; enrollmentID 191875 with Entry date 11/02/2021 exit date 12/1/2021 of the same type); with query section 7.3 we can compute Return time which is NOT -1. 
Please advise.  Thanks.

Best,
Chen

**Comment by nataliesus** [comment]
Confirm we have the same issue. Do you have ReturnTime = 239? I thought it was on our side but obviously it is not. And it is the only HOHID = 91500 that has a ReturnTime discrepancy.

**Comment by 2008zjqc** [comment]
> Confirm we have the same issue. Do you have ReturnTime = 239? I thought it was on our side but obviously it is not. And it is the only HOHID = 91500 that has a ReturnTime discrepancy.

Yes, we are getting the same return time for HoHID 91500.

**Comment by MollyMcEvilley** [comment]
This is consistent with the specs but identifies a data quality problem with the sample data... The InformationDate for the EnrollmentCoC record for what might reasonably be considered a return does not match the EntryDate for the enrollment.    

![image](https://user-images.githubusercontent.com/6156815/198584906-2f4ac9a1-decb-4a40-b84c-fba38c2e4e58.png)
