### ISSUE TITLE
Warning Flag 985-1 Question

### ISSUE THREAD

**Issue by bdavis-pcl** [MollyMcEvilley/LSASampleCode#998]
Hello,

I have this warning flag showing up:
985-1:
All households in SH: No people were served during the report period in your CoC's HMIS-participating beds for this project type. Please check the data to see if this is correct. If it is, describe any reason(s) why this project type did not serve **ny** households.

For one there is a typo (in bold).

However, I'm more curious why this is showing up at all. My dataset contains no Safe Haven projects. It is accurate I'm serving no people for this project type, however Safe Haven is kind of a special case. Yes, Safe Haven projects still exist, but they are an exception. You can't create new Safe Haven projects. I could understand this warning on other project types, but for this project type it seems rather illogical. How many CoCs will receive this warning? How useful is the data from this warning? 

I don't know if we are supposed to be testing Warning Flags, but I figured I'd toss this one out there. This would also apply to Warning: 990-1, 995-1, and 1000-1.

Any feedback appreciated,
Bryan Davis
The Partnership Center ltd.

**Comment by bdavis-pcl** [comment]
Just adding a reference for why my question is about Safe Havens.
https://www.hudexchange.info/homelessness-assistance/coc-esg-virtual-binders/coc-program-components/safe-havens/

**Comment by JulesABrown** [comment]
We will address the typo. 

I have requested that we further limit the flag for that particular project type in cases where no SH projects are found in project.csv.

**Comment by JulesABrown** [comment]
Note that this request has been approved and will be deployed at some point in a forthcoming round. I am going to close this ticket, but please do keep an eye on your uploads next week, @bdavis-pcl, so we can make sure you're not seeing it come up again.
