### ISSUE TITLE
DV data w. Data Collection Stage 3 Issue

### ISSUE THREAD

**Issue by 2008zjqc** [MollyMcEvilley/LSASampleCode#999]
Hi Molly,

With the updated sample data set, there are still records with DVStatus at data collection stage=3. We can't import such information without modifying the data collection stage, and this impacts our tlsa_household HHFleeingDV and RRHFleeingDV counts; those counts are different from sample result.  (For example: PersonID 91367).
Please take a look and let us know we should handle these. Thanks very much.

Best,
Chen

**Comment by MollyMcEvilley** [comment]
There is no requirement that DV data be collected at exit, but it isn't prohibited.  I would recommend that your import procedures set the value of DataCollectionStage to 2 (update) if your system cannot accommodate a value of 3.
